import{DLD_REQUIRED_COLUMNS,CORE_MARKET_UPLOAD_COLUMNS,DLD_LOCAL_MAX_FILE_BYTES,DLD_LOCAL_MAX_ROWS,DLD_LOCAL_REVIEW_ROW_LIMIT,parseCsvText,normalizeDldTransactionsSource,buildDldMarketImportPreview,buildDldMarketKpis,renderCoreMarketUploadCsv}from'/modules/dld-market-data-import-domain.js';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const syntheticFileHash='a'.repeat(64),syntheticHash=n=>String(n).repeat(64).slice(0,64);
const base=(id,date,amount,area,extra={})=>({transaction_id:`DLD-SYN-${id}`,instance_date:date,trans_group_en:'Sales',procedure_name_en:'Sell - Pre Registration',property_type_en:'Unit',property_sub_type_en:'Flat',property_usage_en:'Residential',reg_type_en:'Off-Plan Properties',area_id:'SYN-AREA-1',area_name_en:'Synthetic Community',procedure_area:String(area),actual_worth:String(amount),project_number:'SYN-PROJ-1',project_name_en:'Synthetic Residences',master_project_en:'Synthetic Master',building_name_en:'Synthetic Tower',rooms_en:'2 B/R',has_parking:'1',...extra});
function builtInRows(scenario){const rows=[base(1,'01-08-2026',1950000,92.9),base(2,'20-07-2026',2050000,97.55),base(3,'15-06-2026',2000000,91.04)];if(scenario==='mixed')rows.push(base(4,'01-08-2026',1800000,90,{trans_group_en:'Mortgage'}),base(5,'bad-date',0,0));if(scenario==='duplicate')rows.push({...rows[0]});return rows;}
const mappings=[['transaction_id','source_record_ref'],['instance_date','transaction_date'],['trans_group_en','transaction_type'],['procedure_name_en','transaction_subtype'],['reg_type_en','registration_type'],['area_id / area_name_en','area_source_ref / area_name'],['project_number / project_name_en','project_source_ref / project_name'],['property_type_en / property_sub_type_en','property_type / property_sub_type'],['actual_worth','transaction_amount_aed'],['procedure_area','transaction_area_sqm + derived sqft / price per sqft']];
let objectUrl,uploaded=null;
async function digest(value){const bytes=value instanceof ArrayBuffer?value:new TextEncoder().encode(value);return[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function digestRows(rows){const hashes=[];for(let start=0;start<rows.length;start+=250){const batch=rows.slice(start,start+250);hashes.push(...await Promise.all(batch.map(row=>digest(JSON.stringify(row)))));document.querySelector('#fileStatus').textContent=`Processing locally: hashed ${Math.min(start+batch.length,rows.length).toLocaleString('en-AE')} of ${rows.length.toLocaleString('en-AE')} rows`;await new Promise(resolve=>setTimeout(resolve,0));}return hashes;}
function showError(message){document.querySelector('#fileStatus').textContent=`Stopped: ${message}`;document.querySelector('#fileStatus').className='error';}
function money(value){return value==null?'Unavailable':`AED ${Number(value).toLocaleString('en-AE',{maximumFractionDigits:2})}`;}
function renderAnalytics(preview){
  const kpis=buildDldMarketKpis(preview.accepted),target=document.querySelector('#analytics');
  if(!kpis.available){target.innerHTML='<p>No accepted sales are available for analytics.</p>';return;}
  const acceptedRate=((preview.acceptedRows/preview.sourceRows)*100).toFixed(2),metricRows=(rows,label='Segment')=>rows.map(row=>`<tr><td>${esc(row.label)}</td><td>${row.transactions.toLocaleString('en-AE')}</td><td>${money(row.totalValueAed)}</td><td>${money(row.weightedAveragePricePerSqftAed)}</td><td>${money(row.medianPricePerSqftAed)}</td></tr>`).join('');
  const communityCountRows=metricRows(kpis.communities.slice(0,5)),communityValueRows=metricRows(kpis.communitiesByValue.slice(0,5)),propertyRows=metricRows(kpis.propertyTypes.slice(0,8)),bedroomRows=metricRows(kpis.bedroomMix.slice(0,8)),projectRows=metricRows(kpis.projects.slice(0,8));
  const registrationRows=metricRows(kpis.registrationMix),periodRows=kpis.monthlyActivity.map(row=>`<tr><td>${esc(row.label)}</td><td><span class="coverage ${row.coverage}">${esc(row.coverage)}</span></td><td>${row.transactions.toLocaleString('en-AE')}</td><td>${money(row.totalValueAed)}</td><td>${money(row.weightedAveragePricePerSqftAed)}</td><td>${money(row.medianPricePerSqftAed)}</td></tr>`).join('');
  target.innerHTML=`<div class="kpis"><article><span>Accepted-row rate</span><strong>${acceptedRate}%</strong></article><article><span>Total sales value</span><strong>${money(kpis.totalTransactionValueAed)}</strong></article><article><span>Median transaction</span><strong>${money(kpis.medianTransactionValueAed)}</strong></article><article><span>Weighted avg price / sqft</span><strong>${money(kpis.weightedAveragePricePerSqftAed)}</strong></article><article><span>Median price / sqft</span><strong>${money(kpis.medianPricePerSqftAed)}</strong></article><article><span>Communities represented</span><strong>${kpis.communityCount}</strong></article><article><span>Off-plan share</span><strong>${kpis.offPlanSharePercent}%</strong></article><article><span>Transaction period</span><strong>${esc(kpis.dateFrom)} to ${esc(kpis.dateTo)}</strong></article><article><span>Rows excluded</span><strong>${preview.rejectedRows.toLocaleString('en-AE')}</strong></article></div>
  <div class="breakdowns"><div><h3>Price distribution</h3><table><thead><tr><th>Measure</th><th>25th percentile</th><th>Median</th><th>75th percentile</th></tr></thead><tbody><tr><td>Transaction value</td><td>${money(kpis.transactionValueRangeAed.p25)}</td><td>${money(kpis.transactionValueRangeAed.median)}</td><td>${money(kpis.transactionValueRangeAed.p75)}</td></tr><tr><td>Price / sqft</td><td>${money(kpis.pricePerSqftRangeAed.p25)}</td><td>${money(kpis.pricePerSqftRangeAed.median)}</td><td>${money(kpis.pricePerSqftRangeAed.p75)}</td></tr></tbody></table></div><div><h3>Off-plan versus ready</h3><table><thead><tr><th>Registration</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${registrationRows}</tbody></table></div></div>
  <div class="analytics-wide"><h3>Period activity</h3><table><thead><tr><th>Month</th><th>Coverage</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${periodRows}</tbody></table></div>
  <div class="breakdowns"><div><h3>Top communities by transaction count</h3><table><thead><tr><th>Community</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${communityCountRows}</tbody></table></div><div><h3>Top communities by transaction value</h3><table><thead><tr><th>Community</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${communityValueRows}</tbody></table></div></div>
  <div class="breakdowns"><div><h3>Property mix</h3><table><thead><tr><th>Property type</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${propertyRows}</tbody></table></div><div><h3>Bedroom mix</h3><table><thead><tr><th>Bedrooms</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${bedroomRows}</tbody></table></div></div>
  <div class="analytics-wide"><h3>Top projects by transaction count</h3><table><thead><tr><th>Project</th><th>Sales</th><th>Total value</th><th>Weighted avg / sqft</th><th>Median / sqft</th></tr></thead><tbody>${projectRows}</tbody></table></div>
  <p class="analytics-note">Calculated only from accepted sales in the selected file. Boundary months are marked partial when the file does not cover the complete calendar month. These descriptive KPIs are not a valuation, market share or complete-market statement.</p>`;
}
function render(preview,label){renderAnalytics(preview);document.querySelector('#summary').innerHTML=`<article><span>Official required columns</span><strong>${DLD_REQUIRED_COLUMNS.length}</strong></article><article><span>Source rows</span><strong>${preview.sourceRows.toLocaleString('en-AE')}</strong></article><article><span>Accepted for review</span><strong class="good">${preview.acceptedRows.toLocaleString('en-AE')}</strong></article><article><span>Rejected</span><strong class="${preview.rejectedRows?'bad':''}">${preview.rejectedRows.toLocaleString('en-AE')}</strong></article><article><span>CORE output columns</span><strong>${CORE_MARKET_UPLOAD_COLUMNS.length}</strong></article>`;document.querySelector('#mapping').innerHTML=mappings.map(([from,to])=>`<article><code>${esc(from)}</code><b>→</b><code>${esc(to)}</code></article>`).join('');const accepted=preview.accepted.slice(0,DLD_LOCAL_REVIEW_ROW_LIMIT).map(row=>`<article class="accepted"><strong>${esc(row.source_record_ref)}</strong><span>${esc(row.transaction_date)} · ${esc(row.area_name)} · ${esc(row.property_sub_type)}</span><span>AED ${row.transaction_amount_aed.toLocaleString('en-AE')} · ${row.transaction_area_sqft.toLocaleString('en-AE')} sqft · AED ${row.price_per_sqft_aed.toLocaleString('en-AE')}/sqft</span><small>staged_admin_review · not imported</small></article>`).join(''),rejected=preview.rejected.slice(0,DLD_LOCAL_REVIEW_ROW_LIMIT).map(row=>`<article class="rejected"><strong>Row ${row.rowNumber} · ${esc(row.sourceRecordRef??'No transaction ID')}</strong><span>${row.reasons.map(x=>esc(x.replaceAll('_',' '))).join(' · ')}</span></article>`).join(''),hidden=Math.max(0,preview.acceptedRows-DLD_LOCAL_REVIEW_ROW_LIMIT)+Math.max(0,preview.rejectedRows-DLD_LOCAL_REVIEW_ROW_LIMIT),reviewLimit=hidden?`<article class="review-limit"><strong>On-screen review is sampled</strong><span>Showing up to ${DLD_LOCAL_REVIEW_ROW_LIMIT} accepted and ${DLD_LOCAL_REVIEW_ROW_LIMIT} rejected rows. ${hidden.toLocaleString('en-AE')} additional rows remain included in analytics and the processed file.</span></article>`:'';document.querySelector('#review').innerHTML=`<article class="source"><strong>${esc(label)}</strong><span>File SHA-256: ${esc(preview.sourceFileSha256)}</span></article>${reviewLimit}${accepted}${rejected}`;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(new Blob([renderCoreMarketUploadCsv(preview.accepted)],{type:'text/csv;charset=utf-8'}));document.querySelector('#download').href=objectUrl;}
function renderBuiltIn(){const rows=builtInRows(document.querySelector('#scenario').value);render(buildDldMarketImportPreview({rows,sourceFileSha256:syntheticFileHash,rowHashes:rows.map((_,i)=>syntheticHash((i+1)%10))}),'Built-in synthetic evidence');}
async function processFile(file){if(!file)return;if(file.size>DLD_LOCAL_MAX_FILE_BYTES)throw new Error('Monthly-file POC exceeds the 50 MB limit');const buffer=await file.arrayBuffer(),text=new TextDecoder('utf-8',{fatal:true}).decode(buffer),parsed=parseCsvText(text,{maxRows:DLD_LOCAL_MAX_ROWS}),normalized=normalizeDldTransactionsSource(parsed),fileHash=await digest(buffer),rowHashes=await digestRows(normalized.rows);uploaded={rows:normalized.rows,fileHash,rowHashes,name:file.name,sourceDatasetRef:normalized.sourceDatasetRef,sourceFormat:normalized.sourceFormat};render(buildDldMarketImportPreview({rows:uploaded.rows,sourceFileSha256:uploaded.fileHash,rowHashes:uploaded.rowHashes,sourceDatasetRef:uploaded.sourceDatasetRef}),`Selected locally: ${uploaded.name} · ${uploaded.sourceFormat}`);document.querySelector('#fileStatus').textContent=`Processed locally: ${file.name} · ${parsed.rows.length.toLocaleString('en-AE')} data rows · ${normalized.sourceFormat.replaceAll('_',' ')} · ready for review`;document.querySelector('#fileStatus').className='success';}
document.querySelector('#scenario').addEventListener('change',()=>{uploaded=null;document.querySelector('#sourceFile').value='';document.querySelector('#fileStatus').textContent='Built-in synthetic preview active.';document.querySelector('#fileStatus').className='';renderBuiltIn();});
document.querySelector('#sourceFile').addEventListener('change',async event=>{try{await processFile(event.target.files?.[0]);}catch(error){uploaded=null;showError(error instanceof Error?error.message:'Unable to process CSV');}});
document.querySelector('#reset').addEventListener('click',()=>{uploaded=null;document.querySelector('#sourceFile').value='';document.querySelector('#fileStatus').textContent='Built-in synthetic preview active.';document.querySelector('#fileStatus').className='';renderBuiltIn();});
renderBuiltIn();
