import test from 'node:test';import assert from 'node:assert/strict';
import {queuePage,queueDefinition,queueFilters} from '../src/finance-workspace-domain.js';
import {adviceDocument,adviceReference,adviceSnapshots} from '../src/payout-advice-domain.js';
import {buildApprovedDocumentHtml} from '../src/approved-document-renderer.js';
test('finance paging rejects unbounded/invalid page sizes',()=>{assert.equal(queuePage({}).size,25);for(const size of [0,100,100000,'bad'])assert.throws(()=>queuePage({size}));assert.throws(()=>queuePage({page:-1}));});
test('malformed finance filters return a client validation error',()=>{for(const input of [{from:'2026-02-30'},{from:'2026-10-11',to:'2026-10-10'},{agentId:'invalid'},{currency:'invalid'},{quarter:'2026-Q5'}])assert.throws(()=>queueFilters(input),error=>error.statusCode===400);queueFilters({from:'2026-10-10',currency:'AED',quarter:'2026-Q4'});});
test('paid rows produce one advice per agent and currency with exact cent totals',()=>{
 const batch={batchReference:'SYNTHETIC-BATCH',decidedAt:'2026-10-09',paymentDate:'2026-10-10',paymentReference:'SYNTHETIC-BANK',evidenceReference:'SYNTHETIC-APPROVAL'},base={agentName:'Synthetic',currency:'AED',agentPayoutAmount:0.1,adjustment:0,quarterKey:'2026-Q4'};
 const result=adviceSnapshots([{...base,agentId:'a'},{...base,agentId:'a',agentPayoutAmount:0.2},{...base,agentId:'b'},{...base,agentId:'c'}],batch);
 assert.equal(result.length,3);assert.equal(result[0].snapshot.total,0.3);assert.equal(result[0].snapshot.items.length,2);assert.equal(result[0].snapshot.approvalReference,batch.evidenceReference);
});
test('agent advice is scoped on the server and other finance queues reject agents',()=>{const actor={id:'synthetic-agent',jobRole:'sales_agent',role:'internal_broker'};assert.deepEqual(queueDefinition('advice-generated',actor).params,[['generated'],actor.id]);assert.throws(()=>queueDefinition('payout-approved',actor));});
test('approved, pending and paid batch queues use item status independently',()=>{const actor={jobRole:'accountant',role:'internal_broker'};assert.deepEqual(queueDefinition('payout-approved',actor).params,[['approved']]);assert.deepEqual(queueDefinition('payout-pending',actor).params,[['submitted']]);assert.deepEqual(queueDefinition('payout-paid',actor).params,[['paid']]);});
const snapshot={agentName:'Synthetic <Agent>',currency:'AED',batchReference:'CPB-SYNTHETIC',approvalDate:'2026-10-09',paymentDate:'2026-10-10',paymentReference:'SYNTHETIC-BANK',total:120,items:[{opportunityReference:'OP-TEST',dealReference:'DL-TEST',property:'Synthetic unit',quarter:'2026-Q4',paid:120,adjustment:20}]};
test('advice reconciles the paid portion and identifies immutable payment evidence',()=>{const data=adviceDocument(snapshot,'PA-TEST');assert.equal(data.total,'Total paid: AED 120.00');assert.equal(data.table.rows[0][2],'AED 100.00');assert.equal(data.table.rows[0][3],'AED 20.00');assert.equal(data.header['Bank payment reference'],'SYNTHETIC-BANK');assert.throws(()=>adviceDocument({...snapshot,total:121},'PA'));});
test('reference is stable and HTML hydration escapes data',()=>{assert.equal(adviceReference({createdAt:new Date('2026-10-10'),adviceNumber:42}),'NYSA-PA-2026-000042');const html=buildApprovedDocumentHtml('payout_advice',adviceDocument(snapshot,'PA-TEST'));assert.ok(html.includes('Agent Commission Payout Advice'));assert.ok(html.includes('\\u003cAgent>'));assert.ok(html.includes('table-header-group'));});
