import test from 'node:test';
import assert from 'node:assert/strict';
import { allocateDealAgentCredit,calculateExpectedCommission,calculateRealtimePayout,mayMaintainPayoutPolicy,
  mayViewPayoutWorkspace,payoutFingerprint,receiptQuarterKey,reconcileCommissionReceipt,validatePayoutPolicy,
  validatePayoutSlabs,workingDayDeadline } from '../src/commission-payout-domain.js';

const slabs=[{lowerAmount:0,upperAmount:100000,agentPercent:40},{lowerAmount:100000,upperAmount:250000,agentPercent:45},{lowerAmount:250000,upperAmount:null,agentPercent:50}];
test('payout fingerprints are stable across object key order',()=>assert.equal(payoutFingerprint({b:2,a:1}),payoutFingerprint({a:1,b:2})));
test('company slabs require zero start, contiguous bands and open final band',()=>assert.equal(validatePayoutSlabs(slabs).valid,true));
test('slab gaps and a closed final band fail safely',()=>{const result=validatePayoutSlabs([{lowerAmount:0,upperAmount:10,agentPercent:40},{lowerAmount:11,upperAmount:20,agentPercent:50}]);assert.equal(result.valid,false);assert.match(result.errors.join(' '),/start where the prior slab ends|open-ended/);});
test('policy validates explicit method currency dates reason and slabs',()=>assert.equal(validatePayoutPolicy({policyCode:'agent_commission',currency:'AED',effectiveFrom:'2026-08-01',triggerMethod:'attained_trigger',reason:'Approved policy structure',slabs}).valid,true));
test('expected commission selects greater of percentage and minimum per represented side',()=>{const result=calculateExpectedCommission({agreedValue:1000000,buyerCommissionPercent:2,buyerCommissionMinimum:25000,sellerCommissionPercent:1,sellerCommissionMinimum:0});assert.equal(result.expectedGrossAmount,35000);assert.deepEqual(result.components.map(x=>x.expectedAmount),[25000,10000]);});
test('referral deducted before company receipt is deducted once',()=>{const result=calculateExpectedCommission({agreedValue:1000000,buyerCommissionPercent:2,referralAmount:5000,referralSettlementBasis:'deducted_before_company_receipt'});assert.equal(result.expectedGrossAmount,20000);assert.equal(result.expectedCompanyReceipt,15000);const credit=allocateDealAgentCredit({confirmedActualReceived:15000,externalReferralAmount:5000,referralSettlementBasis:'deducted_before_company_receipt',originatingAgentId:'a',servicingAgentId:'b',originatingAgentSplitPercent:50,servicingAgentSplitPercent:50});assert.equal(credit.internalCreditedAmount,15000);});
test('referral payable from company receipt is deducted once from internal credit',()=>{const result=calculateExpectedCommission({agreedValue:1000000,buyerCommissionPercent:2,referralAmount:5000,referralSettlementBasis:'payable_from_company_receipt'});assert.equal(result.expectedCompanyReceipt,20000);const credit=allocateDealAgentCredit({confirmedActualReceived:20000,externalReferralAmount:5000,referralSettlementBasis:'payable_from_company_receipt',originatingAgentId:'a',servicingAgentId:'b',originatingAgentSplitPercent:50,servicingAgentSplitPercent:50});assert.equal(credit.internalCreditedAmount,15000);});
test('receipt reconciliation preserves partial receipts and uses latest contributing date',()=>{const result=reconcileCommissionReceipt({expectedCompanyReceipt:20000,receipts:[{id:'1',entryType:'receipt',amount:12000,receivedDate:'2026-08-10'},{id:'2',entryType:'receipt',amount:10000,receivedDate:'2026-08-12'},{id:'3',entryType:'reversal',reversesReceiptId:'2',amount:2000,receivedDate:'2026-08-13'}]});assert.equal(result.confirmedActualReceived,20000);assert.equal(result.varianceAmount,0);assert.equal(result.receiptDate,'2026-08-12');});
test('receipt reversal cannot exceed its referenced receipt',()=>assert.throws(()=>reconcileCommissionReceipt({expectedCompanyReceipt:1,receipts:[{id:'1',entryType:'receipt',amount:1,receivedDate:'2026-08-10'},{id:'2',entryType:'reversal',reversesReceiptId:'1',amount:2,receivedDate:'2026-08-10'}]}),/cannot exceed/));
test('Deal split fields allocate one or two agents and reconcile exactly',()=>{const result=allocateDealAgentCredit({confirmedActualReceived:10001,originatingAgentId:'origin',servicingAgentId:'service',originatingAgentSplitPercent:30,servicingAgentSplitPercent:70});assert.equal(result.lines.length,2);assert.equal(result.lines.reduce((s,x)=>s+x.creditedAmount,0),10001);assert.deepEqual(result.sourceSplit,{originatingAgentSplitPercent:30,servicingAgentSplitPercent:70});});
test('same originating and servicing agent consolidates role components',()=>{const result=allocateDealAgentCredit({confirmedActualReceived:10000,originatingAgentId:'same',servicingAgentId:'same',originatingAgentSplitPercent:30,servicingAgentSplitPercent:70});assert.equal(result.lines.length,1);assert.deepEqual(result.lines[0],{agentId:'same',originatingPercent:30,servicingPercent:70,totalCreditPercent:100,creditedAmount:10000});});
test('Deal split fields must total exactly 100',()=>assert.throws(()=>allocateDealAgentCredit({confirmedActualReceived:100,originatingAgentId:'a',servicingAgentId:'b',originatingAgentSplitPercent:40,servicingAgentSplitPercent:50}),/must total 100/));
test('receipt quarter resets on calendar-quarter boundary',()=>{assert.equal(receiptQuarterKey('2026-03-31'),'2026-Q1');assert.equal(receiptQuarterKey('2026-04-01'),'2026-Q2');});
test('Monday receipt is due Thursday under fixed working-day rule',()=>assert.deepEqual(workingDayDeadline('2026-08-10').countedWorkingDates,['2026-08-11','2026-08-12','2026-08-13']));
test('Thursday receipt skips Saturday and Sunday and is due Tuesday',()=>assert.equal(workingDayDeadline('2026-08-13').releaseDueDate,'2026-08-18'));
test('Friday receipt is due Wednesday with no holiday maintenance',()=>assert.deepEqual(workingDayDeadline('2026-08-14').countedWorkingDates,['2026-08-17','2026-08-18','2026-08-19']));
test('attained trigger applies reached slab only to current Deal credit',()=>{const result=calculateRealtimePayout({agentId:'a',dealReference:'DL-1',receiptDate:'2026-08-10',priorCumulativeAmount:90000,currentCreditedAmount:20000,triggerMethod:'attained_trigger',slabs,policyVersionId:'p'});assert.equal(result.agentPayoutAmount,9000);assert.equal(result.bands.length,1);assert.equal(result.bands[0].agentPercent,45);});
test('progressive trigger divides only current Deal credit across crossed slabs',()=>{const result=calculateRealtimePayout({agentId:'a',dealReference:'DL-1',receiptDate:'2026-08-10',priorCumulativeAmount:90000,currentCreditedAmount:20000,triggerMethod:'progressive_trigger',slabs,policyVersionId:'p'});assert.equal(result.bands.length,2);assert.deepEqual(result.bands.map(x=>x.portionAmount),[10000,10000]);assert.equal(result.agentPayoutAmount,8500);});
test('later attained Deal does not reprice earlier payout',()=>{const first=calculateRealtimePayout({agentId:'a',dealReference:'DL-1',receiptDate:'2026-08-10',priorCumulativeAmount:0,currentCreditedAmount:90000,triggerMethod:'attained_trigger',slabs,policyVersionId:'p'}),second=calculateRealtimePayout({agentId:'a',dealReference:'DL-2',receiptDate:'2026-08-11',priorCumulativeAmount:90000,currentCreditedAmount:20000,triggerMethod:'attained_trigger',slabs,policyVersionId:'p'});assert.equal(first.agentPayoutAmount,36000);assert.equal(second.agentPayoutAmount,9000);});
test('only Director may view payout while only full Admin maintains policy',()=>{assert.equal(mayViewPayoutWorkspace({jobRole:'director'}),true);assert.equal(mayViewPayoutWorkspace({role:'admin',jobRole:'admin'}),false);assert.equal(mayViewPayoutWorkspace({jobRole:'accountant'}),false);assert.equal(mayMaintainPayoutPolicy({role:'admin'}),true);assert.equal(mayMaintainPayoutPolicy({role:'internal_broker',jobRole:'director'}),false);});
