import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {readFileSync} from 'node:fs';
import {unzipSync} from 'fflate';
const root=new URL('../release-artifacts/release-3/consolidated/',import.meta.url),name='nysa-core-consolidated-crm-test-dev146.zip',stem=name.slice(0,-4),read=file=>readFileSync(new URL(file,root)),text=file=>read(file).toString('utf8');

test('consolidated Gate 2 contract freezes scope migrations and CRM Test boundary',()=>{const doc=readFileSync(new URL('../docs/CONSOLIDATED_CRM_TEST_CANDIDATE_GATE_2_CONTRACT.md',import.meta.url),'utf8');for(const marker of ['2.1.0-dev.146','CRM Test only','083_inventory_duplicate_prevention.sql','095_dev146_full_scope_uat_governance.sql','MICROSOFT365_EMAIL_ENABLED=0','CALENDLY_ENABLED=0','Native WhatsApp','Recovery therefore uses the pre-deployment database dump'])assert.match(doc,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));});
test('new cumulative migrations never self-register and use the existing application role',()=>{for(const file of ['088_release5_commission_receipt_realtime_payout.sql','089_agent_employment_leave.sql','090_release6_customer_transaction_document_compliance.sql','091_release6_marketing_material_compliance.sql','092_release3b_matching_completion.sql','093_release3d_microsoft365_email.sql','094_release3d_calendly_scheduling.sql','095_dev146_full_scope_uat_governance.sql']){const sql=readFileSync(new URL(`../src/migrations/${file}`,import.meta.url),'utf8');assert.doesNotMatch(sql,/INSERT INTO schema_migrations/i,file);assert.doesNotMatch(sql,/\bTO nysa_app\b/,file);}});
test('CRM Test deployer is target locked backup first and protects other environments',()=>{const source=text('deploy-crm-test-consolidated-dev146.sh');for(const marker of ['EXPECTED_ROOT=/home/nysareal/nysa-core-dashboard-dd6262a-stage','EXPECTED_DATABASE=nysareal_nysa_r2_rehearsal','EXPECTED_VERSION=2.1.0-dev.146','BASELINE_MIGRATION=094_release3d_calendly_scheduling.sql','LATEST_MIGRATION=095_dev146_full_scope_uat_governance.sql','pg_dump','pre-dev146-app.tar.gz','Production snapshot changed','Production clone snapshot changed'])assert.ok(source.includes(marker),marker);assert.doesNotMatch(source,/EXPECTED_ROOT=.*nysa-crm$/m);});
test('deployer requires every external connector switch to remain disabled',()=>{const source=text('deploy-crm-test-consolidated-dev146.sh');for(const flag of ['PROPERTY_FINDER_SANDBOX_ENABLED','PROPERTY_FINDER_ALLOW_READS','PROPERTY_FINDER_LISTING_IMPORT_ALLOW_READS','PROPERTY_FINDER_PRODUCTION_ALLOW_DRAFT_CREATE','PROPERTY_FINDER_PRODUCTION_ALLOW_PUBLISH','MICROSOFT365_EMAIL_ENABLED','CALENDLY_ENABLED'])assert.ok(source.includes(flag),flag);});
test('end-to-end UAT covers customer through Director payout and role boundaries',()=>{const doc=readFileSync(new URL('../docs/CONSOLIDATED_CRM_TEST_END_TO_END_UAT.md',import.meta.url),'utf8');for(const marker of ['structured requirements','governed matching','Viewing','Offer','Booking','Deal','commission received','Director','Payout','My Task Queue'])assert.match(doc,new RegExp(marker,'i'));assert.match(doc,/do not use real private/i);});
test('candidate ZIP checksum manifests and migration inventory reconcile',()=>{const zip=read(name),sha=crypto.createHash('sha256').update(zip).digest('hex'),manifest=JSON.parse(text(`${stem}.manifest.json`)),entries=unzipSync(zip),names=Object.keys(entries);assert.equal(text(`${stem}.sha256.txt`).trim(),`${sha}  ${name}`);assert.equal(manifest.packageSha256,sha);assert.equal(manifest.version,'2.1.0-dev.146');assert.equal(manifest.migrationCount,95);assert.equal(names.filter(item=>/^src\/migrations\/\d{3}_.+\.sql$/.test(item)).length,95);for(const required of ['app.cjs','package.json','public/app.js','public/email-calendly-ui.js','public/brand/nysa/brand-assets.json','public/brand/nysa/vector/nysa-horizontal-dark.svg','public/brand/nysa/raster/nysa-horizontal-light@2x.png','src/server.js','src/migrations/095_dev146_full_scope_uat_governance.sql','MANIFEST.sha256','RUNTIME_MANIFEST.sha256'])assert.ok(names.includes(required),required);for(const entry of names)assert.ok(!entry.includes('\\')&&!entry.startsWith('/')&&!entry.split('/').includes('..'),entry);});
test('candidate archive excludes private runtime and unrelated development material',()=>{const names=Object.keys(unzipSync(read(name)));assert.ok(!names.includes('.env'));for(const prohibited of ['storage/','node_modules/','test/','tools/','outputs/','.git/'])assert.ok(!names.some(item=>item.startsWith(prohibited)),prohibited);});
