import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {validateOpportunityTransition} from '../src/opportunity-domain.js';
import {validateViewingOutcome} from '../src/matching-viewing-domain.js';
import {validateOfferEvent} from '../src/offer-domain.js';
const read=p=>fs.readFileSync(path.join(process.cwd(),p),'utf8');
test('LEAD-ID-22 migration gives Leads a transaction-safe governed reference and historical backfill',()=>{
 const sql=read('src/migrations/061_dev90_reference_and_status_governance.sql');
 assert.match(sql,/lead_month_number_counters/);assert.match(sql,/YYYYMM/);assert.match(sql,/NYSA-LD-/);assert.match(sql,/\[0-9\]\{6\}/);assert.match(sql,/COALESCE\(m\.last_value,0\)\+ROW_NUMBER/);
});
test('LEAD-INV-20 and OPP-INVENTORY-ELIGIBILITY-27 revalidate live Inventory server-side',()=>{
 const r=read('src/routes/opportunities.js'),crm=read('src/routes/crm.js'),app=read('public/app.js');
 assert.match(r,/async function requireLiveInventory/);assert.match(r,/async function requireOpportunityInventory/);assert.match(r,/nysa_inventory_effective_status\(l\.id\) NOT IN \('Sold','Rented','Closed'\)/);assert.match(r,/requireLiveInventory\(checked\.value\.listingId/);assert.match(r,/requireLiveInventory\(match\.listingId/);assert.match(r,/cannot be scheduled for viewing/);assert.match(r,/requireOpportunityInventory\(listingId,requirement,input\.transactionType,client\)/);
 assert.match(crm,/async function rejectUnavailableLeadInventory/);assert.match(crm,/nysa_inventory_effective_status\(l\.id\) NOT IN \('Closed','Sold','Rented'\)/);assert.match(crm,/FOR UPDATE OF l/);assert.match(crm,/insertCapturedLead[\s\S]*rejectUnavailableLeadInventory\(b\.listingId,client\)/);assert.match(crm,/selected Inventory is sold, rented, administratively closed/);assert.match(app,/x\.currentlyEligible/);
});
test('UI-LEAD-TITLE-21 and LEAD-ID-22 show the governed Lead reference in the lifecycle detail',()=>{
 const app=read('public/app.js'),crm=read('src/routes/crm.js'),dash=read('src/routes/dashboards.js');assert.match(app,/SELECTED LEAD LIFECYCLE.*leadReference/);assert.match(app,/lead\.leadReference/);assert.match(crm,/l\.lead_reference ILIKE/);assert.match(dash,/leadReference.*currentStatus/);assert.match(dash,/lead_reference,l\.current_status/);
});
test('OPP-ID-22 displays and searches the durable Opportunity reference',()=>{const routes=read('src/routes/opportunities.js'),ui=read('public/app.js');assert.match(routes,/o\.opportunity_reference ILIKE/);assert.match(ui,/opportunity\.opportunityReference/);assert.match(ui,/activeOpportunityReference/);});
test('OFFER-RECOVERY-MIS-29 and OPP-TERMINAL-OFFER-RECOVERY-31 retain terminal evidence and open auditable recovery',()=>{
 const r=read('src/routes/opportunities.js'),sql=read('src/migrations/061_dev90_reference_and_status_governance.sql'),ui=read('public/offer-ui.js'),app=read('public/app.js');
 assert.match(r,/recovery_checkpoint='terminal_offer'/);assert.match(r,/recovery_state='offer_recovery'/);assert.match(r,/terminal_offer_recovery/);assert.match(r,/terminal_offers/);assert.match(r,/average_recovery_age_days/);assert.match(r,/recovered_acceptances/);assert.match(sql,/predecessor_offer_id/);assert.match(ui,/offer-recovery-form/);assert.match(ui,/predecessorOfferId/);assert.match(app,/Terminal Offer recovery MIS/);
});
test('OFFER-INVENTORY-RELEASE-30 releases only the reservation owned by the terminal Offer and recomputes effective status',()=>{
 const r=read('src/routes/opportunities.js');assert.match(r,/async function releaseOfferOwnedReservation/);
 assert.match(r,/b\.offer_id=\$1 AND b\.opportunity_id=\$2/);assert.match(r,/inventoryStatusBefore/);
 assert.match(r,/UPDATE inventory_assignments SET state='delinked'/);assert.match(r,/nysa_inventory_effective_status\(\$1\)/);
 assert.match(r,/unsafe prior Inventory status/);
 assert.equal(validateOfferEvent('accepted',{eventType:'withdrawn',reason:'NYSA withdrew after reservation',direction:'outbound'}).value.eventType,'withdrawn');
});
test('OPP-STAGE-VALIDATION-32 permits Negotiation to controlled Closed Lost without a Deal',()=>{
 const d=read('src/opportunity-domain.js');assert.match(d,/\['Requirements','Matching','Viewing','Offer','Negotiation'\]/);assert.match(d,/toStage==='Closed Lost'/);
 assert.equal(validateOpportunityTransition('Negotiation','Closed Lost',{reasonCode:'customer_withdrew',reason:'Customer confirmed withdrawal'}).value.toStage,'Closed Lost');
 assert.match(validateOpportunityTransition('Negotiation','Closed Lost',{reasonCode:'customer_withdrew'}).error,/reason/);
});
test('OPP-STAGE-ACTION-VALUE-32 keeps friendly UI labels mapped to canonical stage values',()=>{const ui=read('public/app.js');assert.match(ui,/stageActionLabels=\{'Requirements':'Return to Requirements','Matching':'Return to Matching','Closed Lost':'Close Opportunity as Lost'\}/);assert.match(ui,/option\.textContent=stageActionLabels\[option\.value\]\|\|option\.value/);for(const stage of ['Requirements','Matching','Closed Lost'])assert.ok(ui.includes(`'${stage}'`));});
test('LEAD-CURRENT-STATUS-23 keeps present pursuit status distinct from historical Lead stage and temperature',()=>{
 const sql=read('src/migrations/061_dev90_reference_and_status_governance.sql'),r=read('src/routes/opportunities.js');
 assert.match(sql,/nysa_sync_lead_current_status/);assert.match(sql,/AFTER INSERT OR UPDATE OF stage/);assert.match(r,/current_status='closed_lost'/);
});
test('OPP-CLOSE-STATUS-23A/B/C/D synchronizes authoritative Opportunity and Deal terminal outcomes',()=>{const r=read('src/routes/opportunities.js'),sql=read('src/migrations/061_dev90_reference_and_status_governance.sql');assert.match(r,/stage='Closed Won'/);assert.match(r,/stage='Closed Lost'/);assert.match(r,/d\.status IN \('closed_won','closed_lost'\)/);assert.match(sql,/o\.stage='Closed Won'/);assert.match(sql,/o\.stage='Closed Lost'/);});
test('UI-FLOW-SYNC-24, LEAD-FLOW-SYNC-24, DEAL-COUNT-25 and LEAD-DEAL-COUNT-25 share governed counts and current/closed semantics',()=>{const crm=read('src/routes/crm.js'),opp=read('src/routes/opportunities.js'),ui=read('public/dashboard-ui.js');assert.match(crm,/AS deal_count/);assert.match(crm,/AS closed_deal_count/);assert.doesNotMatch(crm,/Deal',status:'not_available'/);assert.match(opp,/AS active_deals/);assert.match(opp,/AS closed_deals/);assert.match(opp,/count:opportunityCounts\.deals/);assert.match(ui,/data-guided-step/);});
test('LEAD-FLOW-ORDER-26 permits requirements before or in parallel with assessment but requires confirmation before Opportunity readiness',()=>{const crm=read('src/routes/crm.js'),opp=read('src/routes/opportunities.js'),dash=read('src/routes/dashboards.js');assert.match(crm,/assessment is not a prerequisite for recording them/);assert.match(crm,/lead\.assignedTo&&requirementConfirmed&&qualification/);assert.match(crm,/requires broker confirmation before matching/);assert.match(opp,/requirements may be recorded before or in parallel/);assert.match(dash,/requirements:'EXISTS\(SELECT 1 FROM lead_requirements/);});
test('Viewing feedback branching hides repeat confirmation after positive selection and permits governed alternative branches',()=>{const ui=read('public/app.js');assert.match(ui,/\['selected_property','positive'\]\.includes\(v\.outcome\)/);assert.match(ui,/Positive viewing feedback recorded/);for(const value of ['maybe','not_interested','more_options'])assert.ok(ui.includes(`value="${value}"`));const valid=validateViewingOutcome({status:'completed',outcome:'more_options',feedback:'Show alternatives',followUpAction:'Schedule another viewing',followUpDueAt:'2026-08-02T10:00:00Z',expectedVersion:1,attendance:[]});assert.equal(valid.value.outcome,'more_options');});
test('Inventory owner inheritance prefills transaction parties while retaining original attribution',()=>{const r=read('src/routes/opportunities.js');assert.match(r,/async function inheritInventoryOwner/);assert.match(r,/inventory_counterparty_id/);assert.match(r,/seller_counterparty_id/);assert.match(r,/buildOpportunityAttribution/);assert.match(r,/provenance_hash/);});
test('Migration files rely on the runner for schema_migrations registration',()=>{assert.doesNotMatch(read('src/migrations/060_consolidated_lead_opportunity_remediation.sql'),/INSERT INTO schema_migrations/);assert.doesNotMatch(read('src/migrations/061_dev90_reference_and_status_governance.sql'),/INSERT INTO schema_migrations/);});
test('dev.93 R2 clone deployment is checksum-bound, idempotent, migration-61-aware, PID-race-safe and environment-isolated',()=>{const sh=read('release-artifacts/release-2/r2.6/deploy-r2-clone-dev93-complete.sh');for(const marker of ['EXPECTED_VERSION=2.1.0-dev.93','nysa-core-r2-6-cumulative-dev93.zip','Package checksum verified','Deployment already confirmed','R2 health check failed before deployment','load_stable_database_environment','Recovering interrupted deployment: files are $before_version while live worker serves $served_version','partial_install_recovery','tr -d','pg_dump','pre-dev93-app.tar.gz','before_migration" == "61|$LATEST_MIGRATION','"$PRIOR_MIGRATION" "$LATEST_MIGRATION"','EXPECTED_ROOT=/home/nysareal/nysa-r2-prod-clone','PRODUCTION_ROOT=/home/nysareal/nysa-crm','CRM_TEST_ROOT=/home/nysareal/nysa-core-dashboard-dd6262a-stage','Previously discovered R2 clone PID $pid already exited; continuing safely','verified_old_pids','npm','one new worker','Latest migration: $LATEST_MIGRATION','Production and CRM Test snapshots: unchanged','trap finish EXIT'])assert.ok(sh.includes(marker),`missing deployment control: ${marker}`);assert.doesNotMatch(sh,/<\(|>\(|\/dev\/fd/);});
test('UI-LEAD-PROPERTY-SUMMARY-38 shows governed property location and amount in the Lead register',()=>{const ui=read('public/app.js'),crm=read('src/routes/crm.js');assert.match(ui,/Property:.*activeOpportunityListingArea.*listingArea/);assert.match(ui,/activeOpportunityListingPrice\|\|l\.listingPrice/);assert.match(ui,/Amount not recorded/);assert.match(crm,/active_opportunity_listing_area/);assert.match(crm,/opportunity_listing\.price AS listing_price/);});
test('UI-QUALIFICATION-FLOW-SYNC-39 refreshes governed Lead readiness after assessment or override',()=>{const ui=read('public/app.js');assert.match(ui,/nysa:qualification-saved/);assert.match(ui,/qualificationMatch\[1\]/);assert.match(ui,/event\.detail\?\.leadId!==id/);assert.match(ui,/openLead\(id,\{afterStageChange\}\)/);});
test('OPP-INVENTORY-SELECTOR-40 retains the first operationally usable Inventory in Opportunity creation',()=>{const ui=read('public/app.js');assert.match(ui,/status=Available&pageSize=100/);assert.doesNotMatch(ui,/startingInventory\.options\[0\]\?\.remove\(\)/);assert.match(ui,/No operationally usable Inventory is available/);});
test('UI-THEME-33 centralizes a readable premium light workspace palette',()=>{const css=read('public/index.html');for(const token of ['--workspace:','--surface:','--charcoal:','--ink:','--gold-strong:','--focus-ring:','--shadow-sm:','--shadow-lg:'])assert.ok(css.includes(token),`missing theme token ${token}`);assert.match(css,/background:linear-gradient\(110deg,#0a2233,#173646 62%,#193f39\)/);assert.match(css,/--bg:var\(--workspace\)/);assert.match(css,/\.modal\{[^}]*border-top:3px solid var\(--gold\)/);});
test('INV-OPTIONAL-DATE-CLEAR-34 makes every optional Inventory and agreement date explicitly removable',()=>{const ui=read('public/app.js'),routes=read('src/routes/listings.js');for(const name of ['availabilityConfirmedAt','verificationExpiresAt','permitExpiresAt','agreementEffectiveFrom','agreementEffectiveTo','effectiveFrom','effectiveTo'])assert.ok(ui.includes(`'${name}'`),`missing clearable optional date ${name}`);assert.match(ui,/function installOptionalDateClearControls/);assert.match(ui,/button\.dataset\.clearOptionalDate=name/);assert.match(ui,/input\.value=''/);assert.match(ui,/if \(f\[k\] === ''\) f\[k\] = null/);assert.match(routes,/b\.effectiveFrom\|\|null,b\.effectiveTo\|\|null/);assert.match(routes,/verificationExpiresAt:'verification_expires_at'/);});
test('UI-BRAND-LOGO-41 uses the approved production variants for login, shell and favicons',()=>{const ui=read('public/app.js'),page=read('public/index.html');assert.match(ui,/class="auth-logo" src="\/brand\/nysa\/vector\/nysa-stacked-dark\.svg\?v=20260815-dev146"/);assert.match(ui,/class="brand-logo brand-logo-horizontal" src="\/brand\/nysa\/vector\/nysa-horizontal-dark\.svg\?v=20260815-dev146"/);assert.match(ui,/class="brand-logo brand-logo-mark" src="\/brand\/nysa\/vector\/nysa-app-icon\.svg\?v=20260815-dev146"/);assert.doesNotMatch(ui,/class="brand-logo"[^>]*nysa-uae-badge/);for(const size of [16,32,48])assert.match(page,new RegExp(`<link rel="icon" type="image/png" sizes="${size}x${size}" href="/brand/nysa/raster/favicon-${size}\\.png\\?v=20260815-dev146">`));assert.match(page,/\.brand-logo-horizontal\{[^}]*min-width:140px;[^}]*height:44px/);});
test('INV-OWNER-CUSTOMER-LINK-35 keeps Inventory parties separate from Customer Master',()=>{const ui=read('public/app.js'),routes=read('src/routes/listings.js');assert.match(ui,/Saving here maintains the party on Internal Inventory; it does not create a Customer or publish an external Listing/);assert.match(routes,/validateInventoryPartyInput/);assert.match(routes,/INSERT INTO inventory_counterparties/);assert.doesNotMatch(routes,/created_from_inventory_owner/);});
test('INV-OWNER-KYC-ROUTING-36 preserves Customer KYC authority without forcing Inventory owners into Customers',()=>{const ui=read('public/app.js'),crm=read('src/routes/crm.js'),routes=read('src/routes/listings.js');assert.match(ui,/hasCrmAccess\(\) \? '<button data-tab="customers">Customers<\/button>'/);assert.doesNotMatch(ui,/hasCrmAccess\(\)&&ME\.jobRole!=='listing_agent' \? '<button data-tab="customers">Customers<\/button>'/);assert.match(crm,/customer\.ownerId===req\.broker\.id\|\|customer\.createdBy===req\.broker\.id/);assert.match(crm,/contact\.ownerId===req\.broker\.id\|\|contact\.createdBy===req\.broker\.id/);assert.match(routes,/inventory_counterparties/);});
