import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {unzipSync} from 'fflate';

const artifact=name=>new URL(`../release-artifacts/release-3/consolidated/${name}`,import.meta.url),sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');

test('dev199 is a checksum-bound migration-neutral CRM-Test delta from deployed dev198',()=>{const name='nysa-core-consolidated-crm-test-dev199-r1.zip',bytes=fs.readFileSync(artifact(name)),manifest=JSON.parse(fs.readFileSync(artifact(name.replace('.zip','.manifest.json')),'utf8')),checksum=fs.readFileSync(artifact(name.replace('.zip','.sha256.txt')),'utf8').trim();assert.equal(checksum,`${sha(bytes)}  ${name}`);assert.equal(manifest.packageSha256,sha(bytes));assert.equal(manifest.version,'2.1.0-dev.199');assert.equal(manifest.sourceBaselinePackageSha256,'e1fba528650bc35ef20694eb6fc4db1ca2f57d05b3e66faa40b8fcfa9c839f5c');assert.equal(manifest.migrationNeutral,true);assert.deepEqual(manifest.newMigrations,[]);assert.equal(manifest.latestMigration,'126_executing_agent_tier_and_social_uplift.sql');});

test('dev199 package changes only the approved payout-disclosure runtime files',()=>{const current=unzipSync(fs.readFileSync(artifact('nysa-core-consolidated-crm-test-dev199-r1.zip'))),baseline=unzipSync(fs.readFileSync(artifact('nysa-core-consolidated-crm-test-dev198-r1.zip'))),expected=['package-lock.json','package.json','public/commission-payout-ui.js','src/commission-payout-sheet-pdf.js','src/routes/commission-payout.js'],runtime=name=>['app.cjs','.env.example','package.json','package-lock.json'].includes(name)||name.startsWith('src/')||name.startsWith('public/'),changed=Object.keys(current).filter(name=>runtime(name)&&!name.endsWith('/')&&(!baseline[name]||sha(current[name])!==sha(baseline[name]))).sort();assert.deepEqual(changed,expected);for(const [name,bytes] of Object.entries(baseline))if(name.startsWith('src/migrations/'))assert.equal(sha(current[name]),sha(bytes),name);assert.equal(JSON.parse(Buffer.from(current['package.json'])).version,'2.1.0-dev.199');});

test('dev199 deployer is dev198 baseline-bound, backup-first and preserves migration 126',()=>{const deployer=fs.readFileSync(artifact('deploy-crm-test-consolidated-dev199-r1.sh'),'utf8'),manifest=JSON.parse(fs.readFileSync(artifact('nysa-core-consolidated-crm-test-dev199-r1.manifest.json'),'utf8'));assert.match(deployer,/EXPECTED_VERSION=2\.1\.0-dev\.199/);assert.match(deployer,/PREVIOUS_VERSION=2\.1\.0-dev\.198/);assert.ok(deployer.includes(`APPROVED_SHA256=${manifest.packageSha256}`));assert.match(deployer,/LATEST_MIGRATION=126_executing_agent_tier_and_social_uplift\.sql/);assert.match(deployer,/pg_dump[\s\S]*pre-dev199\.dump[\s\S]*tar -czf/);assert.match(deployer,/Production and R2 clone snapshots: unchanged/);assert.doesNotMatch(deployer,/\r/);});
