import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stableHash,validateEmailDraft,validateEmailSend,transitionEmailState,emailAttemptFingerprint,validateMicrosoftNotification,rotateRefreshToken,validateCalendlyHostMapping,validateCalendlyEventTypeMapping,validateSchedulingIntent,validateCalendlyEvent,calendlyEventKey,planCalendlyProjection,evaluateViewingConfirmation} from '../src/email-calendly-domain.js';
import {createDisabledMicrosoft365Connector,createLocalMicrosoft365Connector} from '../src/microsoft365-email-connector.js';
import {createDisabledCalendlyConnector,createLocalCalendlyConnector} from '../src/calendly-connector.js';
const read=file=>readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),hash=stableHash({authority:'synthetic'});

test('stable hash canonicalizes nested object keys',()=>assert.equal(stableHash({b:{y:2,x:1},a:0}),stableHash({a:0,b:{x:1,y:2}})));
test('Email draft rejects every arbitrary recipient field',()=>assert.match(validateEmailDraft({recipientEmail:'outside@example.invalid'}).error,/server-derived/));
test('Email draft accepts controlled purpose and exact authority',()=>assert.equal(validateEmailDraft({leadId:'l',contactId:'c',mailboxConnectionId:'m',purpose:'meeting_coordination',subject:'Synthetic meeting',body:'Synthetic body',contactAuthorityHash:hash}).value.policyVersion,'r3d-microsoft365-email-v1'));
test('Email send requires exact confirmation and idempotency',()=>{assert.match(validateEmailSend({draftVersion:1,idempotencyKey:'one',confirmation:'YES'}).error,/confirmation/);assert.equal(validateEmailSend({draftVersion:1,idempotencyKey:'one',confirmation:'SEND_EMAIL'}).value.draftVersion,1);});
test('Email state machine allows queue and rejects unsafe skip',()=>{assert.equal(transitionEmailState('confirmed','queue').value.to,'queued');assert.match(transitionEmailState('draft','claim').error,/cannot follow/);});
test('Email attempt fingerprint is deterministic',()=>assert.equal(emailAttemptFingerprint({threadId:'t',draftVersion:1,contactAuthorityHash:hash,payloadDigest:hash,idempotencyKey:'i'}),emailAttemptFingerprint({idempotencyKey:'i',payloadDigest:hash,contactAuthorityHash:hash,draftVersion:1,threadId:'t'})));
test('Microsoft notification requires exact client state digest',()=>{const value={subscriptionRef:'s',resourceRef:'r',eventRef:'e',clientStateDigest:hash,receivedAt:'2026-08-14T00:00:00Z'};assert.ok(validateMicrosoftNotification(value,hash).value);assert.match(validateMicrosoftNotification(value,stableHash('other')).error,/invalid/);});
test('refresh-token rotation advances once',()=>assert.deepEqual(rotateRefreshToken({currentGeneration:4,nextEncryptedReference:'private-ref'}).value,{priorGeneration:4,nextGeneration:5,nextEncryptedReference:'private-ref'}));
test('Calendly host mapping requires a reason',()=>assert.match(validateCalendlyHostMapping({calendlyUserRef:'u',brokerId:'b',reason:'no'}).error,/meaningful/));
test('property viewing mapping must be physical',()=>assert.match(validateCalendlyEventTypeMapping({eventTypeRef:'e',kind:'property_viewing',durationMinutes:45,locationMode:'virtual',reason:'Approved mapping'}).error,/physical/));
test('scheduling intent uses Lead authority hash rather than invented version',()=>{const result=validateSchedulingIntent({kind:'customer_meeting',leadId:'l',contactId:'c',brokerId:'b',eventTypeMappingId:'e',eventTypeMappingVersion:1,leadAuthorityHash:hash,authorityHash:hash});assert.equal(result.value.leadAuthorityHash,hash);});
test('property viewing intent requires exact Opportunity and Match versions',()=>assert.match(validateSchedulingIntent({kind:'property_viewing',leadId:'l',contactId:'c',brokerId:'b',eventTypeMappingId:'e',eventTypeMappingVersion:1,leadAuthorityHash:hash,authorityHash:hash}).error,/Property Match versions/));
test('Calendly event requires signed non-replayed evidence',()=>{const value={eventFamily:'invitee.created',providerEventRef:'p',eventRef:'e',inviteeRef:'i',occurredAt:'2026-08-14T00:00:00Z',receivedAt:'2026-08-14T00:00:01Z',payloadDigest:hash,signatureVerified:true,replayDetected:false};assert.ok(validateCalendlyEvent(value).value);assert.match(validateCalendlyEvent({...value,replayDetected:true}).error,/signature/);});
test('Calendly event key distinguishes cancellation history',()=>assert.notEqual(calendlyEventKey({eventFamily:'invitee.created',eventRef:'e',inviteeRef:'i'}),calendlyEventKey({eventFamily:'invitee.canceled',eventRef:'e',inviteeRef:'i'})));
test('meeting projects Activity while viewing projects confirmation task',()=>{assert.equal(planCalendlyProjection({kind:'customer_meeting',correlated:true,hostMapped:true,eventTypeMapped:true}).value.projection,'meeting_activity');assert.equal(planCalendlyProjection({kind:'property_viewing',correlated:true,hostMapped:true,eventTypeMapped:true}).value.projection,'broker_confirmation_task');});
test('viewing confirmation fails closed on stale Inventory',()=>{const result=evaluateViewingConfirmation({assignedBrokerConfirmed:true,actorAuthorized:true,intentCurrent:true,opportunityCurrent:true,propertyMatchCurrent:true,inventoryEligible:false,duplicateViewing:false});assert.equal(result.value.allowed,false);assert.deepEqual(result.value.blockers,['inventory_not_eligible']);});
test('viewing confirmation passes only complete revalidation',()=>assert.equal(evaluateViewingConfirmation({assignedBrokerConfirmed:true,actorAuthorized:true,intentCurrent:true,opportunityCurrent:true,propertyMatchCurrent:true,inventoryEligible:true,duplicateViewing:false}).value.allowed,true));
test('disabled connectors perform no network work',async()=>{assert.equal((await createDisabledMicrosoft365Connector().dispatch()).reasonCode,'connector_disabled');assert.equal((await createDisabledCalendlyConnector().createSchedulingLink()).reasonCode,'connector_disabled');});
test('local Email connector is idempotent and offline',async()=>{const connector=createLocalMicrosoft365Connector(),input={fingerprint:'f'},first=await connector.dispatch(input),second=await connector.dispatch(input);assert.equal(connector.networkEnabled,false);assert.equal(first.providerMessageRef,second.providerMessageRef);assert.equal(second.replayed,true);});
test('local Calendly connector retains cancellation as separate event',async()=>{const connector=createLocalCalendlyConnector(),link=await connector.createSchedulingLink({eventTypeRef:'e',correlationRef:'c'}),event=connector.emitBooking({correlationRef:'c',eventTypeRef:'e',hostRef:'h',startsAt:'2026-08-14T10:00:00Z',endsAt:'2026-08-14T10:45:00Z'}),cancel=connector.emitCancellation(event.eventRef);assert.equal(connector.networkEnabled,false);assert.match(link.schedulingUrl,/127\.0\.0\.1/);assert.equal(cancel.eventFamily,'invitee.canceled');assert.notEqual(cancel.providerEventRef,event.providerEventRef);});

test('migrations 093 and 094 are additive and runner-managed',()=>{const email=read('src/migrations/093_release3d_microsoft365_email.sql'),calendly=read('src/migrations/094_release3d_calendly_scheduling.sql');for(const marker of ['email_message_evidence','email_message_state_events','email_provider_events','email_provider_event_processing','microsoft365_one_active_mailbox_per_broker_idx'])assert.match(email,new RegExp(marker));for(const marker of ['calendly_scheduling_intents','lead_authority_hash','calendly_provider_events','calendly_provider_event_processing','calendly_bookings','calendly_projection_events'])assert.match(calendly,new RegExp(marker));assert.doesNotMatch(email+calendly,/ALTER TABLE (leads|contacts|opportunities|listings)/i);assert.doesNotMatch(email+calendly,/INSERT INTO schema_migrations/i);assert.match(email+calendly,/nysareal_nysar2app/);assert.doesNotMatch(email+calendly,/\bTO nysa_app\b/);});

test('all consolidated candidate migrations rely on the transaction runner for registration',()=>{for(let number=83;number<=94;number++){const prefix=String(number).padStart(3,'0')+'_',file=Object.keys(import.meta.resolve?{}:{});const migration=['083_inventory_duplicate_prevention.sql','084_partner_organization_integration.sql','085_release3c_governed_share_response.sql','086_release4_official_document_evidence.sql','087_release4_dld_market_intelligence.sql','088_release5_commission_receipt_realtime_payout.sql','089_agent_employment_leave.sql','090_release6_customer_transaction_document_compliance.sql','091_release6_marketing_material_compliance.sql','092_release3b_matching_completion.sql','093_release3d_microsoft365_email.sql','094_release3d_calendly_scheduling.sql'].find(name=>name.startsWith(prefix));assert.doesNotMatch(read(`src/migrations/${migration}`),/INSERT INTO schema_migrations/i,migration);}});
test('routes fail closed and separate public webhook receipt from authenticated controls',()=>{const route=read('src/routes/email-calendly.js');for(const marker of ['/webhooks/microsoft-graph/mail','/webhooks/calendly','r.use(requireAuth)','own_mailbox_only','validateEmailSend','signature is invalid','pending_broker_confirmation'])assert.match(route,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(route,/MICROSOFT365_EMAIL_ENABLED/);assert.match(route,/CALENDLY_ENABLED/);});
test('staff UI has no arbitrary recipient field and exposes approved actions',()=>{const app=read('public/app.js'),ui=read('public/email-calendly-ui.js'),bootstrap=read('public/bootstrap.js');assert.match(app,/Email from CORE/);assert.match(app,/Schedule with Calendly/);assert.match(ui,/no editable To, CC or BCC field/i);assert.doesNotMatch(ui,/name="recipient|name="to|name="cc|name="bcc/i);assert.match(bootstrap,/email-calendly-ui\.js/);});
test('environment template contains names only and connectors are disabled by default',()=>{const env=read('.env.example');for(const marker of ['MICROSOFT365_EMAIL_ENABLED=0','CALENDLY_ENABLED=0','MICROSOFT365_WEBHOOK_CLIENT_STATE_SECRET=','CALENDLY_WEBHOOK_SIGNING_KEY=','INTEGRATION_SERVICE_ACTOR_ID='])assert.match(env,new RegExp(marker));});
test('local Gate 3 review is loopback-only GET-only synthetic and blocks network',()=>{const server=read('tools/email-calendly-local/server.js'),html=read('tools/email-calendly-local/index.html'),app=read('tools/email-calendly-local/app.js');assert.match(server,/listen\(port,'127\.0\.0\.1'/);assert.match(server,/req\.method!=='GET'/);assert.match(server,/connect-src 'none'/);assert.match(html,/synthetic records only/i);assert.match(html,/My Task Queue/);assert.match(app,/stale\/unavailable Inventory|Live Inventory is no longer eligible/i);});
test('Property Finder is excluded from Email and Calendly implementation files',()=>{const files=['src/email-calendly-domain.js','src/microsoft365-email-connector.js','src/calendly-connector.js','src/routes/email-calendly.js','public/email-calendly-ui.js','src/migrations/093_release3d_microsoft365_email.sql','src/migrations/094_release3d_calendly_scheduling.sql'];for(const file of files)assert.doesNotMatch(read(file),/property[ _-]?finder/i,file);});
