import test from'node:test';import assert from'node:assert/strict';import{buildExternalPortalReconciliation}from'../src/external-portal-reconciliation-domain.js';
const at='2026-08-11T12:00:00.000Z',payload={reference:'INV-1',price:1950000,status:'available'},base={inventoryRef:'NYSA-INV-1',lifecycleStatus:'active',publicationReady:true,mappingVersion:'pf-map-v1',payload,sourceVersion:'INV-V7'};
const run=(internal,external)=>buildExternalPortalReconciliation({internal,external,evaluatedAt:at});
test('ready unlinked Inventory produces create proposal without executing it',async()=>{const result=await run(base,{providerCode:'property_finder',status:'not_discovered',mappingVersion:'pf-map-v1',payload:{}});assert.equal(result.action,'propose_create');assert.equal(result.externalWritePerformed,false);assert.equal(result.publicationPerformed,false);assert.equal(result.automaticExecutionAllowed,false);});
test('linked aligned live listing requires no action',async()=>{const result=await run(base,{providerCode:'property_finder',externalListingId:'PF-1',linkedInventoryRef:'NYSA-INV-1',status:'live',mappingVersion:'pf-map-v1',payload,observedAt:at});assert.equal(result.action,'no_action');assert.equal(result.payloadAligned,true);assert.equal(result.existingWorkItemRequest,null);});
test('linked drift creates reviewed update proposal without overwrite',async()=>{const result=await run(base,{providerCode:'property_finder',externalListingId:'PF-1',linkedInventoryRef:'NYSA-INV-1',status:'live',mappingVersion:'pf-map-v1',payload:{...payload,price:1900000},observedAt:at});assert.equal(result.action,'propose_reviewed_update');assert.equal(result.internalInventoryChanged,false);assert.equal(result.existingWorkItemRequest.separateQueueCreated,false);});
test('ineligible Internal Inventory proposes unpublish review but does not unpublish',async()=>{const result=await run({...base,publicationReady:false},{providerCode:'property_finder',externalListingId:'PF-1',linkedInventoryRef:'NYSA-INV-1',status:'live',mappingVersion:'pf-map-v1',payload,observedAt:at});assert.equal(result.action,'propose_unpublish_review');assert.equal(result.unpublicationPerformed,false);});
test('unlinked external listing requires manual matching',async()=>{const result=await run(base,{providerCode:'property_finder',externalListingId:'PF-9',linkedInventoryRef:null,status:'live',mappingVersion:'pf-map-v1',payload,observedAt:at});assert.equal(result.action,'manual_match_required');assert.equal(result.deletionPerformed,false);});
test('external deletion records evidence and never deletes Internal Inventory',async()=>{const result=await run(base,{providerCode:'property_finder',externalListingId:'PF-1',linkedInventoryRef:'NYSA-INV-1',status:'deleted',mappingVersion:'pf-map-v1',payload,observedAt:at});assert.equal(result.action,'record_external_absence');assert.equal(result.internalInventoryChanged,false);assert.match(result.evidenceHash,/^[a-f0-9]{64}$/);});
