import test from 'node:test';
import assert from 'node:assert/strict';
import { governedDocumentCatalog, prepareGovernedDocumentAssembly, GOVERNED_DOCUMENT_CATALOG_VERSION } from '../src/governed-document-assembly-domain.js';
const now='2026-08-08T10:00:00.000Z',hash=value=>value.repeat(64),snap=(ref,facts,marker='a')=>({ref,version:'v1',hash:hash(marker),asOf:now,facts});
const sources={organization:snap('ORG',{legalName:'Synthetic NYSA',licenceReference:'LIC-SYN'},'1'),agent:snap('AGENT',{brokerReference:'BROKER-SYN'},'2'),seller_authority:snap('SELLER',{partyReference:'SELLER-SYN',authorityEvidenceReference:'AUTH-SYN'},'3'),inventory:snap('INV',{inventoryReference:'INV-SYN',propertyDescription:'Synthetic apartment',askingPrice:'AED 1,950,000',titleEvidenceReference:'TITLE-SYN'},'4'),commercial_terms:snap('TERMS',{mandateType:'Exclusive',commissionTerms:'Synthetic terms'},'5'),customer:snap('CUSTOMER',{customerReference:'CUSTOMER-SYN',displayName:'Synthetic Customer',identityStatus:'Verified'},'6'),requirement:snap('REQ',{requirementReference:'REQ-SYN',purchaseObjective:'Residence',budget:'AED 2m'},'7'),accepted_offer:snap('OFFER',{amount:'AED 1.9m',revisionReference:'OFFER-R2'},'8'),booking:snap('BOOKING',{bookingReference:'BOOKING-SYN',status:'Confirmed'},'9'),deal_terms:snap('DEAL',{targetCompletion:'2026-10-15',additionalTerms:'Synthetic terms'},'b'),consent_terms:snap('CONSENT',{scope:'Property updates',channels:'Email',effectiveDate:'2026-08-08',expiryDate:'2027-02-08'},'c'),developer:snap('DEV',{developerReference:'DEV-SYN'},'d'),transfer_context:snap('TRANSFER',{transferReference:'TRANSFER-SYN'},'e')};
const templateProfile={id:'TEMPLATE-SYN',version:'1',hash:hash('f'),status:'approved'};

test('catalogue separates official preparation, CORE generation, external capture and unresolved definition',()=>{const byCode=Object.fromEntries(governedDocumentCatalog().map(item=>[item.code,item]));assert.equal(byCode.dld_contract_a.mode,'official_system_preparation');assert.equal(byCode.dld_contract_b.mode,'official_system_preparation');assert.equal(byCode.dld_contract_f.mode,'official_system_preparation');assert.equal(byCode.nysa_marketing_consent.mode,'core_generated');assert.equal(byCode.developer_e_noc.mode,'external_evidence_capture');assert.equal(byCode.listing_noc.mode,'definition_required');});
test('Contract A creates only an immutable official preparation packet',async()=>{const result=await prepareGovernedDocumentAssembly({documentType:'dld_contract_a',sources,now});assert.equal(result.catalogVersion,GOVERNED_DOCUMENT_CATALOG_VERSION);assert.equal(result.status,'official_preparation_ready');assert.equal(result.output.kind,'preparation_packet');assert.equal(result.output.officialContractGenerated,false);assert.match(result.manifestHash,/^[a-f0-9]{64}$/);});
test('missing source facts fail closed before a manifest exists',async()=>{const incomplete={...sources};delete incomplete.inventory;const result=await prepareGovernedDocumentAssembly({documentType:'dld_contract_a',sources:incomplete,now});assert.equal(result.status,'source_validation_blocked');assert.equal(result.manifest,null);assert.equal(result.manifestHash,null);assert.ok(result.missing.some(item=>item.code==='source_inventory'));});
test('NYSA marketing agreement requires approved template evidence and creates preview only',async()=>{const blocked=await prepareGovernedDocumentAssembly({documentType:'nysa_marketing_consent',sources,templateProfile:{...templateProfile,status:'draft'},now});assert.equal(blocked.status,'source_validation_blocked');const ready=await prepareGovernedDocumentAssembly({documentType:'nysa_marketing_consent',sources,templateProfile,now});assert.equal(ready.status,'core_generation_preview_ready');assert.equal(ready.output.documentGenerated,false);assert.equal(ready.manifest.templateProfile.hash,templateProfile.hash);});
test('developer e-NOC stays external evidence pending until issuer evidence is captured',async()=>{const pending=await prepareGovernedDocumentAssembly({documentType:'developer_e_noc',sources,now});assert.equal(pending.status,'external_evidence_pending');assert.equal(pending.output.issuerDocumentGenerated,false);const externalEvidence={evidenceReference:'ENOC-SYN',issuerReference:'DEV-SYN',documentHash:hash('9'),issuedAt:'2026-08-08T09:00:00.000Z',sourceInventoryVersion:'v1'};const captured=await prepareGovernedDocumentAssembly({documentType:'developer_e_noc',sources,externalEvidence,now});assert.equal(captured.status,'external_evidence_captured');assert.equal(captured.output.issuerDocumentGenerated,false);});
test('Listing NOC remains disabled until the owner defines its meaning',async()=>{const result=await prepareGovernedDocumentAssembly({documentType:'listing_noc',sources,now});assert.equal(result.status,'definition_required');assert.equal(result.manifest,null);});
test('source version or value change produces a different immutable manifest hash',async()=>{const first=await prepareGovernedDocumentAssembly({documentType:'dld_contract_b',sources,now});const changed={...sources,requirement:{...sources.requirement,version:'v2',facts:{...sources.requirement.facts,budget:'AED 2.1m'}}};const second=await prepareGovernedDocumentAssembly({documentType:'dld_contract_b',sources:changed,now});assert.notEqual(first.manifestHash,second.manifestHash);});
