import test from 'node:test';
import assert from 'node:assert/strict';
import { buildInventoryDuplicateCandidate, recordInventoryDuplicateDecision, recordInventoryReopenDecision } from '../src/inventory-duplicate-review-domain.js';

const at='2026-08-11T08:00:00.000Z';
const base={lifecycleStatus:'active',areaId:'AREA-DUBAI',communityId:'COMM-MARINA',community:'Dubai Marina',unitReference:'UNIT-MH-A-1204',project:'Marina Heights',building:'Tower A',unitNumber:'1204',propertyType:'Apartment',bedrooms:2,sizeSqft:1210};
const left={...base,inventoryRef:'NYSA-INV-001',propertyReference:'DLD-PROP-77',sourceIdentities:[{provider:'inventory_excel',externalRecordId:'ROW-77'}]};
const right={...base,inventoryRef:'NYSA-INV-002',propertyReference:'DLD-PROP-77',sourceIdentities:[{provider:'property_finder',externalRecordId:'PF-88'}]};

test('matching active inventory stops duplicate maintenance',()=>{const candidate=buildInventoryDuplicateCandidate({left,right,evaluatedAt:at});assert.equal(candidate.classification,'exact_identity_match');assert.equal(candidate.score,100);assert.equal(candidate.evidence.some(item=>item.code==='same_governed_inventory_identity'),true);assert.equal(candidate.reviewRequired,false);assert.equal(candidate.maintenanceGate.outcome,'block_active_duplicate');assert.equal(candidate.maintenanceGate.inventoryCreateAllowed,false);assert.equal(candidate.maintenanceGate.governedIdentityUpdateAllowed,false);assert.equal(candidate.maintenanceGate.existingInventoryRef,left.inventoryRef);assert.equal(candidate.maintenanceGate.managerApprovalRequired,false);assert.equal(candidate.existingWorkItemRequest,null);assert.equal(candidate.automaticMergeAllowed,false);assert.equal(candidate.inventoryMutationPerformed,false);});
test('Unit Reference and Unit Number are accepted as the same identity field',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,unitNumber:null},right:{...right,unitNumber:null},evaluatedAt:at});assert.equal(candidate.classification,'exact_identity_match');assert.equal(candidate.maintenanceGate.outcome,'block_active_duplicate');});
test('a different maintained size cannot produce an automatic duplicate block',()=>{const candidate=buildInventoryDuplicateCandidate({left,right:{...right,sizeSqft:1211},evaluatedAt:at});assert.notEqual(candidate.classification,'exact_identity_match');assert.equal(candidate.maintenanceGate.outcome,'hold_intake_for_duplicate_review');assert.equal(candidate.conflicts.some(item=>item.code==='different_size_sqft'),true);});
test('a missing Building cannot produce an automatic duplicate block',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,building:null},right:{...right,building:null},evaluatedAt:at});assert.notEqual(candidate.classification,'exact_identity_match');assert.equal(candidate.maintenanceGate.outcome,'hold_intake_for_duplicate_review');});
test('matching closed inventory requires immutable manager approval to reopen the same record',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,lifecycleStatus:'closed'},right,evaluatedAt:at});assert.equal(candidate.maintenanceGate.outcome,'require_manager_reopen_approval');assert.equal(candidate.maintenanceGate.inventoryCreateAllowed,false);assert.equal(candidate.maintenanceGate.existingInventoryEditable,false);assert.equal(candidate.maintenanceGate.managerApprovalRequired,true);const approval=recordInventoryReopenDecision({candidate,decision:'approve_reopen',reason:'Manager confirmed that this closed Inventory may be reopened.',managerRef:'MANAGER-1',decidedAt:at});assert.equal(approval.inventoryRef,left.inventoryRef);assert.equal(approval.resultingStatus,'active');assert.equal(approval.editAllowedAfterApproval,true);assert.equal(approval.newInventoryCreated,false);assert.equal(approval.statusMutationPerformed,false);assert.equal(approval.immutable,true);assert.match(approval.approvalHash,/^[a-f0-9]{64}$/);});
test('same provider record cannot override a conflicting unit number',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,propertyReference:null},right:{...right,propertyReference:null,sourceIdentities:[{provider:'inventory_excel',externalRecordId:'ROW-77'}],unitNumber:'1301'},evaluatedAt:at});assert.equal(candidate.evidence.some(item=>item.code==='same_external_source_identity'),true);assert.equal(candidate.conflicts.some(item=>item.code==='different_unit_number'),true);assert.notEqual(candidate.classification,'exact_identity_match');assert.ok(candidate.score<100);assert.equal(candidate.maintenanceGate.outcome,'hold_intake_for_duplicate_review');assert.equal(candidate.maintenanceGate.inventoryCreateAllowed,false);});
test('project building and unit hold intake for human review when Community is unavailable',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,communityId:null,community:null,propertyReference:null,sourceIdentities:[]},right:{...right,communityId:null,community:null,propertyReference:null,sourceIdentities:[],sizeSqft:1225},evaluatedAt:at});assert.equal(candidate.classification,'strong_duplicate_candidate');assert.equal(candidate.reviewRequired,true);assert.equal(candidate.maintenanceGate.outcome,'hold_intake_for_duplicate_review');assert.equal(candidate.maintenanceGate.inventoryCreateAllowed,false);});
test('similar properties with different Community and Unit Number allow maintenance',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,propertyReference:null,sourceIdentities:[]},right:{...right,propertyReference:null,sourceIdentities:[],communityId:'COMM-JLT',unitReference:'UNIT-JLT-1802',unitNumber:'1802',project:'Other Project',building:'Other Tower',sizeSqft:1215},evaluatedAt:at});assert.equal(candidate.classification,'unlikely_duplicate');assert.equal(candidate.reviewRequired,false);assert.equal(candidate.maintenanceGate.outcome,'allow_inventory_maintenance');assert.equal(candidate.maintenanceGate.inventoryCreateAllowed,true);assert.equal(candidate.existingWorkItemRequest,null);});
test('confirmed held candidate records a preservation-bound plan but executes no merge',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,communityId:null,community:null,propertyReference:null,sourceIdentities:[]},right:{...right,communityId:null,community:null,propertyReference:null,sourceIdentities:[],sizeSqft:1225},evaluatedAt:at});const decision=recordInventoryDuplicateDecision({candidate,decision:'confirm_duplicate',canonicalInventoryRef:left.inventoryRef,reason:'The held intake was confirmed as the same legal unit.',reviewedByRef:'MANAGER-1',reviewedAt:at});assert.equal(decision.canonicalInventoryRef,left.inventoryRef);assert.equal(decision.supersededInventoryRef,right.inventoryRef);assert.equal(decision.mergeExecuted,false);assert.ok(decision.preservationRequirements.includes('reservation_and_availability_state'));assert.equal(decision.immutable,true);assert.match(decision.decisionHash,/^[a-f0-9]{64}$/);});
test('separate-property and defer decisions use the existing work item',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,communityId:null,community:null},right:{...right,communityId:null,community:null,sizeSqft:1225},evaluatedAt:at});const separate=recordInventoryDuplicateDecision({candidate,decision:'separate_properties',reason:'Two separate legal units were confirmed by evidence.',reviewedByRef:'MANAGER-1',reviewedAt:at});assert.equal(separate.existingWorkItemRequest.action,'complete_existing_work_item');const deferred=recordInventoryDuplicateDecision({candidate,decision:'defer',reason:'Awaiting the maintained Community from the source.',reviewedByRef:'MANAGER-1',reviewedAt:at,deferUntil:'2026-08-12T08:00:00.000Z'});assert.equal(deferred.existingWorkItemRequest.action,'reschedule_existing_work_item');assert.equal(deferred.existingWorkItemRequest.separateQueueCreated,false);});
test('review decisions fail closed on weak reason, invalid canonical record or past defer time',()=>{const candidate=buildInventoryDuplicateCandidate({left:{...left,communityId:null,community:null},right:{...right,communityId:null,community:null,sizeSqft:1225},evaluatedAt:at});assert.throws(()=>recordInventoryDuplicateDecision({candidate,decision:'confirm_duplicate',canonicalInventoryRef:'OTHER',reason:'Sufficient review reason',reviewedByRef:'MANAGER-1',reviewedAt:at}),/canonical/);assert.throws(()=>recordInventoryDuplicateDecision({candidate,decision:'separate_properties',reason:'short',reviewedByRef:'MANAGER-1',reviewedAt:at}),/reason/);assert.throws(()=>recordInventoryDuplicateDecision({candidate,decision:'defer',reason:'Sufficient review reason',reviewedByRef:'MANAGER-1',reviewedAt:at,deferUntil:'2026-08-10T08:00:00.000Z'}),/future/);});
