import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');

test('migration 091 contains the complete material configuration review and task chain',()=>{const sql=read('src/migrations/091_release6_marketing_material_compliance.sql');for(const marker of ['marketing_material_types','marketing_material_type_versions','marketing_channel_rule_versions','marketing_materials','marketing_material_versions','marketing_material_media_links','marketing_material_official_evidence_links','marketing_material_permit_snapshots','marketing_material_channel_requests','marketing_material_review_events','marketing_material_task_links'])assert.match(sql,new RegExp(marker));});
test('migration seeds no active legal permit or disclosure policy',()=>{const sql=read('src/migrations/091_release6_marketing_material_compliance.sql');assert.doesNotMatch(sql,/INSERT INTO marketing_(material_types|material_type_versions|channel_rule_versions)/);assert.match(sql,/permit_requirement.*DEFAULT 'none'/);});
test('submitted versions and evidence are protected from mutation',()=>{const sql=read('src/migrations/091_release6_marketing_material_compliance.sql');assert.match(sql,/protect_marketing_material_version/);assert.match(sql,/Submitted marketing material content is immutable/);assert.match(sql,/marketing_review_events_immutable/);assert.match(sql,/marketing_task_links_immutable/);});
test('marketing Tasks use dedicated context without synthetic customer records',()=>{const sql=read('src/migrations/091_release6_marketing_material_compliance.sql');assert.match(sql,/marketing_material_version_id/);assert.match(sql,/task_type IN\('marketing_material_review','marketing_material_follow_up'\).*lead_id IS NULL AND contact_id IS NULL/s);assert.match(sql,/tasks_one_open_marketing_review_idx/);});
test('route enforces configured Manager or Director assignment',()=>{const source=read('src/routes/marketing-material-compliance.js');assert.match(source,/resolveMaterialApprover/);assert.match(source,/managerId/);assert.match(source,/directorId/);assert.match(source,/assigned_approver_role/);assert.match(source,/marketing_material_review/);});
test('route reuses approved media documents campaigns permits and official evidence',()=>{const source=read('src/routes/marketing-material-compliance.js');for(const marker of ['property_media','document_versions','marketing_campaigns','permit_number','official_document_evidence_versions'])assert.match(source,new RegExp(marker));});
test('approval and current eligibility are separate and earliest expiry is calculated',()=>{const source=read('src/routes/marketing-material-compliance.js');assert.match(source,/effectiveReleaseUntil/);assert.match(source,/current_eligibility/);assert.match(source,/approved_release_until/);assert.match(source,/dependency_changed|all_current_checks_passed/);});
test('generic Task completion cannot approve marketing material',()=>{const source=read('src/routes/lead-operations.js');assert.match(source,/marketing_material_review/);assert.match(source,/generic Task completion cannot approve or release material/);assert.match(source,/t\.assignee_id=/);});
test('staff UI provides creation preflight submission register and review',()=>{const source=read('public/marketing-material-compliance-ui.js');for(const marker of ['New marketing material','Create, preflight and submit','Marketing material register','Manager or Director','MARKETING MATERIAL REVIEW','Assigned channel decisions'])assert.match(source,new RegExp(marker));});
test('server bootstrap and main navigation mount the package',()=>{assert.match(read('src/server.js'),/marketingMaterialComplianceRoutes/);assert.match(read('public/bootstrap.js'),/marketing-material-compliance-ui\.js/);assert.match(read('public/app.js'),/data-tab="marketingCompliance"/);});
test('package has no outbound publication or portal connector',()=>{const combined=[read('src/marketing-material-compliance-domain.js'),read('src/routes/marketing-material-compliance.js'),read('public/marketing-material-compliance-ui.js')].join('\n');assert.doesNotMatch(combined,/fetch\(['"]https?:|axios|property-finder|publishTo|sendEmail|sendSms/i);});
test('local review is loopback-only GET-only and blocks outbound connections',()=>{const server=read('tools/marketing-material-compliance-local/server.js'),app=read('tools/marketing-material-compliance-local/app.js');assert.match(server,/listen\(port,'127\.0\.0\.1'/);assert.match(server,/req\.method!=='GET'/);assert.match(server,/connect-src 'none'/);assert.match(app,/queue\('Manager'\)/);assert.match(app,/queue\('Director'\)/);assert.match(app,/No external publication occurs/);});
