import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createPartnerMasterLocalServer,partnerMasterHeaders}from'../tools/partner-master-local/server.js';const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
test('local partner governance covers organization types, verification, duplicates and immutable revisions',()=>{const sources=['tools/partner-master-local/index.html','tools/partner-master-local/app.js'].map(read).join('\n');for(const marker of ['Developer','External agency','Referral partner','Service provider','Possible duplicate','Verified and active','Expired licence','version 2','IMMUTABLE VERSION HISTORY'])assert.match(sources,new RegExp(marker,'i'));});
test('licence is optional and visibly recorded as not provided',()=>{const sources=['tools/partner-master-local/index.html','tools/partner-master-local/app.js'].map(read).join('\n');for(const marker of ['Licence details are optional','Not provided','Missing optional licence details do not block verification'])assert.match(sources,new RegExp(marker,'i'));});
test('Admin page contains no Inventory transaction controls',()=>{const sources=['tools/partner-master-local/index.html','tools/partner-master-local/app.js'].map(read).join('\n');for(const marker of ['organization reference data only','existing Inventory transaction may optionally reference','Inventory origin and individual owner selection do not belong'])assert.match(sources,new RegExp(marker,'i'));assert.doesNotMatch(sources,/id="inventory-origin"/i);});
test('governance reuses the existing Company identity and enforces the two-person review message',()=>{const sources=['tools/partner-master-local/index.html','tools/partner-master-local/app.js'].map(read).join('\n');for(const marker of ['Govern an existing Company','does not create another organization identity','Creator attempts own approval','different Administrator','Hidden from governance review'])assert.match(sources,new RegExp(marker,'i'));});
test('Inventory provenance is optional, compatible and does not replace existing facts',()=>{const sources=['tools/partner-master-local/inventory.html','tools/partner-master-local/inventory.js'].map(read).join('\n');for(const marker of ['Organization provenance','OPTIONAL','Inventory save allowed','Existing developer text','ownership remain unchanged','Service provider'])assert.match(sources,new RegExp(marker,'i'));assert.match(sources,/id="inventory-origin"/i);});
test('Inventory provenance includes direct-owner, active, pending and missing-link scenarios',()=>{const sources=['tools/partner-master-local/inventory.html','tools/partner-master-local/inventory.js'].map(read).join('\n');for(const marker of ['Direct owner','Compatible active version','Only pending version','No maintained organization','No Partner Master relationship required','completed later','append-only'])assert.match(sources,new RegExp(marker,'i'));});
test('local partner master contains no private contact input or external capability',()=>{const sources=['tools/partner-master-local/index.html','tools/partner-master-local/app.js','tools/partner-master-local/inventory.html','tools/partner-master-local/inventory.js','tools/partner-master-local/server.js'].map(read).join('\n');for(const prohibited of ['fetch(','XMLHttpRequest','WebSocket','sendBeacon','type="file"','ownerPhone','ownerEmail','passport','emiratesId'])assert.doesNotMatch(sources,new RegExp(prohibited.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(partnerMasterHeaders['Content-Security-Policy'],/connect-src 'none'/);});
test('local partner master server is loopback-only and GET-only',async()=>{const server=createPartnerMasterLocalServer();await new Promise((resolve,reject)=>server.once('error',reject).listen(0,'127.0.0.1',resolve));try{assert.equal(server.address().address,'127.0.0.1');for(const route of ['/','/inventory']){const response=await new Promise((resolve,reject)=>import('node:http').then(({get})=>get(`http://127.0.0.1:${server.address().port}${route}`,resolve).on('error',reject)));assert.equal(response.statusCode,200);response.resume();}}finally{await new Promise(resolve=>server.close(resolve));}});
