import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildGovernedMatchingRunV2,validateInventoryMatchDecision} from '../src/governed-matching-domain.js';
import {INVENTORY_EVALUATOR_FIELD_COLUMNS,MATCHING_COMPLETION_POLICY_VERSION,declarationAssessmentReadiness,evaluateInventoryEligibilityV2,inventoryEvaluatorProjection,scoreInventoryCandidateV2,validateCandidateAssessment,validateGovernedPromotion} from '../src/inventory-eligibility-domain.js';
const read=file=>readFileSync(new URL(`../${file}`,import.meta.url),'utf8');
const at='2026-08-14T10:00:00.000Z',requirement={id:'r1',versionNo:4,businessLine:'Sale',purpose:'own_use',areas:['Dubai Marina'],propertyTypes:['Apartment'],budgetMin:2000000,budgetMax:2600000,fundingMethod:'mortgage',bedroomsMin:2,bedroomsMax:3,sizeSqftMin:1100,sizeSqftMax:1500,timelineCode:'0_3_months',mustHaves:[],exclusions:[],preferences:[],acceptableTradeOffs:[]},listing={id:'l1',inventoryReference:'NYSA-INV-1',project:'Marina Residence',area:'Dubai Marina',community:'Dubai Marina',propertyType:'Apartment',bedrooms:'2',sizeSqft:1250,price:2400000,currency:'AED',paymentPlanType:'Mortgage',handoverStatus:'ready',status:'Available',effectiveStatus:'Available',workflowStatus:'approved',verificationStatus:'verified',verificationExpiresAt:'2026-09-01T00:00:00Z',availabilityConfirmedAt:'2026-08-12T10:00:00Z',transactionTypes:['Sale'],activeReservation:false};

test('v3 exact operational authority is eligible and evidence hashed',()=>{const result=evaluateInventoryEligibilityV2({listing,requirement,opportunityTransactionType:'Sale',checkedAt:at});assert.equal(result.state,'eligible');assert.equal(result.eligible,true);assert.match(result.evidenceHash,/^[a-f0-9]{64}$/);});
test('missing transaction type needs clarification and is never inferred',()=>{const result=evaluateInventoryEligibilityV2({listing:{...listing,transactionTypes:null},requirement,checkedAt:at});assert.equal(result.state,'needs_clarification');assert.ok(result.reasons.some(item=>item.code==='transaction_type_missing'));});
test('explicit transaction mismatch is excluded',()=>{const result=evaluateInventoryEligibilityV2({listing:{...listing,transactionTypes:['Rental']},requirement,checkedAt:at});assert.equal(result.state,'excluded');assert.ok(result.reasons.some(item=>item.code==='transaction_type_mismatch'));});
test('availability history is advisory and never removes otherwise eligible Inventory',()=>{for(const availabilityConfirmedAt of ['2026-08-01T00:00:00Z',null]){const result=evaluateInventoryEligibilityV2({listing:{...listing,availabilityConfirmedAt},requirement,checkedAt:at});assert.equal(result.state,'eligible');assert.equal(result.eligible,true);assert.ok(result.advisories.some(item=>item.code==='availability_confirmation'));}});
test('recorded maximum budget affects ranking and explanation but never eligibility',()=>{const result=evaluateInventoryEligibilityV2({listing:{...listing,price:2700000},requirement,checkedAt:at}),score=scoreInventoryCandidateV2(requirement,{...listing,price:2700000},[]);assert.equal(result.eligible,true);assert.ok(result.advisories.some(item=>item.code==='budget_above_recorded_maximum'));assert.equal(score.criteria.find(item=>item.code==='budget').state,'not_met');});
test('must-have and exclusion assessments inform ranking but never gate promotion',()=>{const declared={...requirement,mustHaves:['Full marina view'],exclusions:['Tenanted']},none=declarationAssessmentReadiness(declared,[]);assert.equal(none.promotionReady,true);assert.equal(none.assessmentComplete,false);const assessments=[{declarationKind:'must_have',declarationIndex:0,sequenceNo:1,result:'met'},{declarationKind:'exclusion',declarationIndex:0,sequenceNo:1,result:'not_met'}],complete=declarationAssessmentReadiness(declared,assessments);assert.equal(complete.promotionReady,true);assert.equal(complete.assessmentComplete,true);});
test('unassessed declarations remain eligible with visible ranking advisories',()=>{const result=evaluateInventoryEligibilityV2({listing,requirement:{...requirement,mustHaves:['Full marina view']},checkedAt:at});assert.equal(result.state,'eligible');assert.equal(result.eligible,true);assert.ok(result.advisories.some(item=>item.code==='must_have_fit_variance'));});
test('fixed v3 scoring reconciles to 100 points',()=>{const result=scoreInventoryCandidateV2(requirement,listing,[]);assert.equal(result.score,95);assert.equal(result.criteria.reduce((sum,item)=>sum+item.weight,0),100);assert.equal(result.criteria.find(item=>item.code==='customer_declarations').state,'not_assessed');});
test('shared evaluator fails closed when each governed eligibility fact is invalid or absent',()=>{
  for(const [overrides,code,state] of [
    [{deletedAt:at},'deleted','excluded'],[{workflowStatus:'draft'},'workflow_not_approved','excluded'],
    [{verificationStatus:'pending'},'verification_not_trusted','excluded'],[{effectiveStatus:null},'effective_status_missing','needs_clarification'],
    [{effectiveStatus:'Closed'},'not_available','excluded'],[{verificationExpiresAt:'2026-08-01T00:00:00Z'},'verification_expired','excluded'],
    [{transactionTypes:null},'transaction_type_missing','needs_clarification'],[{transactionTypes:['Rental']},'transaction_type_mismatch','excluded'],
    [{availabilityExpiresAt:'2026-08-01T00:00:00Z'},'availability_expired','excluded']
  ]){const result=evaluateInventoryEligibilityV2({listing:{...listing,...overrides},requirement,opportunityTransactionType:'Sale',checkedAt:at});assert.equal(result.state,state,code);assert.ok(result.reasons.some(item=>item.code===code),code);}
});
test('customer-fit variance and missing fit facts never create ineligibility',()=>{for(const overrides of [{price:2700000},{sizeSqft:null},{area:'Downtown Dubai',community:'Downtown Dubai'},{propertyType:'Villa'},{bedrooms:'1'},{paymentPlanType:'Developer plan'},{handoverStatus:'expected'}]){const result=evaluateInventoryEligibilityV2({listing:{...listing,...overrides},requirement,opportunityTransactionType:'Sale',checkedAt:at});assert.equal(result.eligible,true,JSON.stringify(overrides));}});
test('Opportunity creation explains that customer fit affects ranking only',()=>{const source=read('public/app.js');assert.match(source,/Only operationally usable Inventory is selectable/);for(const criterion of ['Budget','location','property type','bedrooms','size','funding','timing'])assert.match(source,new RegExp(criterion,'i'));assert.match(source,/affect ranking and explanation only/);});
test('shared scorer responds behaviorally to every governed ranking field',()=>{
  for(const [overrides,criterion] of [
    [{area:'Downtown Dubai',community:'Downtown Dubai'},'area_community'],[{propertyType:'Villa'},'property_type'],
    [{bedrooms:'1'},'bedrooms'],[{sizeSqft:900},'size'],[{price:2700000},'budget'],
    [{paymentPlanType:'Developer plan'},'funding_payment'],[{handoverStatus:'expected'},'timeline_handover']
  ]){const result=scoreInventoryCandidateV2(requirement,{...listing,...overrides},[]),item=result.criteria.find(entry=>entry.code===criterion);assert.ok(item,criterion);assert.equal(item.state,'not_met',criterion);}
});
test('one exported field contract generates the complete canonical Inventory projection',()=>{
  const projection=inventoryEvaluatorProjection('inventory');
  for(const column of Object.values(INVENTORY_EVALUATOR_FIELD_COLUMNS))assert.match(projection,new RegExp(`inventory\\.${column}\\b`),column);
  assert.match(projection,/nysa_inventory_effective_status\(inventory\.id\) AS effective_status/);
  assert.match(projection,/inventory\.status AS stored_status/);
});
test('v3 run ordering is stable by score missing facts and Inventory reference',()=>{const second={...listing,id:'l2',inventoryReference:'NYSA-INV-2'},run=buildGovernedMatchingRunV2(requirement,[second,listing],at,'Sale');assert.equal(run.policyVersion,MATCHING_COMPLETION_POLICY_VERSION);assert.deepEqual(run.candidates.map(item=>item.listingId),['l1','l2']);assert.equal(run.eligibleCount,2);});
test('assessment input requires controlled evidence and notes',()=>{assert.match(validateCandidateAssessment({declarationKind:'must_have',declarationIndex:0,result:'met',evidenceKind:'broker_review'}).error,/notes/);assert.equal(validateCandidateAssessment({declarationKind:'must_have',declarationIndex:0,result:'met',evidenceKind:'broker_review',assessmentNotes:'Reviewed exact Inventory facts'}).value.result,'met');});
test('promotion input requires version request ID and one to six exact selections',()=>{assert.match(validateGovernedPromotion({expectedOpportunityVersion:1,requestId:'bad',selections:[]}).error,/request ID/);const valid=validateGovernedPromotion({expectedOpportunityVersion:2,requestId:'10000000-0000-4000-8000-000000000001',selections:[{runId:'r',candidateId:'c',shortlistDecisionId:'d'}]});assert.equal(valid.value.selections.length,1);});
test('Opportunity shortlist decision requires an idempotent assignment request',()=>{const base={decision:'shortlisted',reasonCode:'strong_fit',reasonNotes:'Reviewed exact current requirement'};assert.match(validateInventoryMatchDecision({...base,assignToOpportunity:true}).error,/request ID/);const valid=validateInventoryMatchDecision({...base,assignToOpportunity:true,requestId:'10000000-0000-4000-8000-000000000001'});assert.equal(valid.value.assignToOpportunity,true);});
test('migration 092 is additive immutable and performs no legacy backfill',()=>{const sql=read('src/migrations/092_release3b_matching_completion.sql');for(const marker of ['transaction_types','size_sqft_min','needs_clarification','inventory_match_candidate_assessments','property_match_governed_origins','promotion_fingerprint','prevent_release2_immutable_evidence_mutation','r3b-eligibility-ranking-v2'])assert.match(sql,new RegExp(marker));assert.doesNotMatch(sql,/UPDATE listings SET transaction_types/i);});
test('migration 101 adds an immutable ranking-only fit policy without rewriting prior evidence',()=>{const sql=read('src/migrations/101_dev159_customer_fit_ranking_only.sql');for(const marker of ['r3b-operational-eligibility-fit-ranking-v3','operationalEligibilityOnly','customerFitNeverExcludes','customerFitVariancesRemainSelectable'])assert.match(sql,new RegExp(marker));assert.doesNotMatch(sql,/UPDATE matching_policy_versions|DELETE FROM matching_policy_versions/i);});
test('authenticated routes revalidate and atomically create governed assignment lineage',()=>{const route=read('src/routes/governed-matching.js');for(const marker of ['/assessments','/crm/opportunities/:opportunityId/governed-matches','evaluateInventoryEligibilityV2','property_match_governed_origins','inventory_assignments','inventory_assignment_events','governed_shortlist_assigned'])assert.match(route,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(route,/UPDATE listings SET status/i);});
test('viewing and Release 3C consume canonical v3 operational eligibility',()=>{assert.match(read('src/routes/opportunities.js'),/loadOpportunityInventoryEvaluation/);assert.match(read('src/routes/release3c-governed-shares.js'),/evaluateInventoryEligibilityV2/);assert.match(read('src/routes/release3c-governed-shares.js'),/inventoryEvaluatorProjection/);});
test('staff UI exposes clear ranking, atomic assignment and legacy recovery',()=>{const source=read('public/matching-completion-ui.js');for(const marker of ['need clarification','Assess declared must-haves','Missing / trade-offs','Shortlist and assign','Assign shortlisted property','seven-day Inventory Assignment'])assert.match(source,new RegExp(marker,'i'));assert.doesNotMatch(source,/data-promote-candidate/);assert.match(read('public/bootstrap.js'),/matching-completion-ui\.js/);});
test('local review is loopback-only GET-only synthetic and blocks outbound connections',()=>{const server=read('tools/matching-completion-local/server.js'),app=read('tools/matching-completion-local/app.js'),html=read('tools/matching-completion-local/index.html');assert.match(server,/listen\(port,'127\.0\.0\.1'/);assert.match(server,/req\.method!=='GET'/);assert.match(server,/connect-src 'none'/);assert.match(html,/SYNTHETIC DATA/);assert.match(app,/No reservation, stage change, viewing, Offer, message or external publication occurs/);});
