import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createPropertyFinderSandboxClient, PROPERTY_FINDER_SANDBOX_ORIGIN } from '../src/property-finder-sandbox.js';
import { normalizePropertyFinderListingForImport, propertyFinderListingImportPreview, PROPERTY_FINDER_LOCATION_SEARCH_CONFIRMATION } from '../src/property-finder-listing-import.js';

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const clock = Date.parse('2026-08-05T20:00:00.000Z');
const env = (overrides = {}) => ({ NYSA_DEPLOYMENT_ENV:'crm_test',PROPERTY_FINDER_ENVIRONMENT:'sandbox',PROPERTY_FINDER_API_BASE_URL:PROPERTY_FINDER_SANDBOX_ORIGIN,
  PROPERTY_FINDER_SANDBOX_API_KEY:'k'.repeat(40),PROPERTY_FINDER_SANDBOX_API_SECRET:'s'.repeat(32),PROPERTY_FINDER_SANDBOX_EXPIRES_AT:'2026-09-04T16:26:00.000Z',
  PROPERTY_FINDER_API_SCOPES:'users:read,listings:read,credits:read,compliances:read,listing_verification:full_access,locations:read,projects:read,webhooks:full_access',PROPERTY_FINDER_SANDBOX_ENABLED:'1',PROPERTY_FINDER_ALLOW_READS:'1',...overrides });

test('dev.141 performs one confirmed-capable PF location read and returns only selectable public hierarchy fields',async()=>{const calls=[],client=createPropertyFinderSandboxClient({env:env(),now:()=>clock,fetchImpl:async(url,options)=>{calls.push({url,options});if(url.endsWith('/v1/auth/token'))return new Response(JSON.stringify({accessToken:'t'.repeat(32),expiresIn:1800}),{status:200});if(url.includes('/v1/locations?'))return new Response(JSON.stringify({data:[{id:'44',name:'Meydan One',path:'Dubai, Meydan, Meydan One',type:'subcommunity',privateNote:'withheld'}]}),{status:200});throw new Error(url);}});const result=await client.searchLocations({query:'Meydan',parent:'Dubai'});assert.deepEqual(result.locations,[{id:'44',label:'Meydan One',path:'Dubai, Meydan, Meydan One',type:'subcommunity'}]);assert.match(calls[1].url,/search=Meydan/);assert.match(calls[1].url,/filter(?:%5B|\[)parent(?:%5D|\])=Dubai/);assert.equal(calls[1].options.method,'GET');assert.equal(result.externalWritesPerformed,false);assert.doesNotMatch(JSON.stringify(result),/privateNote|withheld/);});

test('dev.141 blocks location reads locally when locations scope or default-off switch is missing',async()=>{let calls=0;const missing=createPropertyFinderSandboxClient({env:env({PROPERTY_FINDER_API_SCOPES:'users:read,listings:read,credits:read'}),now:()=>clock,fetchImpl:async()=>{calls++;}});await assert.rejects(missing.searchLocations({query:'Meydan'}),e=>e.code==='location_read_scope_missing');const off=createPropertyFinderSandboxClient({env:env({PROPERTY_FINDER_ALLOW_READS:'0'}),now:()=>clock,fetchImpl:async()=>{calls++;}});await assert.rejects(off.searchLocations({query:'Meydan'}),e=>e.code==='sandbox_not_ready');assert.equal(calls,0);});

test('dev.141 compares a linked sanitized PF snapshot without deciding or changing either side',()=>{const pf=normalizePropertyFinderListingForImport({id:'pf-1',reference:'R3B-UAT-1',title:{en:'Test listing'},project:{name:'Meydan Villa'},location:{id:'44',name:'Meydan One'},type:'villa',bedrooms:4,size:4000,price:{type:'sale',amounts:{sale:10000000},currency:'AED'}}),linked={id:'core-1',inventoryReference:'NYSA-INV-000018',project:'Meydan Villa',community:'Meydan',propertyType:'Villa',bedrooms:'4',sizeSqft:4000,price:9000000,currency:'AED'},preview=propertyFinderListingImportPreview(pf,{linked});assert.equal(preview.match.kind,'linked');assert.equal(preview.reconciliation.changed,true);assert.deepEqual(preview.reconciliation.changes.map(x=>x.field),['price','community']);assert.ok(preview.reconciliation.changes.every(x=>x.decisionRequired));assert.match(preview.reconciliation.propertyFinderSnapshotHash,/^[a-f0-9]{64}$/);assert.match(preview.reconciliation.effect,/neither CORE nor Property Finder is changed/);});

test('dev.141 HTTP and UI require exact confirmation, full admin and expose selection plus read-only comparison',()=>{const route=read('src/routes/property-finder-sandbox.js'),ui=read('public/app.js');for(const marker of ['PROPERTY_FINDER_LOCATION_SEARCH_CONFIRMATION',"/integrations/property-finder/sandbox/locations/search",'client.searchLocations','ordinaryRecordsChanged: false','linkedChangeCount'])assert.ok(route.includes(marker),marker);for(const marker of ['Search PF locations','SEARCH_PROPERTY_FINDER_SANDBOX_LOCATIONS','Search, then select the exact PF location','Review PF changes','PF versus CORE read-only comparison','No records were changed'])assert.ok(ui.includes(marker),marker);assert.doesNotMatch(route,/client\.(create|update|delete|publish|unpublish)/);});
