import crypto from 'node:crypto';
import { Router } from '../lib/http-kit.js';
import { one,execute,transaction,uuid,audit } from '../db.js';
import { requireAuth } from '../auth.js';
import { canReadOpportunity,canWriteOpportunity } from '../crm-policy.js';
import { googleConfigured,googleAuthorizationUrl,exchangeGoogleCode,googleProfile,encryptSecret,decryptSecret,refreshGoogleToken,createGoogleViewingEvent,isGoogleOAuthCallbackPath } from '../google-calendar.js';
import { syncGoogleViewing } from '../calendar-sync.js';

const r=Router();r.use((req,res,next)=>isGoogleOAuthCallbackPath(req.path)?next():requireAuth(req,res,next));
const isAdmin=req=>req.broker.role==='admin'&&req.broker.jobRole==='admin';
r.get('/integrations/google-calendar/status',async(req,res)=>{const row=await one("SELECT account_email,calendar_id,connected_at FROM calendar_connections WHERE provider='google_calendar' AND disconnected_at IS NULL");res.json({configured:googleConfigured(),connected:Boolean(row),accountEmail:row?.accountEmail||null,calendarId:row?.calendarId||null,connectedAt:row?.connectedAt||null});});
r.get('/integrations/google-calendar/connect',async(req,res)=>{if(!isAdmin(req))return res.status(403).json({error:'Administrator access required'});if(!googleConfigured())return res.status(503).json({error:'Google Calendar OAuth environment settings are incomplete'});const state=crypto.randomBytes(32).toString('base64url'),hash=crypto.createHash('sha256').update(state).digest('hex');await execute("DELETE FROM integration_oauth_states WHERE expires_at<NOW()");await execute("INSERT INTO integration_oauth_states(state_hash,provider,broker_id,expires_at) VALUES($1,'google_calendar',$2,NOW()+INTERVAL '10 minutes')",[hash,req.broker.id]);res.statusCode=302;res.setHeader('Location',googleAuthorizationUrl(state));res.end();});
r.get('/integrations/google-calendar/callback',async(req,res)=>{if(req.query.error)return res.status(400).json({error:`Google authorization was not completed: ${req.query.error}`});const hash=crypto.createHash('sha256').update(req.query.state||'').digest('hex'),state=await one("DELETE FROM integration_oauth_states WHERE state_hash=$1 AND provider='google_calendar' AND expires_at>NOW() RETURNING *",[hash]);if(!state)return res.status(400).json({error:'Google authorization state is invalid or expired'});const actor=await one("SELECT id FROM brokers WHERE id=$1 AND role='admin' AND job_role='admin' AND active",[state.brokerId]);if(!actor)return res.status(403).json({error:'The initiating Administrator is no longer active'});const tokens=await exchangeGoogleCode(req.query.code||'');if(!tokens.refresh_token)return res.status(409).json({error:'Google did not return offline authorization; reconnect and approve access'});const profile=await googleProfile(tokens.access_token),id=uuid();await transaction(async client=>{await execute(`INSERT INTO calendar_connections(id,provider,account_email,calendar_id,encrypted_refresh_token,scope,connected_by) VALUES($1,'google_calendar',$2,'primary',$3,$4,$5) ON CONFLICT(provider) DO UPDATE SET account_email=EXCLUDED.account_email,encrypted_refresh_token=EXCLUDED.encrypted_refresh_token,scope=EXCLUDED.scope,connected_by=EXCLUDED.connected_by,connected_at=NOW(),disconnected_at=NULL,updated_at=NOW()`,[id,profile.email,encryptSecret(tokens.refresh_token),tokens.scope||'https://www.googleapis.com/auth/calendar',actor.id],client);await audit('CalendarConnection',id,'connected',actor.id,{provider:'google_calendar',accountEmail:profile.email},client);});res.statusCode=302;res.setHeader('Location','/#admin');res.end();});
r.post('/crm/opportunities/:id/viewings/:viewingId/google-meet',async(req,res)=>{const viewing=await one(`SELECT v.*,o.owner_id,o.created_by,o.assigned_team_id,o.opportunity_reference,li.project AS listing_project,c.email AS customer_email FROM viewings v JOIN opportunities o ON o.id=v.opportunity_id JOIN listings li ON li.id=v.listing_id JOIN contacts c ON c.id=o.contact_id WHERE v.id=$1 AND o.id=$2`,[req.params.viewingId,req.params.id]);if(!viewing)return res.status(404).json({error:'Viewing not found'});viewing.participantIds=[];if(!canReadOpportunity(req.broker,viewing)||!canWriteOpportunity(req.broker,viewing))return res.status(403).json({error:'Viewing is outside your writable scope'});const existing=await one("SELECT * FROM viewing_calendar_events WHERE viewing_id=$1 AND provider='google_calendar'",[viewing.id]);if(existing)return res.json(existing);const connection=await one("SELECT * FROM calendar_connections WHERE provider='google_calendar' AND disconnected_at IS NULL");if(!connection)return res.status(409).json({error:'Google Calendar is not connected'});const owner=await one('SELECT email FROM brokers WHERE id=$1',[viewing.ownerId]);viewing.attendeeEmails=[viewing.customerEmail,owner?.email].filter(Boolean);const token=await refreshGoogleToken(decryptSecret(connection.encryptedRefreshToken)),created=await createGoogleViewingEvent(token.access_token,connection.calendarId,viewing),record=await one(`INSERT INTO viewing_calendar_events(id,viewing_id,provider,external_event_id,calendar_id,event_url,meeting_url,sync_status,synced_by) VALUES($1,$2,'google_calendar',$3,$4,$5,$6,'active',$7) RETURNING *`,[uuid(),viewing.id,created.eventId,connection.calendarId,created.eventUrl,created.meetingUrl,req.broker.id]);await audit('ViewingCalendarEvent',record.id,'created',req.broker.id,{viewingId:viewing.id,externalEventId:created.eventId});res.status(201).json(record);});
r.post('/crm/opportunities/:id/viewings/:viewingId/google-meet/sync',async(req,res)=>{const viewing=await one(`SELECT v.*,o.owner_id,o.created_by,o.assigned_team_id FROM viewings v JOIN opportunities o ON o.id=v.opportunity_id WHERE v.id=$1 AND o.id=$2`,[req.params.viewingId,req.params.id]);if(!viewing)return res.status(404).json({error:'Viewing not found'});viewing.participantIds=[];if(!canWriteOpportunity(req.broker,viewing))return res.status(403).json({error:'Viewing is outside your writable scope'});const result=await syncGoogleViewing(viewing.id,req.broker.id,{reconcile:req.body?.reconcile===true});if(!result.linked)return res.status(409).json({error:'Viewing is not linked to Google Calendar'});res.status(result.error?502:200).json(result);});
export default r;
