import { Router } from '../lib/http-kit.js';
import { one,many,execute,transaction,uuid,audit } from '../db.js';
import { requireAuth } from '../auth.js';
import { calculateQualification,applyQualificationOverride,validateQualificationFactors,calculateMortgage,calculateInvestmentReturns,qualificationFollowUpPlan } from '../crm-domain.js';
import { hasInternalCrmIdentity,isManager,isCrmReadOnly,canReadLead,canWriteLead,canOperateLead } from '../crm-policy.js';
import { validateFeeItems,calculateFeeItems } from '../admin-governance.js';
import { classificationDimension,loadActiveClassificationCatalogue } from '../classification-catalogue.js';

const r=Router();r.use(requireAuth,(req,res,next)=>hasInternalCrmIdentity(req.broker)?next():res.status(403).json({error:'CRM customer data is restricted to NYSA staff'}));
const clean=v=>typeof v==='string'&&v.trim()?v.trim():null;
const admin=(req,res)=>req.broker.role==='admin'||(req.broker.jobRole==='admin_assistant'&&!/\/(approve|activate)$/.test(req.path))||(res.status(403).json({error:'Administrator access required for approval and activation'}),false);
const maintainer=admin;
async function leadFor(req,res,scope='read'){const lead=await one('SELECT * FROM leads WHERE id=$1',[req.params.id]);if(!lead){res.status(404).json({error:'Lead not found'});return null;}const allowed=scope==='manage'?canWriteLead(req.broker,lead):scope==='operate'?canOperateLead(req.broker,lead):canReadLead(req.broker,lead);if(!allowed){res.status(403).json({error:'Lead is outside your permitted scope'});return null;}return lead;}
async function createQualificationFollowUp({lead,assessment,temperature,actorId,client}){
  const policy=await one("SELECT * FROM sla_policies WHERE status='active' ORDER BY effective_from DESC LIMIT 1",[],client),plan=qualificationFollowUpPlan({temperature,assessedAt:new Date(),policy});
  if(!policy||!plan?.dueAt)throw Object.assign(new Error('An active SLA policy with valid Qualification follow-up timings is required'),{statusCode:409});
  const assigneeId=lead.assignedTo||actorId;
  const assignee=await one("SELECT id FROM brokers WHERE id=$1 AND status='active'",[assigneeId],client);
  if(!assignee)throw Object.assign(new Error('Qualification follow-up requires an active assigned Sales Agent'),{statusCode:409});
  await execute(`UPDATE tasks SET status='cancelled',outcome='Superseded by a later governed Qualification assessment',updated_at=NOW()
    WHERE lead_id=$1 AND task_type='qualification_follow_up' AND status IN('open','in_progress')`,[lead.id],client);
  const taskId=uuid(),subject=temperature==='Cold'?'Cold Lead nurture follow-up':`${temperature} Lead qualification follow-up`;
  const task=await one(`INSERT INTO tasks(id,lead_id,contact_id,task_type,subject,details,assignee_id,priority,due_at,created_by)
    VALUES($1,$2,$3,'qualification_follow_up',$4,$5,$6,$7,$8,$9) RETURNING *`,[taskId,lead.id,lead.contactId,subject,
    `Governed ${temperature} qualification follow-up. Deadline is set from the active SLA policy and must not be extended by the assigned Agent.`,assigneeId,plan.priority,plan.dueAt,actorId],client);
  await execute(`INSERT INTO qualification_follow_up_task_links(id,task_id,assessment_id,lead_id,sla_policy_id,temperature,timer_basis,target_minutes,cycle_number,cadence_business_days,due_at)
    VALUES($1,$2,$3,$4,$5,$6,$7,$8,1,$9,$10)`,[uuid(),task.id,assessment.id,lead.id,policy.id,temperature,plan.timerBasis,plan.targetMinutes,plan.cadenceBusinessDays,plan.dueAt],client);
  const next=await one("SELECT MIN(due_at) AS due_at FROM tasks WHERE lead_id=$1 AND status IN('open','in_progress')",[lead.id],client);
  await execute('UPDATE leads SET next_follow_up_at=$1,updated_at=NOW() WHERE id=$2',[next?.dueAt||plan.dueAt,lead.id],client);
  await audit('Task',task.id,'qualification_sla_created',actorId,{assessmentId:assessment.id,slaPolicyId:policy.id,temperature,timerBasis:plan.timerBasis,targetMinutes:plan.targetMinutes,dueAt:plan.dueAt},client);
  return {taskId:task.id,dueAt:plan.dueAt,priority:plan.priority,timerBasis:plan.timerBasis,targetMinutes:plan.targetMinutes,cadenceBusinessDays:plan.cadenceBusinessDays,slaPolicyId:policy.id};
}

r.get('/admin/qualification-models',async(req,res)=>{if(!maintainer(req,res))return;res.json({models:await many('SELECT * FROM qualification_models ORDER BY model_code,version DESC')});});
r.post('/admin/qualification-models',async(req,res)=>{
  if(!maintainer(req,res))return;const b=req.body||{},factorError=validateQualificationFactors(b.factors);
  const catalogue=await loadActiveClassificationCatalogue(),objective=classificationDimension(catalogue,'customer_objective')?.values.find(value=>value.active&&value.code===clean(b.customerObjective)&&value.code!=='not_confirmed');
  if(!clean(b.modelCode)||!clean(b.name)||!clean(b.purpose)||!objective||factorError)return res.status(400).json({error:factorError||`modelCode, name, purpose and an active Customer objective from ${catalogue.version.code} are required`});
  const totalWeight=b.factors.reduce((sum,x)=>sum+Number(x.weight),0);if(Math.abs(totalWeight-100)>0.001)return res.status(400).json({error:'Qualification factor weights must total 100%'});
  const hot=Number(b.thresholds?.hotMin),warm=Number(b.thresholds?.warmMin);if(!Number.isFinite(hot)||!Number.isFinite(warm)||warm<0||hot>100||warm>=hot)return res.status(400).json({error:'Thresholds must satisfy 0 <= warmMin < hotMin <= 100'});
  const modelCode=clean(b.modelCode),customerObjective=clean(b.customerObjective),row=await transaction(async client=>{
    await execute('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`qualification-model:${modelCode}:${customerObjective}`],client);
    const current=await one('SELECT * FROM qualification_models WHERE model_code=$1 AND customer_objective=$2 ORDER BY version DESC LIMIT 1',[modelCode,customerObjective],client),id=uuid(),version=(current?.version||0)+1;
    const created=await one(`INSERT INTO qualification_models(id,model_code,name,description,purpose,business_line,customer_objective,version,factors,thresholds,guidance,supersedes_model_id,created_by)
      VALUES($1,$2,$3,$4,$5,NULL,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[id,modelCode,clean(b.name),clean(b.description),clean(b.purpose),customerObjective,version,JSON.stringify(b.factors),JSON.stringify(b.thresholds),JSON.stringify(b.guidance||{}),current?.id||null,req.broker.id],client);
    await audit('QualificationModel',id,'draft_created',req.broker.id,{version,customerObjective},client);return created;
  });res.status(201).json(row);
});
r.post('/admin/qualification-models/:modelId/test',async(req,res)=>{if(!admin(req,res))return;const model=await one('SELECT * FROM qualification_models WHERE id=$1',[req.params.modelId]);if(!model)return res.status(404).json({error:'Model not found'});const result=calculateQualification(model,req.body?.inputs||{});res.status(result.error?400:200).json(result);});
r.patch('/admin/qualification-models/:modelId',async(req,res)=>{if(!admin(req,res))return;const current=await one('SELECT * FROM qualification_models WHERE id=$1',[req.params.modelId]);if(!current)return res.status(404).json({error:'Model not found'});if(current.status!=='draft')return res.status(409).json({error:'Only draft qualification versions can be edited'});const b=req.body||{},factorError=validateQualificationFactors(b.factors);if(factorError)return res.status(400).json({error:factorError});const total=b.factors.reduce((sum,x)=>sum+Number(x.weight),0);if(Math.abs(total-100)>0.001)return res.status(400).json({error:'Qualification factor weights must total 100%'});const warm=Number(b.thresholds?.warmMin),hot=Number(b.thresholds?.hotMin);if(!Number.isFinite(warm)||!Number.isFinite(hot)||warm<0||warm>=hot||hot>100)return res.status(400).json({error:'Score bands must satisfy 0 <= Warm < Hot <= 100'});const row=await one('UPDATE qualification_models SET name=$1,description=$2,purpose=$3,business_line=NULL,factors=$4,thresholds=$5,guidance=$6 WHERE id=$7 AND status=$8 RETURNING *',[clean(b.name),clean(b.description),clean(b.purpose),JSON.stringify(b.factors),JSON.stringify(b.thresholds),JSON.stringify(b.guidance||{}),current.id,'draft']);await audit('QualificationModel',row.id,'draft_edited',req.broker.id,{version:row.version});res.json(row);});
r.post('/admin/qualification-models/:modelId/approve',async(req,res)=>{
  if(!admin(req,res))return;if(!clean(req.body?.reason))return res.status(400).json({error:'Approval reason is required'});
  const row=await one("UPDATE qualification_models SET status='approved',approved_by=$1,approved_at=NOW(),approval_reason=$2 WHERE id=$3 AND status='draft' RETURNING *",[req.broker.id,clean(req.body.reason),req.params.modelId]);
  if(!row)return res.status(409).json({error:'Only a draft model can be approved'});await audit('QualificationModel',row.id,'approved',req.broker.id,{reason:req.body.reason});res.json(row);
});
r.post('/admin/qualification-models/:modelId/activate',async(req,res)=>{
  if(!admin(req,res))return;const result=await transaction(async client=>{const model=await one('SELECT * FROM qualification_models WHERE id=$1 FOR UPDATE',[req.params.modelId],client);if(!model||model.status!=='approved')return null;
    await execute("UPDATE qualification_models SET status='retired',effective_to=NOW() WHERE model_code=$1 AND customer_objective=$2 AND status='active'",[model.modelCode,model.customerObjective],client);
    const active=await one("UPDATE qualification_models SET status='active',effective_from=NOW() WHERE id=$1 RETURNING *",[model.id],client);await audit('QualificationModel',model.id,'activated',req.broker.id,null,client);return active;});
  if(!result)return res.status(409).json({error:'Only an approved model can be activated'});res.json(result);
});
r.post('/admin/qualification-models/:modelId/retire',async(req,res)=>{
  if(req.broker.role!=='admin')return res.status(403).json({error:'Full Administrator access required to retire a Qualification Version'});
  const reason=clean(req.body?.reason);if(!reason||reason.length<10)return res.status(400).json({error:'A meaningful retirement reason is required'});
  const row=await transaction(async client=>{const model=await one('SELECT * FROM qualification_models WHERE id=$1 FOR UPDATE',[req.params.modelId],client);if(!model||!['draft','approved','active'].includes(model.status))return null;const retired=await one("UPDATE qualification_models SET status='retired',effective_to=NOW() WHERE id=$1 RETURNING *",[model.id],client);await audit('QualificationModel',model.id,'retired',req.broker.id,{reason,priorStatus:model.status,customerObjective:model.customerObjective},client);return retired;});
  if(!row)return res.status(409).json({error:'This Qualification Version is already retired or unavailable'});res.json(row);
});

r.get('/crm/leads/:id/qualification-assessments',async(req,res)=>{const lead=await leadFor(req,res);if(!lead)return;res.json({assessments:await many(`SELECT a.*,m.name AS model_name,m.model_code FROM qualification_assessments a JOIN qualification_models m ON m.id=a.model_id WHERE a.lead_id=$1 ORDER BY assessed_at DESC`,[lead.id])});});
r.post('/crm/leads/:id/qualification-assessments/:assessmentId/override',async(req,res)=>{
  const lead=await leadFor(req,res,'manage');if(!lead)return;if(!isManager(req.broker))return res.status(403).json({error:'Only an authorized manager or director can override a qualification result'});
  const source=await one('SELECT * FROM qualification_assessments WHERE id=$1 AND lead_id=$2',[req.params.assessmentId,lead.id]);if(!source)return res.status(404).json({error:'Qualification assessment not found'});
  const b=req.body||{},override=applyQualificationOverride({temperature:source.calculatedTemperature},b.overrideTemperature,b.overrideReason,true);if(override.error)return res.status(400).json({error:override.error});if(!override.overrideReason)return res.status(400).json({error:'Select a result different from the calculated result and provide the mandatory override reason'});
  const id=uuid(),row=await transaction(async client=>{const assessment=await one(`INSERT INTO qualification_assessments(id,lead_id,model_id,model_version,factor_inputs,factor_contributions,calculated_score,calculated_temperature,
      final_temperature,recommendation,override_reason,overridden_by,assessed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,
      [id,lead.id,source.modelId,source.modelVersion,JSON.stringify(source.factorInputs),JSON.stringify(source.factorContributions),source.calculatedScore,source.calculatedTemperature,override.finalTemperature,JSON.stringify(source.recommendation||{}),override.overrideReason,req.broker.id,req.broker.id],client);
    await execute('UPDATE leads SET temperature=$1,updated_at=NOW() WHERE id=$2',[override.finalTemperature,lead.id],client);const nextAction=await createQualificationFollowUp({lead,assessment,temperature:override.finalTemperature,actorId:req.broker.id,client});await audit('QualificationAssessment',id,'manager_override',req.broker.id,{sourceAssessmentId:source.id,calculatedTemperature:source.calculatedTemperature,finalTemperature:override.finalTemperature,reason:override.overrideReason,nextAction},client);return{assessment,nextAction};});
  res.status(201).json({...row.assessment,contributions:source.factorContributions,recommendation:source.recommendation,nextAction:row.nextAction});
});
r.get('/crm/leads/:id/qualification-questionnaire',async(req,res)=>{const lead=await leadFor(req,res);if(!lead)return;const catalogue=await loadActiveClassificationCatalogue(),objective=classificationDimension(catalogue,'customer_objective')?.values.find(value=>value.active&&value.code===lead.customerObjective&&value.code!=='not_confirmed');if(!objective)return res.status(409).json({error:'Confirm an active Customer objective before qualification; legacy mixed classifications cannot select a questionnaire'});if(lead.classificationCatalogueVersionId!==catalogue.version.id)return res.status(409).json({error:`Lead classification is not pinned to active catalogue ${catalogue.version.code}; complete governed classification review first`});const model=await one(`SELECT * FROM qualification_models WHERE model_code='lead_readiness' AND status='active' AND customer_objective=$1 ORDER BY effective_from DESC LIMIT 1`,[lead.customerObjective]);if(!model)return res.status(409).json({error:`No active Lead Qualification Version is available for Customer objective ${lead.customerObjective}. Ask an administrator to approve the exact objective-specific questions, weights and thresholds.`});res.json({model:{id:model.id,name:model.name,version:model.version,purpose:model.purpose,customerObjective:model.customerObjective,classificationVersion:catalogue.version.code,factors:model.factors.map(f=>({...f,question:f.question||f.description||f.label,answerType:f.answerType||'scale',answerOptions:f.answerOptions||[]})),thresholds:model.thresholds,guidance:model.guidance},canOverride:isManager(req.broker)});});
r.post('/crm/leads/:id/qualification-assessments',async(req,res)=>{
  const lead=await leadFor(req,res,'operate');if(!lead||isCrmReadOnly(req.broker))return;const b=req.body||{};
  if(String(lead.assignedTo)!==String(req.broker.id))return res.status(403).json({error:'The assigned Sales Agent records the qualification assessment; a Manager may review and use the separate audited override action'});
  const contactEvidence=await one(`SELECT id,due_at FROM activities WHERE lead_id=$1 AND voided_at IS NULL AND completed_at IS NOT NULL
    AND contact_outcome_code IN ('substantive_discussion','requirements_confirmed','viewing_agreed','offer_feedback','decision_received','callback_requested')
    ORDER BY completed_at DESC LIMIT 1`,[lead.id]);
  if(!contactEvidence)return res.status(409).json({error:'Record a completed substantive Customer discussion before assessing qualification'});
  if(!contactEvidence.dueAt)return res.status(409).json({error:'The completed Customer discussion must retain a dated next action before qualification'});
  const catalogue=await loadActiveClassificationCatalogue(),objective=classificationDimension(catalogue,'customer_objective')?.values.find(value=>value.active&&value.code===lead.customerObjective&&value.code!=='not_confirmed');
  if(!objective||lead.classificationCatalogueVersionId!==catalogue.version.id)return res.status(409).json({error:`Confirm the Customer objective against active classification catalogue ${catalogue.version.code}`});
  const model=await one(`SELECT * FROM qualification_models WHERE model_code='lead_readiness' AND status='active' AND customer_objective=$1 ORDER BY effective_from DESC LIMIT 1`,[lead.customerObjective]);
  if(!model)return res.status(409).json({error:`No active objective-specific Qualification Version is available for ${lead.customerObjective}`});const calculated=calculateQualification(model,b.inputs||{});if(calculated.error)return res.status(400).json({error:calculated.error});
  const override=applyQualificationOverride(calculated,b.overrideTemperature,b.overrideReason,isManager(req.broker));
  if(override.error)return res.status(isManager(req.broker)?400:403).json({error:override.error});
  const finalTemperature=override.finalTemperature,overrideReason=override.overrideReason,overriddenBy=overrideReason?req.broker.id:null;
  const id=uuid(),row=await transaction(async client=>{const currentLead=await one('SELECT stage FROM leads WHERE id=$1 FOR UPDATE',[lead.id],client);if(currentLead.stage!=='Contacted'&&currentLead.stage!=='Qualified')return{error:'Record the first Customer contact before completing qualification'};const assessment=await one(`INSERT INTO qualification_assessments(id,lead_id,model_id,model_version,factor_inputs,factor_contributions,calculated_score,calculated_temperature,
      final_temperature,recommendation,override_reason,overridden_by,assessed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,
      [id,lead.id,model.id,model.version,JSON.stringify(b.inputs||{}),JSON.stringify(calculated.contributions),calculated.score,calculated.temperature,finalTemperature,JSON.stringify(calculated.recommendation),overrideReason,overriddenBy,req.broker.id],client);
    await execute("UPDATE leads SET temperature=$1,stage=CASE WHEN stage='Contacted' THEN 'Qualified' ELSE stage END,updated_at=NOW() WHERE id=$2",[finalTemperature,lead.id],client);if(currentLead.stage==='Contacted')await execute("INSERT INTO lead_stage_history(id,lead_id,from_stage,to_stage,reason_code,changed_by) VALUES($1,$2,'Contacted','Qualified','qualification_assessment_completed',$3)",[uuid(),lead.id,req.broker.id],client);const nextAction=await createQualificationFollowUp({lead,assessment,temperature:finalTemperature,actorId:req.broker.id,client});await audit('QualificationAssessment',id,'calculated_and_lead_qualified',req.broker.id,{modelId:model.id,modelVersion:model.version,score:calculated.score,calculatedTemperature:calculated.temperature,finalTemperature,overrideReason,leadStageFrom:currentLead.stage,leadStageTo:'Qualified',nextAction},client);return{assessment,nextAction};});
  if(row.error)return res.status(409).json({error:row.error});res.status(201).json({...row.assessment,leadStage:'Qualified',contributions:calculated.contributions,recommendation:calculated.recommendation,nextAction:row.nextAction});
});

r.get('/admin/regulatory-assumptions',async(req,res)=>{if(!admin(req,res))return;res.json({versions:await many('SELECT * FROM regulatory_assumption_versions ORDER BY created_at DESC')});});
r.post('/admin/regulatory-assumptions',async(req,res)=>{if(!admin(req,res))return;const b=req.body||{},items=b.items||b.assumptions?.items,error=validateFeeItems(items);if(!clean(b.name)||!clean(b.disclaimer)||!clean(b.sourceReference)||error)return res.status(400).json({error:error||'Rule-set name, authority/reference and disclaimer are required'});const prior=await one('SELECT COALESCE(MAX(version),0) AS version FROM regulatory_assumption_versions WHERE name=$1',[clean(b.name)]),id=uuid(),assumptions={items,sourceReference:clean(b.sourceReference),placeholders:items.map(x=>`fee.${x.code}`)};const row=await one(`INSERT INTO regulatory_assumption_versions(id,name,version,currency,assumptions,disclaimer,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[id,clean(b.name),prior.version+1,b.currency||'AED',JSON.stringify(assumptions),clean(b.disclaimer),req.broker.id]);await audit('RegulatoryAssumption',id,'draft_created',req.broker.id,{itemCount:items.length,sourceReference:clean(b.sourceReference)});res.status(201).json(row);});
r.patch('/admin/regulatory-assumptions/:assumptionId',async(req,res)=>{if(!admin(req,res))return;const b=req.body||{},items=b.items,error=validateFeeItems(items);if(error||!clean(b.name)||!clean(b.disclaimer)||!clean(b.sourceReference))return res.status(400).json({error:error||'Rule-set name, authority/reference and disclaimer are required'});const row=await one("UPDATE regulatory_assumption_versions SET name=$1,currency=$2,assumptions=$3,disclaimer=$4,updated_at=NOW() WHERE id=$5 AND status='draft' RETURNING *",[clean(b.name),b.currency||'AED',JSON.stringify({items,sourceReference:clean(b.sourceReference),placeholders:items.map(x=>`fee.${x.code}`)}),clean(b.disclaimer),req.params.assumptionId]);if(!row)return res.status(409).json({error:'Only a draft assumption version can be edited'});await audit('RegulatoryAssumption',row.id,'draft_edited',req.broker.id,{itemCount:items.length,sourceReference:clean(b.sourceReference)});res.json(row);});
r.post('/admin/regulatory-assumptions/:assumptionId/test',async(req,res)=>{if(!admin(req,res))return;const found=await one('SELECT * FROM regulatory_assumption_versions WHERE id=$1',[req.params.assumptionId]);if(!found)return res.status(404).json({error:'Assumption version not found'});const result=calculateFeeItems(found.assumptions?.items,req.body||{});res.status(result.error?400:200).json(result);});
r.post('/admin/regulatory-assumptions/:assumptionId/approve',async(req,res)=>{if(!admin(req,res))return;const reason=clean(req.body?.reason);if(!reason)return res.status(400).json({error:'Approval reason is required'});const row=await one("UPDATE regulatory_assumption_versions SET status='approved',approved_by=$1,approved_at=NOW(),approval_reason=$2,updated_at=NOW() WHERE id=$3 AND status='draft' RETURNING *",[req.broker.id,reason,req.params.assumptionId]);if(!row)return res.status(409).json({error:'Only a draft assumption version can be approved'});await audit('RegulatoryAssumption',row.id,'approved',req.broker.id,{reason});res.json(row);});
r.post('/admin/regulatory-assumptions/:assumptionId/activate',async(req,res)=>{if(!admin(req,res))return;const row=await transaction(async client=>{const found=await one('SELECT * FROM regulatory_assumption_versions WHERE id=$1 FOR UPDATE',[req.params.assumptionId],client);if(!found||found.status!=='approved')return null;await execute("UPDATE regulatory_assumption_versions SET status='retired',effective_to=NOW(),updated_at=NOW() WHERE status='active'",[],client);const active=await one("UPDATE regulatory_assumption_versions SET status='active',effective_from=NOW(),effective_to=NULL,updated_at=NOW() WHERE id=$1 RETURNING *",[found.id],client);await audit('RegulatoryAssumption',found.id,'activated',req.broker.id,null,client);return active;});if(!row)return res.status(409).json({error:'Only an approved assumption version can be activated'});res.json(row);});
r.post('/admin/regulatory-assumptions/:assumptionId/retire',async(req,res)=>{if(req.broker.role!=='admin')return res.status(403).json({error:'Administrator access required to retire a fee rule-set version'});const reason=clean(req.body?.reason);if(!reason)return res.status(400).json({error:'Retirement reason is required'});const row=await one("UPDATE regulatory_assumption_versions SET status='retired',effective_to=NOW(),updated_at=NOW() WHERE id=$1 AND status IN ('draft','approved') RETURNING *",[req.params.assumptionId]);if(!row)return res.status(409).json({error:'Only a draft or approved version can be retired directly; activate a replacement to retire the active version'});await audit('RegulatoryAssumption',row.id,'retired',req.broker.id,{reason});res.json(row);});

function buildScenarioCalculation(type,inputs,listing,assumption){
  const output=type==='mortgage'?calculateMortgage(inputs||{}):calculateInvestmentReturns(inputs||{});if(output.error)return{error:output.error};
  const fees=calculateFeeItems(assumption.assumptions?.items,{propertyPrice:inputs?.propertyPrice??inputs?.price??listing?.price,propertyValue:inputs?.propertyValue??inputs?.propertyPrice??inputs?.price??listing?.price,mortgageAmount:inputs?.mortgageAmount??inputs?.loanAmount??output.principal??0,quantity:inputs?.quantity??1,quantities:inputs?.quantities||{},transactionTypes:['purchase',type==='mortgage'?'mortgage':'investment'],fundingMethod:inputs?.fundingMethod??(type==='mortgage'?'bank_finance':'cash'),propertyType:inputs?.propertyType??listing?.propertyType,serviceChannel:inputs?.serviceChannel});if(fees.error)return{error:`Active fee rules are invalid: ${fees.error}`};
  output.regulatoryFees=fees.values;output.regulatoryFeeDetails=fees.details;output.totalRegulatoryFees=fees.total;output.regulatoryFeeTotalMinimum=fees.totalMinimum;output.regulatoryFeeTotalMaximum=fees.totalMaximum;output.assumptionVersion={id:assumption.id,name:assumption.name,version:assumption.version};return{output};
}

r.get('/crm/leads/:id/financial-scenarios',async(req,res)=>{const lead=await leadFor(req,res);if(!lead)return;const [scenarios,activeAssumption]=await Promise.all([many(`SELECT f.*,l.project AS listing_project,a.name AS assumption_name,a.version AS assumption_version FROM financial_scenarios f LEFT JOIN listings l ON l.id=f.listing_id JOIN regulatory_assumption_versions a ON a.id=f.assumption_version_id WHERE f.lead_id=$1 ORDER BY f.created_at DESC`,[lead.id]),one("SELECT id,name,version,currency,disclaimer,effective_from FROM regulatory_assumption_versions WHERE status='active'")]);res.json({scenarios,activeAssumption});});
r.post('/crm/leads/:id/financial-scenarios/preview',async(req,res)=>{
  const lead=await leadFor(req,res,'operate');if(!lead)return;const b=req.body||{},type=b.scenarioType;if(!['mortgage','roi'].includes(type))return res.status(400).json({error:'Select Mortgage affordability or Investment return'});
  const listing=b.listingId?await one('SELECT id,property_type,price FROM listings WHERE id=$1 AND deleted_at IS NULL',[b.listingId]):null;if(b.listingId&&!listing)return res.status(400).json({error:'Linked property not found'});const assumption=await one("SELECT * FROM regulatory_assumption_versions WHERE status='active'");if(!assumption)return res.status(409).json({error:'Calculation unavailable until an administrator activates an approved Regulatory and Fee Assumption version'});
  const calculated=buildScenarioCalculation(type,b.inputs||{},listing,assumption);if(calculated.error)return res.status(400).json({error:calculated.error});res.json({output:calculated.output,assumption:{id:assumption.id,name:assumption.name,version:assumption.version,currency:assumption.currency,disclaimer:assumption.disclaimer}});
});
r.post('/crm/leads/:id/financial-scenarios',async(req,res)=>{
  const lead=await leadFor(req,res,'operate');if(!lead)return;const b=req.body||{},type=b.scenarioType;
  if(!['mortgage','roi'].includes(type)||!clean(b.scenarioName))return res.status(400).json({error:'scenarioType and scenarioName are required'});
  const listing=b.listingId?await one('SELECT id,property_type,price FROM listings WHERE id=$1 AND deleted_at IS NULL',[b.listingId]):null;if(b.listingId&&!listing)return res.status(400).json({error:'Listing not found'});
  const assumption=await one("SELECT * FROM regulatory_assumption_versions WHERE status='active'");if(!assumption)return res.status(409).json({error:'Calculation unavailable until an administrator activates an approved Regulatory and Fee Assumption version'});if(b.expectedAssumptionVersionId&&b.expectedAssumptionVersionId!==assumption.id)return res.status(409).json({error:'The active Regulatory and Fee Assumption changed after preview. Calculate and review again before saving'});
  const calculated=buildScenarioCalculation(type,b.inputs||{},listing,assumption);if(calculated.error)return res.status(409).json({error:calculated.error});const output=calculated.output;
  const id=uuid(),row=await one(`INSERT INTO financial_scenarios(id,lead_id,listing_id,scenario_type,scenario_name,input_snapshot,output_snapshot,currency,assumption_version_id,
    property_price,loan_amount,monthly_payment,gross_yield,net_yield,cash_on_cash_return,disclaimer,created_by)
    VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[id,lead.id,b.listingId||null,type,clean(b.scenarioName),JSON.stringify(b.inputs||{}),JSON.stringify(output),assumption.currency,assumption.id,output.propertyPrice||output.price,output.principal||null,output.monthlyPayment||null,output.grossYield||null,output.netYield||null,output.cashOnCashReturn||null,assumption.disclaimer,req.broker.id]);
  await audit('FinancialScenario',id,'created',req.broker.id,{leadId:lead.id,type,assumptionVersionId:assumption.id});res.status(201).json({...row,output});
});

export default r;
