import {prepareBrokerNextActions,previewBrokerActionDecision} from '/modules/broker-next-action-domain.js';
const now='2026-08-08T12:00:00.000Z';
const responses=[
  {responseReference:'RESP-SYN-001',evidenceHash:'a'.repeat(64),outcome:'viewing_requested',occurredAt:'2026-08-08T09:30:00.000Z',responsibleAgentReference:'AGENT-SYN-001',opportunityReference:'OPP-SYN-021',requirementReference:'REQ-SYN-003',propertyReference:'NYSA-SYN-002',responseSource:'provider_event_simulation',workingContext:{summary:'Customer requested a viewing for Garden Terrace.',missingFacts:['Confirm customer availability','Confirm property access window']}},
  {responseReference:'RESP-SYN-002',evidenceHash:'b'.repeat(64),outcome:'interested',occurredAt:'2026-08-08T08:30:00.000Z',responsibleAgentReference:'AGENT-SYN-001',opportunityReference:'OPP-SYN-021',requirementReference:'REQ-SYN-003',propertyReferences:['NYSA-SYN-001','NYSA-SYN-002'],responseSource:'manual_fallback',workingContext:{summary:'Customer remains interested in two shortlisted properties.',missingFacts:['Service-charge confirmation']}},
  {responseReference:'RESP-SYN-003',evidenceHash:'c'.repeat(64),outcome:'information_required',occurredAt:'2026-08-08T11:30:00.000Z',responsibleAgentReference:'AGENT-SYN-002',opportunityReference:'OPP-SYN-034',requirementReference:'REQ-SYN-009',propertyReference:'NYSA-SYN-003',responseSource:'provider_event_simulation',workingContext:{summary:'Customer requested a payment-plan and market-evidence comparison.',missingFacts:['Approved payment schedule']}},
  {responseReference:'RESP-SYN-004',evidenceHash:'d'.repeat(64),outcome:'not_suitable',occurredAt:'2026-08-08T10:15:00.000Z',responsibleAgentReference:'AGENT-SYN-003',opportunityReference:'OPP-SYN-055',requirementReference:'REQ-SYN-014',propertyReference:'NYSA-SYN-004',responseSource:'manual_fallback',notSuitableEvidence:{preferenceImpact:{code:'confirmed_change',label:'Customer confirmed a preference change; new requirement version required'}},workingContext:{summary:'Customer confirmed that the minimum internal area is now 1,350 sq ft.',missingFacts:[]}}
];
const $=selector=>document.querySelector(selector),escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let queueData=null,selectedAction=null;
const sourceLabel=value=>value==='provider_event_simulation'?'Simulated provider event':'Manual fallback';
function renderStats(){const c=queueData.counts;$('#stats').innerHTML=`<article><small>Total open</small><b>${c.total}</b></article><article class="danger"><small>Overdue</small><b>${c.overdue}</b></article><article class="warn"><small>Due soon</small><b>${c.dueSoon}</b></article><article><small>Queue generated</small><b>12:00</b></article>`;}
function actionCard(item){return `<button class="action-card ${item.ageingState} ${selectedAction?.actionReference===item.actionReference?'selected':''}" data-action="${escapeHtml(item.actionReference)}"><span class="priority">${escapeHtml(item.priority)}</span><div><p>${escapeHtml(item.opportunityReference)} · ${escapeHtml(item.responsibleAgentReference)}</p><h3>${escapeHtml(item.action.label)}</h3><p>${item.propertyReferences.map(escapeHtml).join(' · ')}</p></div><strong>${escapeHtml(item.ageingLabel)}</strong></button>`;}
function renderQueue(){const filter=$('#filter').value,items=queueData.actions.filter(item=>filter==='all'||item.ageingState===filter);$('#queue').innerHTML=items.length?items.map(actionCard).join(''):'<p class="none">No actions match this filter.</p>';document.querySelectorAll('.action-card').forEach(button=>button.addEventListener('click',()=>{selectedAction=queueData.actions.find(item=>item.actionReference===button.dataset.action);renderQueue();renderDetail();}));}
function renderDetail(){const a=selectedAction;if(!a)return;$('#detail').innerHTML=`<div class="detail-head"><span>${escapeHtml(a.priority)} priority</span><b>${escapeHtml(a.ageingLabel)}</b></div><p class="eyebrow">PREPARED WORKING CONTEXT</p><h2>${escapeHtml(a.action.label)}</h2><dl><div><dt>Opportunity</dt><dd>${escapeHtml(a.opportunityReference)}</dd></div><div><dt>Requirement</dt><dd>${escapeHtml(a.requirementReference||'Not linked')}</dd></div><div><dt>Responsible agent</dt><dd>${escapeHtml(a.responsibleAgentReference)}</dd></div><div><dt>Response source</dt><dd>${sourceLabel(a.responseSource)}</dd></div><div><dt>Due</dt><dd>${escapeHtml(a.dueAt)}</dd></div><div><dt>Evidence</dt><dd>${escapeHtml(a.responseEvidenceHash.slice(0,12))}...</dd></div></dl><section class="context"><b>Why this action exists</b><p>${escapeHtml(a.workingContext.summary||'No summary available')}</p><b>Before acting</b>${a.workingContext.missingFacts.length?`<ul>${a.workingContext.missingFacts.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`:'<p>No missing facts recorded.</p>'}</section><form id="decision-form"><label>Broker decision<select id="decision"><option value="start">Start work</option><option value="complete">Preview completion</option><option value="defer">Defer with reason</option></select></label><label id="defer-row" class="hidden">Defer until<input id="defer-until" type="datetime-local" value="2026-08-08T14:00"></label><label>Evidence note<textarea id="decision-note" rows="3">Synthetic broker decision for local functional review.</textarea></label><button type="submit">Preview work record</button><p class="hint">Preview only. Nothing is assigned, sent, completed or changed.</p></form><div id="decision-result" class="decision-result hidden"></div>`;$('#decision').addEventListener('change',()=>$('#defer-row').classList.toggle('hidden',$('#decision').value!=='defer'));$('#decision-form').addEventListener('submit',previewDecision);}
async function previewDecision(event){event.preventDefault();const decision=$('#decision').value,result=await previewBrokerActionDecision(selectedAction,{decision,note:$('#decision-note').value,decidedBy:selectedAction.responsibleAgentReference,decidedAt:now,deferUntil:decision==='defer'?new Date($('#defer-until').value).toISOString():null}),node=$('#decision-result');node.classList.remove('hidden');if(result.error){node.className='decision-result error';node.textContent=result.error;return;}node.className='decision-result';node.innerHTML=`<span>PREVIEW · NOT APPLIED</span><h3>${escapeHtml(decision==='complete'?'Completion evidence':decision==='defer'?'Deferral evidence':'Work-start evidence')}</h3><p>Action ${escapeHtml(selectedAction.actionReference)} retains its original response evidence. Inventory and Opportunity remain unchanged.</p><code>${result.value.evidenceHash.slice(0,20)}...</code>`;}
$('#filter').addEventListener('change',renderQueue);
const prepared=await prepareBrokerNextActions({now,responses});if(prepared.error){document.body.textContent=prepared.error;}else{queueData=prepared.value;renderStats();renderQueue();}
