const ui=window.NysaInventoryWorkspaceUI;
const field=(label,placeholder='')=>`<div><label>${label}</label><input placeholder="${placeholder}"></div>`;
const reviewNav=`<nav class="modal-actions" aria-label="Dummy view selector"><a class="btn" href="/">Create Inventory</a><a class="btn" href="/?view=detail">Saved Inventory</a><a class="btn btn-primary" href="/?view=opportunity">Inventory selection</a></nav>`;
const create=`<section class="record-workspace"><div class="modal record-workspace-surface listing-edit-modal"><div class="eyebrow">SYNTHETIC LOCAL REVIEW · UAT-035</div><h2>Create Inventory draft</h2>${ui.journeyMarkup({mode:'create'})}<form id="listing-form"><div class="form-grid">${ui.sectionHeading('1A','Property identity','Identify the exact property once. Developer and Area use maintained master data; Unit Reference and Unit Number are one governed value.')}<div class="span3 inventory-headline-field"><label>Inventory headline / name *</label><input placeholder="Distinctive internal Inventory name"></div>${field('Project *')}${field('Developer','Select from Developer Master')}${field('Area *','Select from Area Maintenance')}${field('Community *')}${field('Building *')}${field('Unit Reference / Unit Number *')}${field('Property type *')}${field('Bedrooms')}${ui.sectionHeading('1B','Commercial terms and handover','Record the asking terms and the seller/developer payment structure. Buyer funding stays in Structured Requirements.')}${field('Size (sqft) *')}${field('Asking price *')}${field('Reference / market price')}${field('Currency *','AED')}${field('Seller / developer payment plan')}${field('Handover status *')}${ui.sectionHeading('1C','Source, responsibility and readiness','Identify who supplied the property information, preserve the originating NYSA agent and record current availability separately from verification.')}${field('Who or what supplied this property to NYSA? *','Owner, Developer, agency/co-broker, internal referral or source-file reference')}<div class="span3">${field('Originating NYSA Inventory agent *','Current authorized user')}</div>${field('Availability last confirmed','Optional')}<div class="span3 inventory-additional-party-note"><b>Owner and authority are completed after the Draft is saved</b><span>Step 2 opens in the saved record before Manager verification.</span></div><div class="span3"><label>Notes</label><textarea rows="3"></textarea></div></div><div class="modal-actions"><button type="button" class="btn">Cancel</button><button type="button" class="btn btn-primary">Save as draft</button></div></form></div></section>`;
const detail=`<section class="record-workspace"><div class="modal record-workspace-surface listing-detail-modal"><div class="eyebrow">SYNTHETIC LOCAL REVIEW · UAT-035</div><h2>Saved Inventory workspace</h2>${ui.journeyMarkup({mode:'detail',verificationStatus:'unverified',partyCount:0})}<section id="inventory-step-property" class="inventory-record-section"><div class="inventory-record-section-heading"><span>STEP 1</span><div><h3>Inventory property record</h3><p>The saved identity, commercial terms, source and NYSA responsibility used downstream.</p></div><button class="btn btn-sm">Edit property facts</button></div><div class="kv-grid"><div><b>Property</b>Synthetic apartment</div><div><b>Source</b>Developer Master</div><div><b>Responsible agent</b>Authorized test role</div></div></section><section id="inventory-step-authority" class="inventory-record-section"><div class="inventory-record-section-heading"><span>STEP 2</span><div><h3>Owner, Internal Inventory authority and activation</h3><p>Complete the owner or represented-party record first. Manager verification follows beneath it.</p></div></div><details open class="listing-workflow-history"><summary>2A · Owner / represented party and Internal Inventory authority (0 parties)</summary><div class="empty compact">No Inventory-side party maintained.</div><form class="form-grid"><div><label>Role *</label><select><option>Seller</option></select></div>${field('Name *')}${field('Internal-use authority evidence *')}<button class="btn btn-primary span3" type="button">Save Inventory owner / party</button></form></details><section class="proposal-readiness blocked"><b>2B · Inventory verification: unverified</b><span>Save the owner or represented party and authority evidence before submitting for Manager verification.</span></section></section><section id="inventory-step-external" class="inventory-record-section inventory-external-journey"><div class="inventory-record-section-heading"><span>STEP 3 · OPTIONAL</span><div><h3>External Listing preparation</h3><p>Available after Internal Inventory activation; portal evidence remains separate.</p></div></div><div class="inventory-additional-party-note"><b>External portal fields are maintained separately</b><button class="btn btn-sm" type="button">Open External Portal Listings</button></div></section></div></section>`;
const opportunity=`<section class="record-workspace"><div class="modal record-workspace-surface opportunity-modal"><div class="eyebrow">SYNTHETIC LOCAL REVIEW · UAT-036</div><h2>Inventory selection</h2><p>Add, remove, replace or re-add Inventory being considered for this customer until a final Offer is accepted.</p><section class="inventory-record-section"><div class="form-grid"><div><label>Customer journey stage</label><select id="opportunity-stage"><option>Requirements</option><option>Matching</option><option>Viewing</option><option>Offer</option><option>Negotiation</option><option>Accepted Offer</option><option>Booking</option><option>Deal</option></select></div><div class="span2 proposal-readiness ready" id="opportunity-lock-state"></div></div></section><section class="inventory-record-section"><div class="inventory-record-section-heading"><span>ACTIVE SELECTION</span><div><h3>Selected Inventory</h3><p>Removal retains immutable history and requires a reason.</p></div></div><div id="opportunity-attached"></div></section><section class="inventory-record-section"><div class="inventory-record-section-heading"><span>MAINTAIN</span><div><h3>Add or re-add Inventory</h3><p>Every action revalidates approval, verification, availability, reservation and the current seven-day confirmation.</p></div></div><div class="form-grid"><div class="span2"><label>Eligible Inventory</label><select id="opportunity-eligible"><option value="inv-a">NYSA-INV-000101 · Synthetic Marina apartment</option></select></div><button class="btn btn-primary" id="opportunity-attach" type="button">Add Inventory to selection</button></div><div id="opportunity-removed"></div></section><section class="proposal-readiness ready"><b id="opportunity-summary"></b><div class="opportunity-eligibility-counts"><span>2 verification not trusted</span><span>1 availability stale</span><span>1 budget maximum exceeded</span></div></section><details class="opportunity-eligibility-details"><summary>Review why Inventory is not currently selectable (4)</summary><div class="opportunity-eligibility-list"><article><b>NYSA-INV-000201</b><small>Synthetic Downtown unit</small><p>Verification is not currently trusted.</p></article><article><b>NYSA-INV-000202</b><small>Synthetic Creek unit</small><p>Availability confirmation is older than seven days.</p></article><article><b>NYSA-INV-000203</b><small>Synthetic Hills unit</small><p>Inventory price exceeds the confirmed maximum budget.</p></article><article><b>NYSA-INV-000204</b><small>Synthetic Harbour unit</small><p>Inventory transaction type must be confirmed.</p></article></div></details></div></section>`;
const reviewView=new URLSearchParams(location.search).get('view');
document.querySelector('#app').innerHTML=reviewView==='opportunity'?opportunity:reviewView==='detail'?detail:create;
document.querySelector('#app h2')?.insertAdjacentHTML('afterend',reviewNav);
if(reviewView==='detail'){
  const nav=document.querySelector('[aria-label="Dummy view selector"]');
  nav?.insertAdjacentHTML('afterend',`<section class="inventory-record-section" aria-labelledby="lifecycle-review-title"><div class="inventory-record-section-heading"><span>INTERACTIVE REVIEW</span><div><h3 id="lifecycle-review-title">Inventory maintenance across the transaction lifecycle</h3><p>Select a stage to review exactly what can change and what is protected.</p></div></div><label for="lifecycle-stage">Transaction position</label><select id="lifecycle-stage"><option value="draft">Inventory draft</option><option value="pre_acceptance">Opportunity / viewing / Offer not accepted</option><option value="accepted">Accepted Offer / reservation</option><option value="deal">Deal created</option></select><div id="lifecycle-result" class="proposal-readiness"></div></section>`);
  const result=document.querySelector('#lifecycle-result'),edit=document.querySelector('#inventory-step-property button');
  const states={
    draft:{locked:false,title:'Property record is maintainable',body:'Edit property, commercial, source and authority facts. Save explicitly. The Inventory must still pass verification before customer use.'},
    pre_acceptance:{locked:false,title:'Maintainable before final acceptance',body:'Edit Inventory facts and add, remove or replace Opportunity Inventory. Eligibility is recalculated. Existing Offer revisions remain immutable; changed commercial terms require a new Offer revision.'},
    accepted:{locked:true,title:'Transactional facts are protected',body:'The accepted Offer and reservation fix the selected property and agreed terms. Do not silently remove or replace Inventory. Use the governed cancellation, release or recovery pathway first.'},
    deal:{locked:true,title:'Deal snapshot is immutable',body:'Inventory maintenance cannot rewrite the Deal. A governed Deal correction or Close Lost recovery must be recorded; ordinary master-data maintenance remains separate from the completed transaction.'}
  };
  const sync=()=>{const state=states[document.querySelector('#lifecycle-stage').value];result.className=`proposal-readiness ${state.locked?'blocked':'ready'}`;result.innerHTML=`<b>${state.title}</b><span>${state.body}</span>`;if(edit){edit.disabled=state.locked;edit.textContent=state.locked?'Property facts protected at this stage':'Edit property facts';}};
  document.querySelector('#lifecycle-stage').addEventListener('change',sync);sync();
}
if(reviewView==='opportunity'){
  const inventory={eligible:[{id:'inv-a',reference:'NYSA-INV-000101 · Synthetic Marina apartment'}],attached:[],removed:[]};
  const locked=()=>['Accepted Offer','Booking','Deal'].includes(document.querySelector('#opportunity-stage').value);
  const render=()=>{const isLocked=locked(),attached=document.querySelector('#opportunity-attached'),removed=document.querySelector('#opportunity-removed'),select=document.querySelector('#opportunity-eligible'),attach=document.querySelector('#opportunity-attach'),lock=document.querySelector('#opportunity-lock-state');
    attached.innerHTML=inventory.attached.length?inventory.attached.map(item=>`<article class="inventory-additional-party-note" data-attached="${item.id}"><b>${item.reference}</b><span>Currently selected</span><label>Removal reason * <input data-remove-reason placeholder="Required before removal"></label><button class="btn btn-sm" data-remove="${item.id}" ${isLocked?'disabled':''}>Remove from selection</button></article>`).join(''):'<div class="empty compact">No Inventory is currently selected. Use the maintained selector below.</div>';
    removed.innerHTML=inventory.removed.length?`<details open><summary>Previously removed Inventory (${inventory.removed.length})</summary>${inventory.removed.map(item=>`<article class="inventory-additional-party-note"><b>${item.reference}</b><span>Removed history retained · ${item.reason}</span><button class="btn btn-sm" data-readd="${item.id}" ${isLocked?'disabled':''}>Re-add after eligibility validation</button></article>`).join('')}</details>`:'';
    select.innerHTML=inventory.eligible.map(item=>`<option value="${item.id}">${item.reference}</option>`).join('')||'<option value="">No additional eligible Inventory</option>';attach.disabled=isLocked||!inventory.eligible.length;
    lock.className=`span2 proposal-readiness ${isLocked?'blocked':'ready'}`;lock.innerHTML=isLocked?'<b>Selection locked</b><span>An accepted Offer, Booking or Deal protects the selected Inventory.</span>':'<b>Selection maintainable</b><span>Attach, remove or re-add Inventory at this stage.</span>';
    document.querySelector('#opportunity-summary').textContent=`${inventory.eligible.length} eligible to attach · ${inventory.attached.length} currently attached · ${inventory.eligible.length+inventory.attached.length+inventory.removed.length+4} reviewed`;
    document.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{const row=button.closest('[data-attached]'),reason=row.querySelector('[data-remove-reason]').value.trim();if(!reason){row.querySelector('[data-remove-reason]').focus();return;}const index=inventory.attached.findIndex(item=>item.id===button.dataset.remove),[item]=inventory.attached.splice(index,1);inventory.removed.push({...item,reason});render();});
    document.querySelectorAll('[data-readd]').forEach(button=>button.onclick=()=>{const index=inventory.removed.findIndex(item=>item.id===button.dataset.readd),[item]=inventory.removed.splice(index,1);inventory.attached.push(item);render();});
  };
  document.querySelector('#opportunity-attach').onclick=()=>{if(locked()||!inventory.eligible.length)return;inventory.attached.push(inventory.eligible.shift());render();};
  document.querySelector('#opportunity-stage').addEventListener('change',render);render();
}
