from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

OUT = Path(r"C:\Users\ajitr\OneDrive\Desktop\nysa-pocket-ledger\canonical-worktree\outputs\NYSA_CORE_Application_Wide_Implicit_Business_Rules_Register_dev158.docx")
NAVY, BLUE, DARK, INK, MUTED = "17365D", "2E74B5", "1F4D78", "202124", "5F6368"
PALE_BLUE, PALE_GOLD, PALE_RED, PALE_GREEN, LIGHT, BORDER, WHITE = "E8EEF5", "FFF4D6", "FDECEC", "E9F5EE", "F2F4F7", "CBD2D9", "FFFFFF"

def run(p, text, bold=False, italic=False, size=10.5, color=INK):
    r=p.add_run(text); r.bold=bold; r.italic=italic; r.font.name="Calibri"; r.font.size=Pt(size); r.font.color.rgb=RGBColor.from_string(color)
    r._element.get_or_add_rPr().rFonts.set(qn("w:ascii"),"Calibri"); r._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"),"Calibri"); return r

def shade(cell, fill):
    pr=cell._tc.get_or_add_tcPr(); shd=pr.find(qn("w:shd"))
    if shd is None: shd=OxmlElement("w:shd"); pr.append(shd)
    shd.set(qn("w:fill"),fill)

def margins(cell, top=80, start=120, bottom=80, end=120):
    pr=cell._tc.get_or_add_tcPr(); tc=pr.first_child_found_in("w:tcMar")
    if tc is None: tc=OxmlElement("w:tcMar"); pr.append(tc)
    for name,val in (("top",top),("start",start),("bottom",bottom),("end",end)):
        node=tc.find(qn(f"w:{name}"))
        if node is None: node=OxmlElement(f"w:{name}"); tc.append(node)
        node.set(qn("w:w"),str(val)); node.set(qn("w:type"),"dxa")

def table_widths(table, widths, indent=120):
    table.autofit=False; pr=table._tbl.tblPr
    w=pr.find(qn("w:tblW"))
    if w is None: w=OxmlElement("w:tblW"); pr.append(w)
    w.set(qn("w:w"),str(sum(widths))); w.set(qn("w:type"),"dxa")
    ind=pr.find(qn("w:tblInd"))
    if ind is None: ind=OxmlElement("w:tblInd"); pr.append(ind)
    ind.set(qn("w:w"),str(indent)); ind.set(qn("w:type"),"dxa")
    grid=table._tbl.tblGrid
    for c in list(grid): grid.remove(c)
    for x in widths:
        gc=OxmlElement("w:gridCol"); gc.set(qn("w:w"),str(x)); grid.append(gc)
    for row in table.rows:
        tr=row._tr.get_or_add_trPr()
        if tr.find(qn("w:cantSplit")) is None: tr.append(OxmlElement("w:cantSplit"))
        for i,cell in enumerate(row.cells):
            tc=cell._tc.get_or_add_tcPr(); cw=tc.find(qn("w:tcW"))
            if cw is None: cw=OxmlElement("w:tcW"); tc.append(cw)
            cw.set(qn("w:w"),str(widths[min(i,len(widths)-1)])); cw.set(qn("w:type"),"dxa"); margins(cell)

def note(doc, title, text, fill=PALE_GOLD):
    t=doc.add_table(rows=1,cols=1); t.alignment=WD_TABLE_ALIGNMENT.LEFT; table_widths(t,[9360]); shade(t.cell(0,0),fill)
    p=t.cell(0,0).paragraphs[0]; p.paragraph_format.space_after=Pt(1); run(p,title+"\n",True,color=NAVY); run(p,text)
    doc.add_paragraph().paragraph_format.space_after=Pt(1)

def field(doc, label, text, color=NAVY):
    p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(2); p.paragraph_format.line_spacing=1.05
    run(p,label+": ",True,color=color); run(p,text); return p

def bullet(doc,text):
    p=doc.add_paragraph(style="List Bullet"); p.paragraph_format.space_after=Pt(2); run(p,text); return p

def page_field(paragraph):
    paragraph.alignment=WD_ALIGN_PARAGRAPH.RIGHT
    run(paragraph,"Page ",size=9,color=MUTED)
    fld=OxmlElement("w:fldSimple"); fld.set(qn("w:instr"),"PAGE"); paragraph._p.append(fld)

def R(id,title,status,current,used,impact,flow,exceptions,evidence,decision):
    return dict(id=id,title=title,status=status,current=current,used=used,impact=impact,flow=flow,exceptions=exceptions,evidence=evidence,decision=decision)

sections = [
("A", "Platform, identity and access", [
R("A-01","Internal-only operating model","Approved design decision","CORE treats Release 1–3 CRM functions as internal NYSA operations. External Customer self-service is not part of dev.158.","Authentication, navigation, API authorization and every operational workspace.","Customer actions must be recorded by an authorized internal user; there is no customer-controlled correction or approval path.","User invitation/activation → authenticated session → role and scope checks → permitted API action → audit event.","Configured external connectors may transmit approved content, but they do not create an external CORE user.","DECISIONS D001; crm-policy.js; auth.js","Confirm whether later releases should retain internal-only operation or introduce governed external portals."),
R("A-02","Role set and internal identity test","Implemented; owner review required","Recognized job roles are Administrator, Admin Assistant, Sales Agent, Listing Agent, Manager, Director and Accountant. Internal identity also depends on broker role/classification.","All permission checks, dashboards, queues, approvals and data scopes.","A staff record with an unexpected classification can be authenticated yet fail domain access, or receive the fallback Agent dashboard.","Broker master → invitation/activation → role/classification → API policy → role workspace.","Partner brokers are distinct; inactive users are rejected.","crm-policy.js; dashboard-domain.js; routes/auth.js","Approve the definitive job-role catalogue, fallbacks and role-change governance."),
R("A-03","Read scope is broader than write scope","Implemented implicit rule — high priority","For Leads and Customers, most internal non-Accountant users receive register-wide read SQL scope; write and assignment rights are narrower. Accountant is excluded.","Customer register, Lead register, search, Lead detail and related records.","Sales and Listing staff may see records beyond their own/team operational responsibility. This affects privacy, least privilege and search expectations.","Authenticated user → lead/contact read-scope predicate → API result; separate write policy controls mutation.","Documents and some private evidence use additional access checks; broad register visibility does not necessarily grant file access.","crm-policy.js leadScopeSql/contactScopeSql; PERMISSIONS_MATRIX.md","Decide whether read scope should be organization-wide, team-wide or assignment/participation-based per role."),
R("A-04","Role-scoped Opportunity and Deal access","Implemented","Opportunity scope is based on ownership, creation, team or explicit participation. Listing Agents are generally read participants, not Opportunity writers.","Opportunity register/detail, transaction workspaces and Deal activity.","Cross-team collaboration requires explicit participation or a privileged role; otherwise a user may know Inventory but not access the related Opportunity.","Lead ownership/team → Opportunity attribution/participants → scope predicate → permitted action.","Administrator/Director have broader reading; Accountant remains limited to finance-related use.","crm-policy.js; transaction-representation-domain.js","Confirm role-by-role read, write, participate and approve rights."),
R("A-05","Director and Accountant are operationally read-only","Implemented","Director and Accountant are not general CRM writers. Director retains specific approval/read powers; Accountant is excluded from Lead/Opportunity operations.","Lead, Opportunity and transaction mutations; approval routes.","Executive oversight is separated from routine data entry. Urgent corrections still need an operational role or controlled admin action.","Role → write policy → denial or domain-specific approval action.","Director can approve governed items such as Deals/marketing; this is not blanket write authority.","crm-policy.js; PERMISSIONS_MATRIX.md","Confirm whether any named correction or delegation actions are required for Director/Accountant."),
R("A-06","Seven-day authenticated session","Implemented implicit default","A session lasts 168 hours. The cookie is HttpOnly, SameSite=Strict and Secure in production; password reset invalidates existing sessions.","Sign-in, API authentication and password reset.","Long sessions reduce repeated login but increase exposure if a workstation remains unlocked.","Login → random token → hashed session row and cookie → expiry/explicit logout/reset.","Expired sessions are deleted/rejected; throttling is in-memory rather than a shared durable store.","auth.js; routes/auth.js","Approve session duration, idle timeout, concurrent-session policy and rate-limit durability."),
R("A-07","Password and activation minimums","Implemented","Passwords require at least 12 characters. Accounts are created through bootstrap or governed invitation/activation; reset uses expiring, single-use records.","User onboarding, password reset and authentication.","The policy sets a length floor but does not express composition, breached-password or MFA requirements.","Invitation/reset request → controlled code → identity fields and password → active broker → audit/session invalidation.","Codes expire; consumed/cancelled codes cannot be reused.","routes/auth.js; admin-governance.js","Approve password, MFA, lockout and identity-verification policy."),
R("A-08","API authorization is authoritative","Approved design decision","Visible buttons are convenience only; server routes repeat role, scope, state and version checks.","Every mutation and restricted read.","Bypassing the UI cannot lawfully bypass governance. UAT must test API denial as well as hidden controls.","UI request → authenticated API → policy/domain validation → transaction → audit/result.","Administrator does not automatically bypass independent-approval rules.","PERMISSIONS_MATRIX.md; route modules","Retain as a mandatory architecture rule."),
]),
("B", "Administration, masters and governance", [
R("B-01","Controlled values are versioned, not hard-deleted","Approved design decision","Governed master values use stable codes and active/versioned records; historical references remain.","Areas, teams, qualification models, fees, templates, document rules and other masters.","Changing a label should not rewrite historical meaning; deactivation prevents new use while preserving old cases.","Draft version → test/review → approve/activate → new transactions freeze/reference version → retire old version.","Some early dropdowns remain source-code constants rather than fully governed masters.","DECISIONS D012; admin-governance.js; migrations","Confirm which remaining source-code lists must become administered masters."),
R("B-02","Stable codes use lowercase snake_case","Implemented implicit standard","Administrative stable codes must use lowercase letters, numbers and underscores with controlled length.","Master creation, integrations, rules and audit references.","Human labels can change, but integrations and stored rules depend on stable codes.","Admin input → code validation → versioned master → downstream foreign key/code use.","Legacy fixed labels may not follow this convention.","admin-governance.js","Approve naming convention, ownership and change-control process."),
R("B-03","Area routing has a global fallback","Approved decision; detailed precedence implicit","Routing chooses the lowest numeric priority matching source/business type and Area; an All Areas rule is considered after an Area-specific rule at the same priority.","Lead creation and assignment derivation.","A single priority or broad rule can divert a large volume of Leads. Missing Area-specific coverage silently falls back when a global rule exists.","Lead source + current business type + primary Area → eligible routing rules → priority/specificity sort → team/agent assignment.","If no rule matches, the route must handle an unassigned/exception state. Current business-type defects can influence routing.","DECISIONS D014; routing-service.js","Approve the exact precedence, tie-break, fallback and no-match escalation rules."),
R("B-04","Primary routing Area must be one of the preferred Areas","Implemented; user has challenged seller-side application","The Lead validator requires primary routing Area to be contained in the Lead's preferred Areas.","Lead capture and routing.","This is coherent for buyer/tenant demand but forces artificial demand fields for seller/landlord supply Leads.","Lead fields → preferred-Area normalization → primary-Area consistency validation → routing.","Owner direction already indicates seller/landlord Areas should derive from linked Inventory; dev.158 does not implement that distinction.","routing-service.js; UAT-063","Pending implementation design: apply demand-Area rules only to buyer/tenant objectives; define the supply-side Inventory linkage."),
R("B-05","Qualification models require tested approval and activation","Implemented","A model moves draft → tested/approved → active; the previous active model for the same line is retired.","Lead qualification questionnaires and score/temperature derivation.","Changing the active model changes future assessments, while prior assessments retain their evidence.","Factors/weights/thresholds → test result → approval → activation → Lead assessment → stored contributions/version.","Models can be generic or business-line-specific; mixed business-type values make coverage ambiguous.","admin routes/UI; crm-domain.js","Confirm model ownership, four-eyes approval, effective dating and correct classification dimensions."),
R("B-06","Fee items and proposal templates are versioned","Implemented","Fee definitions and proposal templates are versioned and validated. Comparison proposals require at least two properties; all proposals allow one to three properties and limited approved media.","Proposal generation and commercial disclosure.","A proposal is reproducible only when its exact template, fees, properties and media versions are retained.","Active template/fees → selected Opportunity properties → generated immutable version → governed send/acknowledgment.","Template limits may be too restrictive for some commercial cases; owner approval is not recorded.","admin-governance.js; files-proposals routes","Approve property/media limits, mandatory disclosures and template ownership."),
R("B-07","Partner organizations are separate from Companies and Customers","Approved design direction; partly implicit workflow","Developer, external agency, referral partner and service-provider organizations have legal/classification versions, verification and relationship records. They are not Customer roles.","Developer master, brokerage arrangements, listing NOC and Inventory party governance.","Mixing Developer into Customer role creates duplicate identities and unclear KYC/authority. Organization governance supports reuse across many properties.","Partner organization → evidence/version review → active relationship → optional Inventory linkage.","Direct-owner Inventory may proceed without a partner organization when secured owner-party evidence exists.","partner-organization-domain.js; partner-master-domain.js; UAT-040/UAT-057","Owner direction is to remove Developer from Customer roles; confirm all remaining organization classes and migration treatment."),
R("B-08","Community and Building need governed identity, but Inventory still uses free text","Observed design gap — high priority","Market Intelligence supports canonical Community mapping, yet dev.158 Inventory capture stores Community/Building as text and does not bind to an approved external location identity.","Inventory creation, duplicate detection, matching, reporting, market intelligence and future portal mapping.","Spelling variants fragment stock and can break Property Finder-approved community/building mapping. Duplicate keys can also diverge.","Current: typed text → Inventory. Target to decide: governed Area/Community/Building → Inventory → external mapping/version.","Property Finder is disabled; no live portal mapping was tested or authorized.","inventory-domain.js; market-intelligence-integration-domain.js; UAT-051","Approve canonical hierarchy, aliases, effective dating, unmapped exception process and PF mapping ownership."),
]),
("C", "Customers, companies, consent and channels", [
R("C-01","Customer is a reusable party master","Approved model","A Customer is created once and may have multiple Leads, roles, channels, facts and KYC evidence.","Customer register, Lead capture, proposals, communications and Deals.","Creating a new Customer for every enquiry fragments history and duplicate controls.","Customer master → roles/channels/KYC → one or more Leads → Opportunities/Deal party links.","Transaction-only counterparties are separate when the party should not become a full Customer.","DATA_MODEL.md; crm routes","Confirm merge/survivorship and cross-team ownership rules."),
R("C-02","Customer role list mixes genuine customer roles with organization types","Implemented; owner has rejected Developer","Values include Buyer, Seller, Landlord, Tenant, Developer, Investor and Other. Developer is also modeled as a partner organization.","Customer create/edit, Customer register and role history.","Developer duplicates an organization classification and may trigger wrong KYC, ownership and reporting semantics. Investor is also ambiguous without a transaction side.","Role selection → contact_roles → UI/report context; it does not by itself create Inventory or a Developer master.","One Customer may hold multiple roles; current primary contact_type can oversimplify this.","crm-domain.js; UAT-057","Remove Developer per owner direction; explicitly define Investor/Other and whether Buyer/Seller roles are derived per Lead instead."),
R("C-03","Preferred channel is stored but its processing effect is unclear","Implemented field; unresolved business rule","Phone, Email, WhatsApp and SMS are offered as preferred channels. CORE displays the value, but dev.158 does not consistently prove that tasks or dispatch always honor it.","Customer profile, follow-up context and communication preparation.","A mandatory preference can create false consent. A preferred channel must not override consent, restriction or connector availability.","Customer channel/preference → communication policy checks → permitted connector/draft → evidence.","WhatsApp and other providers may be disabled; consent and do-not-contact remain higher-order controls.","crm-domain.js; communication-domain.js; UAT-058","Decide whether optional, what it influences, fallback order, and how consent/restrictions override it."),
R("C-04","At least one email or phone is required","Implemented","Customer validation requires a usable email or phone; phone follows E.164 formatting.","Customer creation and contact maintenance.","This prevents non-contactable records but may block walk-in/referral Leads with incomplete details.","Captured identity → channel validation → Customer master → later verification/consent.","No implication that a supplied channel is verified or consented.","crm-domain.js","Approve incomplete-contact exception and verification requirements."),
R("C-05","Customer duplicate review can block Lead creation","Implemented","A pending duplicate-review Customer is treated as draft and cannot start a Lead until resolved.","Customer search/create and Lead capture.","This protects identity integrity but can delay response to a genuine enquiry.","New/matched Customer → duplicate review → resolved Customer → Lead.","Existing Customer selection should be preferred; merge policy needs owner confirmation.","crm routes/UI","Approve duplicate thresholds, SLA and emergency proceed-with-review path."),
R("C-06","Consent is not inferred from a preference or signature image","Approved governance principle","Consent must be represented by an executed, effective, versioned agreement with scope and permitted channels.","Outbound communications, proposals and channel dispatch.","A stored phone number or WhatsApp preference alone is not permission to communicate.","Agreement template/version → execution/effective dates → consent scope/channels → communication policy.","Expiry, restrictions and do-not-contact can still block dispatch.","DECISIONS; governance routes; communication-domain.js","Approve consent scopes, lawful-basis exceptions, retention and withdrawal processing."),
R("C-07","Customer register pagination is incomplete","Confirmed regression defect","The API supports page and pageSize, but the main Customer UI fixes pageSize=10, sends no page number and offers no navigation; it shows only page 1.","Customer main tab search and browse.","Users can incorrectly conclude a Customer does not exist, then create duplicates. Lead capture's separate search correctly pages through up to 100 at a time.","Main tab filter → /crm/contacts?pageSize=10 → first page only. Lead picker → repeated paged search → full permitted matches.","Filtering may bring a record into page 1, but browse completeness remains false.","public/app.js; routes/crm.js; UAT-059","Regression: restore complete server-side pagination/search and add regression tests across all registers."),
R("C-08","KYC/document access is narrower than Customer visibility","Implemented","A user may see a Customer register row while KYC and private documents remain subject to separate maintenance/review/file rules.","Customer detail and document download/preview.","Broad Customer visibility must not be mistaken for authority to inspect identity evidence.","Customer scope → detail projection; document request → classification/entity access check → no-store view/download → audit.","PDF can be viewed inline; other types use download.","files-proposals routes; crm routes","Confirm document classifications, reviewer roles and audit/retention expectations."),
]),
("D", "Lead capture, routing, SLA and qualification", [
R("D-01","Lead Business Type combines three different dimensions","Confirmed defect — high priority","Sale, Rental, Off-plan and Commercial are mutually exclusive, although they represent transaction mode, market stage and segment.","Lead capture, routing, qualification-model coverage, website AI intake, reports and downstream transaction mapping.","The same real request cannot be expressed coherently, for example buy an off-plan residential unit or lease a ready commercial unit.","Business Type → routing/model/report filters → Opportunity transaction selection; information is lost at capture.","Owner requested separate Lead requirement dimensions; the separate specification document remains under review.","crm-domain.js; UAT-062; Lead Classification Business Rules Review v3","Replace only after owner approves exact values, combinations, migration and downstream mapping."),
R("D-02","Supply-side Leads are forced through demand-side fields","Confirmed defect — high priority","Seller/Landlord Leads currently require budgets, preferred Areas, primary routing Area and a property-that-prompted-query pattern designed for buyers/tenants.","Lead capture and initial structured requirements.","Agents enter fabricated values or cannot capture a genuine instruction to sell/lease owned Inventory.","Current: Customer → demand fields → Lead. Required design: objective determines demand vs supply → supply links/creates Inventory → Area/property facts derive from Inventory.","Inventory may not yet exist; owner must decide staged capture and minimum authority evidence.","UAT-063; routing-service.js; Lead review document","Owner has directed a supply-side redesign; confirm exact fields, Inventory timing and routing before implementation."),
R("D-03","Lead stage transitions are a fixed state machine","Implemented implicit rules","New→Contacted/Lost; Contacted→Qualified/Lost; Qualified→Viewing/Negotiation/Lost; Viewing→Qualified/Negotiation/Lost; Negotiation→Viewing/Won/Lost; Lost→New; Won is terminal.","Lead detail, activities, dashboards and close/reopen behavior.","Some normal journeys cannot skip stages. Reopening Lost to New discards no history but restarts operational interpretation.","Current stage + requested stage → transition validator → stage/history update → dashboard/queue changes.","Opportunity has a separate lifecycle; Lead stage is not a substitute for transaction stage.","crm-domain.js; DECISIONS","Approve permitted skips, reopen authority and synchronization rules with Opportunity/Deal."),
R("D-04","A Call automatically advances New to Contacted","Implemented implicit automation","Recording a Call on a New Lead changes its stage to Contacted.","Lead activity capture and SLA reporting.","A failed/no-answer call may overstate actual contact unless outcome semantics are enforced.","New Lead + Call activity → automatic stage transition → history/SLA recalculation.","Other activities do not necessarily cause the same change.","crm-domain.js; crm routes","Decide which call outcomes qualify as Contacted and whether agent confirmation is required."),
R("D-05","Lost requires a reason and can reopen to New","Implemented","A Lead cannot close Lost without a reason; Lost may transition back to New.","Lead closure, pipeline reporting and reactivation.","Reason quality drives loss analytics. Reopening to New may create misleading age/SLA unless original dates remain visible.","Close request + reason → Lost/history/closed time; reopen → New/history while preserving prior closure.","Won is terminal in the Lead state machine.","crm-domain.js","Approve controlled loss reasons, free-text rules, reopen roles and SLA behavior."),
R("D-06","Default business calendar is Mon–Fri, 09:00–18:00 Dubai","Implemented fallback","When no maintained calendar applies, business-time calculations use Monday–Friday 09:00–18:00 at UTC+4.","Assignment acceptance, first-contact SLA and due-time calculations.","Unconfigured calendars silently impose hours that may not match brokerage operations or UAE working patterns.","Event timestamp → configured calendar or fallback → business-minute deadline → queues/escalation.","Other domains also encode weekends; consistency must be governed centrally.","crm-domain.js","Approve workweek, holidays, Ramadan hours, timezone and fallback policy."),
R("D-07","Qualification temperature sets response targets","Implemented defaults","Hot=15 minutes, Warm=240, Cold=1,440 and Unassessed=240 for response guidance.","Lead prioritization, SLA/agent dashboards and follow-up cues.","A score label directly changes urgency. Unassessed is treated like Warm, which may or may not be intended.","Qualification assessment/override → temperature → target response minutes → due/risk display.","Configured routing/assignment deadlines may coexist; precedence is not owner-approved.","crm-domain.js","Approve targets by objective/segment/source and precedence against routing SLAs."),
R("D-08","Qualification excludes sensitive attributes and permits reasoned override","Implemented governance","Sensitive personal/social factors are blocked. Missing required or reject factors can block a result; Hot/Warm/Cold may be overridden with a reason.","Qualification-model maintenance and Lead assessment.","This supports fair, explainable qualification but overrides can weaken consistency without review analytics.","Active model → allowed responses → factor contributions → score/band → optional reasoned override → immutable assessment.","Overrides do not repair missing mandatory evidence unless the route explicitly permits it.","crm-domain.js","Approve protected-factor policy, override roles, monitoring and appeal/correction process."),
R("D-09","Website AI intake only accepts two current Business Types as determined","Implemented implicit rule","For supported AI forms, Sale and Off-plan may be accepted as determined; Rental and Commercial are routed to review_required.","Website AI lead intake and assignment readiness.","Rental/Commercial enquiries receive systematically different treatment due to the mixed classification field, not necessarily risk or confidence.","AI payload → schema/form validation → derived business type → determined or review_required → Lead processing.","Only named AI form versions are accepted.","website-ai-routing.js","Reconfirm after Lead classification redesign; define confidence and human-review rules explicitly."),
R("D-10","Lead register is limited to the first ten results","Confirmed analogous regression","The Lead UI sets pageSize=10; the API returns no page navigation in this register path.","Main Lead pipeline browsing/search.","Agents can miss older matching Leads and duplicate work or misread pipeline counts.","Filters → /crm/leads?pageSize=10 → newest matching ten → UI count without navigation.","Search can change which records fall into the first ten but cannot make browse complete.","public/app.js; routes/crm.js; UAT-060","Implement true pagination/infinite loading and a shared regression test for all registers."),
]),
("E", "Inventory, parties, verification and availability", [
R("E-01","Inventory party is not automatically a Customer","Implemented","Owner/party roles include Seller, Landlord/Lessor, Developer and Authorized Representative; party types include person, company, external broker and agency. Evidence/source are required.","Inventory creation, authority and Deal party preparation.","A transaction party can be governed without polluting the Customer register, but deliberate linking/merge rules are required to avoid duplicates.","Party identity/source/authority evidence → Inventory party link → transaction representation/Deal party.","Customer creation remains a separate explicit action.","inventory-party-domain.js","Approve when to link/create Customer or partner organization, and survivorship rules."),
R("E-02","Inventory identity uses a five-part duplicate key","Implemented","Unit Reference + Building + Size + Community + Area form the duplicate identity. Incomplete identity is blocked.","Inventory creation and duplicate review.","Free-text Community/Building differences can defeat duplicate detection; minor size formatting can split the same unit.","Inventory facts → normalized composite → active/closed match search → block/reopen/review path.","An active duplicate is blocked; a matching closed record must be reopened rather than recreated.","inventory-duplicate-gate.js","Revisit after canonical Community/Building and define tolerance/alias handling."),
R("E-03","Suspected duplicates require a governed decision","Implemented","A reviewer must choose canonical/defer/continue as configured and give a meaningful reason; closed matches follow a Manager reopen approval/rejection path.","Inventory duplicate queue and reopen workflow.","This preserves one lifecycle per property but adds operational latency and reviewer dependency.","Duplicate candidate → reviewer decision/reason → canonical reuse, distinct continuation, defer or reopen → audit.","Active duplicates cannot be bypassed as ordinary new Inventory.","inventory-duplicate-gate.js","Approve reviewer roles, SLA and merge/reopen consequences."),
R("E-04","Verification and availability are separate concepts","Implemented but UI incomplete","Verification establishes trust/approval; availability establishes that the property is presently actionable. dev.158 stores availability confirmation/effective date and optional expiry.","Inventory review, cards, matching eligibility and publication readiness.","Showing only 'checked on' without an expiry leaves stale stock actionable unless freshness logic intervenes.","Creator submits → verification decision → availability confirmation/effective/expiry → eligibility checks and cards.","Missing explicit expiry can remain advisory; owner reported no field to maintain expiry (UAT-050).","inventory-verification-domain.js; migration 100; UAT-050","Approve who sets/extends expiry, default term, evidence and stale-stock behavior; add the missing UI control."),
R("E-05","Verification decisions are controlled and stateful","Implemented","Verification requests start only from unverified/expired; pending requests can be verified, returned or rejected. Exemptions can be exempted, returned or rejected, with reasons/evidence.","Inventory verification queue and review screen.","The decision changes whether Inventory can be promoted or published; returned/rejected must be intelligible to creator and checker.","Request + evidence/reason → pending queue → checker decision → verification status → eligibility/workflow.","Only pending items can be decided. User observed checker guidance is not role-specific (UAT-055).","inventory-verification-domain.js; UAT-055","Approve checker guidance, resubmission, segregation-of-duties and queue-return behavior."),
R("E-06","Verification currently offers an intermediate agent/custodian assignment","Implemented behavior rejected by owner","dev.158 permits assigning an eligible Listing/Sales Agent during verification and refers to a current custodian/responsible agent.","Inventory verification review and Inventory visibility.","The field creates unclear ownership: whether it controls use, approval, follow-up or only accountability. User could not see the assignment on the Inventory card.","Verification review → agent/custodian assignment → agent-scope logic; display/approval semantics are incomplete.","Owner explicitly directed removal: Listing Agent lists; checker verifies; Sales Agent selects available Inventory during Opportunity creation.","inventory-agent-governance.js; UAT-055/UAT-056","Treat as an approved product direction pending implementation and regression UAT; define any replacement accountability field separately."),
R("E-07","Verification completion does not return to the queue","Observed workflow defect","After deciding a verification item, dev.158 remains on the detailed record rather than returning to the verification queue.","Manager/checker review workflow.","High-volume review becomes slower and the reviewer may repeat or overlook items.","Queue → detail → decision → current detail remains; expected → queue refresh/next item.","A confirmation summary may still be needed before navigation.","UAT-054","Implement post-decision return/next-item behavior and verify queue count/state."),
R("E-08","Inventory availability freshness uses seven days for publication readiness","Implemented implicit threshold","Publication readiness expects availability confirmation within the last seven days, alongside approved workflow, trusted verification, core fields and approved media.","External-listing readiness and stock quality.","A fixed seven-day cadence creates workload and may be inappropriate by asset/mandate type.","Availability event time → freshness calculation → readiness blocker/advisory → publication workflow.","Property Finder remains disabled; this readiness rule still affects internal interpretation.","inventory-domain.js","Approve freshness by inventory type, explicit expiry precedence and reminder/escalation."),
R("E-09","Inventory register is limited to the first ten results","Confirmed analogous regression","The Inventory UI sets pageSize=10 and lacks a page-control path for the main register.","Inventory browse/search and operational review.","Users can miss approved stock and misinterpret totals, producing false 'not available' conclusions.","Filters → /listings?pageSize=10 → first ten sorted records → cards/count.","Opportunity pickers may use different page sizes; inconsistent search behavior increases confusion.","public/app.js; routes/listings.js; UAT-061","Use shared server-side pagination/search components and full-register regression coverage."),
R("E-10","Property and funding vocabularies are source-code controlled","Implemented implicit lists","Property types include common residential/commercial types and Bulk Deal. Payment plans include Cash, Mortgage, Developer Plan and Post-handover; funding maps cash/mortgage/mixed/unknown.","Inventory capture, Lead requirements and customer-fit scoring.","Unapproved labels and mappings influence matching and reports. Bulk Deal additionally requires at least two complete unique units.","Selected values → stored Inventory/requirements → compatibility/scoring/report grouping.","Source-code lists are not fully owner-maintained masters in dev.158.","inventory-domain.js","Approve complete catalogues, synonyms, combination rules and admin ownership."),
R("E-11","Price and availability history is immutable evidence","Implemented","Price/availability changes create events with evidence references/digests and reviewer context; conflict correction requires meaningful reasons.","Inventory audit trail, current-state derivation and dispute review.","The current card is a projection; historical events remain the evidence. Silent overwrite is not allowed.","New event + evidence → immutable history → effective current projection → eligibility/cards.","Corrections add events rather than delete facts.","inventory-history-domain.js","Confirm evidence classes, reviewer roles and retention."),
R("E-12","Authorized partner-org version may be activated by its creator","Implemented dev.158 correction","Migration 100 removed a creator-versus-verifier constraint for authorized partner organization versions while preserving fact immutability.","Developer/partner organization governance.","This relaxes strict four-eyes control for authorized roles and must be a deliberate governance decision.","Draft organization version → authorized activation by same/different user → immutable active facts → relationships/Inventory use.","Other review workflows may still prohibit self-approval.","100_dev158_uat040_048_operational_corrections.sql","Confirm precisely which roles and evidence classes permit same-user activation."),
]),
("F", "Matching, eligibility and Opportunity formation", [
R("F-01","Operational eligibility and customer fit are combined in one evaluator","Implemented; owner has challenged hard customer-fit exclusions","The evaluator returns eligible, needs_clarification or excluded. Operational status and customer-requirement comparisons both influence whether Inventory can be selected/promoted.","Lead-to-Opportunity starting Inventory, matching runs and shortlist promotion.","A property can be operationally valid yet blocked from discussion because a customer-fit value is treated as eligibility rather than ranking.","Lead requirement + Inventory snapshot + declarations/assessments → evaluator → state/reasons/score → selector/promotion.","Manual browsing may show the record while creation rejects it, producing an unexplained contradiction.","inventory-eligibility-domain.js; UAT-052","Split operational eligibility from advisory fit ranking, subject to explicit owner-approved safety/compliance hard gates."),
R("F-02","dev.158 hard-excludes price above maximum budget","Implemented defect/regression — owner rejected","If asking price exceeds the Lead maximum budget, dev.158 returns excluded. Price below the minimum remains eligible as affordable.","Opportunity creation Inventory picker and governed matching.","Real buyers can increase budget after seeing a property; the hard block prevents legitimate agent/customer discussion.","Budget max + asking price → exclusion reason → selector may display then creation revalidates and rejects.","A later local dev159 correction exists outside the deployed dev.158 baseline and is not treated as passed or deployed.","inventory-eligibility-domain.js; UAT-052","Owner directed all customer-fit criteria to ranking only. Implement, deploy and retest before marking passed."),
R("F-03","Operational hard exclusions in dev.158","Implemented; review list","Deleted Inventory, workflow not approved, untrusted verification, Closed/Sold/Rented, expired verification, expired availability and transaction-type mismatch are hard exclusions.","Matching, Opportunity creation and shortlist promotion.","These gates protect against using invalid or unavailable stock, but each must have visible reason and a governed recovery route.","Inventory state/evidence/transaction types → hard-gate checks → excluded reason codes → UI/action denial.","Missing status/transaction type becomes needs_clarification rather than excluded; owner may still revise transaction-type treatment.","inventory-eligibility-domain.js","Approve each hard gate, its recovery action, error wording and whether transaction mismatch is operational or ranking."),
R("F-04","Missing/must-have assessment produces needs_clarification","Implemented","Missing effective status/transaction types, unconfirmed must-haves or exclusions, and incomplete declaration evidence can make a candidate non-eligible pending clarification.","Governed matching and promotion.","A missing assessment can function like a hard block even when the property is reasonable, shifting workload to data completion.","Requirements/declarations/assessments → readiness checks → needs_clarification → no promotion until evidence is completed.","Availability confirmation missing/old can be advisory when no explicit expiry applies.","inventory-eligibility-domain.js","Decide which missing data blocks selection versus lowers confidence/ranking."),
R("F-05","Customer-fit score uses fixed weights and bands","Implemented implicit scoring model","Budget 25, Area/Community 20, Property Type 15, Bedrooms 15, Size 10, Funding/Payment 5, Timeline/Handover 5 and assessed preferences 5. Scores ≥80 Strong, ≥60 Partial, else Outside key requirements.","AI-assisted/governed matching evidence and candidate ordering.","Weights encode product strategy. Area and budget dominate; small changes around 60/80 change labels materially.","Comparable facts → per-factor assessment → weighted score → band/rank → agent shortlist decision.","The score should explain, not automatically decide, unless owner explicitly authorizes automation.","inventory-eligibility-domain.js","Approve weights, tolerances, bands, missing-data treatment and version governance."),
R("F-06","Matching run and decisions are immutable evidence","Implemented","Runs freeze requirement and Inventory facts; candidate decisions are shortlisted, rejected or deferred with controlled feedback. Promotion is limited to one through six properties and is idempotent.","Governed matching workspace and shortlist.","This allows later proof of what was considered, but reruns are required after material requirement or Inventory changes.","Current requirement/version + candidate snapshot → run → score/reasons → agent decision → shortlist/promotion → event history.","No duplicate promotion; exact run/candidate references are retained.","governed-matching-domain.js; inventory-eligibility-domain.js","Approve shortlist limit, rerun triggers and customer-visible explanation."),
R("F-07","Manual match requires availability confirmation and fit rationale","Implemented","An agent must select approved Inventory, record fit status/rationale and confirm likely availability before shortlisting manually.","Opportunity property selection outside an automated run.","Manual discretion is allowed but must leave an explainable record; the checkbox is not a substitute for an availability event.","Inventory selection → rationale/exception/likely-availability attestation → shortlist link → later viewing/offer.","A later eligibility recheck can still block stale/invalid stock.","matching-viewing-domain.js","Confirm minimum rationale, evidence and Manager-review triggers for exceptions."),
R("F-08","Opportunity creation requires governed representation context","Implemented","Paths are buyer-side, Inventory-side or dual. Buyer path requires a qualified Lead; Inventory path requires approved NYSA Inventory; dual requires both, agent identities, authority and conflict disclosure/evidence.","Lead conversion to Opportunity and party attribution.","The path determines which agent/authority facts are mandatory and how conflicts are governed.","Qualified Lead and/or approved Inventory → representation path → agents/authority/counterparty evidence → Opportunity.","External co-broker/buyer sources use transaction-only counterparties rather than silently creating Customers.","transaction-representation-domain.js","Approve path names, dual-agency policy, required evidence and external-party handling."),
R("F-09","Opportunity stages are independent of Lead stages","Approved design; transitions implicit","Opportunity stages are Requirements, Matching, Viewing, Offer, Negotiation, Booking, Closed Won and Closed Lost.","Opportunity journey, next actions and dashboards.","A Lead can remain at a different stage than its Opportunity unless synchronization is explicitly defined; reporting can diverge.","Lead conversion → Opportunity stage machine → transaction events → separate Lead update/closure rules.","Closed states are terminal except governed recovery/closure processes.","opportunity-domain.js; DECISIONS","Approve cross-lifecycle synchronization and allowed stage skips/reversals."),
R("F-10","Opportunity transaction type repeats the mixed classification problem","Implemented implicit list","Opportunity transaction types are Sale, Rental, Off-plan and Commercial, again mixing transaction, stage and segment.","Opportunity creation, matching, Offer/Deal mapping and approval.","Even if Lead capture is corrected, downstream ambiguity remains unless Opportunity and Deal schemas are aligned.","Lead requirement dimensions → current single Opportunity type → eligibility/offer/deal-type mapping.","Deal later distinguishes commercial sale/rental, exposing the mismatch.","opportunity-domain.js; deal-domain.js","Include Opportunity/Deal migration in the classification redesign; no isolated dropdown fix."),
]),
("G", "Viewing, offers, negotiation, booking and closure", [
R("G-01","Viewing requires a shortlisted property and governed logistics","Implemented","A Viewing requires shortlisted Inventory, valid date/time/timezone, meeting point, instructions and no more than 20 attendees.","Viewing creation and diary integration.","The 20-person cap and required logistics are operational assumptions that may not fit launches/open houses.","Shortlist → Viewing schedule → diary/calendar attempt → attendance/outcome/feedback → follow-up.","Cancellation and no-show are distinct outcomes.","matching-viewing-domain.js","Approve attendee limit, timezone/calendar behavior and group-viewing exception."),
R("G-02","Completed Viewing requires outcome, feedback and follow-up","Implemented","Completion is blocked without outcome/feedback plus a dated next action.","Viewing completion and Offer readiness.","This improves discipline but can delay status updates when customer feedback is pending.","Viewing occurs → attendance/outcome/feedback → follow-up action/due time → completion → Offer gate.","Offer revision/sending/acceptance also relies on recorded Viewing feedback in current flow.","matching-viewing-domain.js; opportunity routes","Approve pending-feedback state and when Offers may proceed before formal feedback."),
R("G-03","Offer is versioned; terminal outcomes are immutable","Implemented","Purchase, Rental, Off-plan and Commercial Offers progress draft/sent/viewed/countered/accepted/rejected/expired/withdrawn. Revisions preserve history; rejected/withdrawn require reasons.","Offer preparation, negotiation and Booking.","A rejected Offer cannot be silently edited into a lower Offer; a new revision/Offer action must be explicit.","Draft terms → immutable revision → send/status events → counter/revise → acceptance or terminal outcome.","Revision number >1 requires a material-correction/revision reason.","offer-domain.js","Approve which changes require a revision versus a new Offer, and customer/counterparty evidence."),
R("G-04","Renegotiate-same-property action has no price-entry form","Confirmed UAT defect","After Customer rejection, the recovery action can be clicked but dev.158 exposes no form to enter a revised price/terms; visible alternatives focus on requirements or Inventory.","Negotiation recovery after rejected Offer.","The normal commercial path—lower price on the same property—is blocked, encouraging wrong requirement changes or Opportunity closure.","Rejected Offer → recovery choice → expected new governed revision form → send/review; current flow stops after choice.","The terminal rejected Offer should remain immutable; correction must create a new revision/event.","UAT-053; offer-domain.js","Add revised terms form with prior-offer comparison, reason, authority and full revision history; retest end to end."),
R("G-05","Offer numeric and validity constraints are fixed","Implemented","Amount must be positive; currency is a three-letter code; deposit is between zero and amount; validity must be future-dated.","Offer creation/revision.","The rules prevent nonsensical terms but do not define multi-currency conversion, rent frequency or staged off-plan schedules.","Terms → domain validation → immutable revision → status workflow.","Deal closing later uses the exact accepted Offer value.","offer-domain.js","Approve currency catalogue, rental/off-plan term model and rounding/tax treatment."),
R("G-06","Offer acceptance and Inventory reservation are atomic","Implemented","Accepting an eligible Offer and reserving its Inventory occur together with evidence. If another Opportunity reserves first, neither change is committed.","Booking/reservation creation.","This prevents accepted-but-unreserved inconsistency and enforces exclusivity under concurrency.","Accepted exact Offer revision + evidence → database transaction/lock → Offer accepted + seven-day reservation or full rollback.","Evidence must be PDF/JPEG/PNG up to 10 MB in the UI path.","booking-domain.js; offer-ui.js; UAT concurrency tests","Approve evidence formats/size and behavior when no exclusive reservation is commercially required."),
R("G-07","Reservation duration is exactly seven days","Implemented implicit default","A new reservation expires exactly seven days after confirmation.","Offer acceptance, Booking and Inventory blocking.","A universal period may not fit rentals, off-plan launches or developer policies.","Booking start → system expiry +7 days → active reservation → expiry/release/extension.","Manager may extend only before expiry, with reason, to a maximum cumulative 14 days.","booking-domain.js; offer-ui.js","Approve default/maximum by deal type, working vs calendar days and reminder cadence."),
R("G-08","Manager controls reservation extension/release/cancel/expiry","Implemented","Only the maintained Manager for the Opportunity can govern the active reservation, subject to status/time/version rules.","Booking actions and Inventory availability.","This centralizes stock control but can stall transactions if Manager coverage/delegation is absent.","Active reservation → Manager action + reason/version → new expiry or terminal state → Inventory released/blocked.","Expired status can only be recorded after time; terminal states require reasons as applicable.","booking-domain.js; offer-ui.js","Approve delegation, out-of-hours coverage and automatic expiry processing."),
R("G-09","Inventory assignment uses a seven-day governed lifecycle","Implemented dev.158","A fresh assignment measures seven days; active duplicates are prevented. Manager extension can reach a maximum 14 cumulative days; delink adds an event without erasing creation history.","Inventory-to-Opportunity assignment/linkage.","Assignments create temporary accountability/exclusivity and must not become hidden ownership.","Opportunity/Inventory link → created event/expiry → optional Manager extension → delinked event → full history.","Non-Managers cannot extend; history preserves same actor and prior events.","migration 099; independently verified Section tests","Confirm distinction among shortlist, assignment and reservation, and whether all need separate expiries."),
R("G-10","Deal type determines mandatory parties","Implemented","Sale requires Buyer+Seller; Rental requires Tenant+Landlord; Off-plan requires Buyer+Developer; commercial sale/rental use corresponding pairs.","Deal preparation and closing gates.","Misclassified transaction type produces wrong party and document requirements.","Accepted Opportunity/Offer → Deal type → required party roles → party links/evidence → approval/close.","Each transaction party must be exactly one of Customer, Company or transaction-only counterparty.","deal-domain.js","Align with classification redesign and approve party substitution/representative rules."),
R("G-11","Commercial Deal approval is Director-only","Implemented implicit authority rule","Manager can approve a managed-team non-commercial Deal. Commercial Deals require Director approval; Director can approve any Deal within policy.","Deal approval before closure.","Commercial transactions have a higher authority threshold, potentially creating a bottleneck.","Deal type/team → approval route → Manager or Director decision → closure readiness.","Administrator does not automatically replace the required commercial approver.","crm-policy.js; deal-domain.js","Approve monetary/risk thresholds, delegation and whether all commercial cases require Director."),
R("G-12","Close Won/Lost has evidence and downstream effects","Implemented","Won requires confirmation, evidence, note and non-future actual time. Lost requires controlled reason/explanation/evidence plus explicit confirmation that Deal and Opportunity close and reservation releases.","Deal completion and administrative closure.","Closure affects pipeline, Inventory and audit records; casual closing is deliberately prevented.","Closure request → terms/reservation/parties/checklist/approval/document gates → Deal and Opportunity terminal events → Inventory/reservation effects.","Administrative closure is Manager-authorized and reason-controlled; prior tests proved blocks and persisted reason.","deal-domain.js; opportunity routes; dev158 business-condition tests","Approve loss taxonomy, reversal/correction path and reconciliation with Lead stage."),
]),
("H", "Documents, communications, finance and workforce", [
R("H-01","Official document rules can block approval/closure","Implemented","Requirement versions map deal/document context to required or advisory evidence at before-pending-approval, before-approval and before-close-won gates.","Inventory external listing and Deal compliance.","A configuration change can block transactions; exact evidence/version/fingerprint makes the decision auditable.","Active rule/version + case context → requirement set → immutable PDF evidence → independent review → gate satisfied/blocked.","Advisory items do not block. Expired or mismatched context can invalidate evidence.","document-compliance-domain.js","Approve each required document matrix, issuer, expiry, exception and reviewer route."),
R("H-02","Compliance reminders use fixed calendar-day offsets","Implemented default","Reminder offsets default to 0, 7, 14 and 30 calendar days.","Document expiry/follow-up tasks.","Calendar-day reminders may land on non-working days and may be too late for critical permits.","Evidence/rule expiry → offset calculation → task/reminder → completion/reuse.","The business calendar used for Lead SLA is not automatically applied.","document-compliance-domain.js","Approve offsets by document type and working/calendar-day treatment."),
R("H-03","Marketing material has independent approval and dependency validity","Implemented","Material is versioned, channel/region governed and approved by assigned Manager/Director; Manager/Director cannot self-approve, while Administrator may review directly. Default validity is 30 days, bounded by dependencies.","Marketing collateral and channel release.","A previously approved asset becomes stale when media rights, permit, official evidence, campaign or document changes/expires.","Draft material + exact document/media/evidence/permit → preflight → routed review → release window → stale/expired on dependency change.","Approved release does not auto-extend beyond the earliest dependency expiry.","marketing-material-compliance-domain.js","Approve channels, approver routes, 30-day default and emergency withdrawal/reissue."),
R("H-04","Customer shortlist response does not mutate business state automatically","Implemented","A Customer response such as not suitable is evidence only; it does not automatically change Inventory, Opportunity, send content or alter requirements.","Proposal/shortlist feedback.","Human review prevents overreaction but requires a clear next-action queue.","Shared shortlist → response event → deterministic proposed next action → agent decides requirement/property/lifecycle update.","Maximum shortlist is six properties.","customer-shortlist-domain.js; broker-next-action-domain.js","Approve which responses may automate tasks versus require agent confirmation."),
R("H-05","Broker next actions use fixed response deadlines","Implemented implicit defaults","Viewing=2h; interest/info=4h; more options/not suitable=8h; confirmed requirement change=4h.","Post-shortlist response queue.","Uniform deadlines may not reflect customer priority, working hours or team capacity.","Response code/time → proposed action + due time → queue → agent completion.","No automatic assignment, send or lifecycle mutation.","broker-next-action-domain.js","Approve deadlines, business-time calendar and escalation."),
R("H-06","Diary range and calendar behavior are constrained","Implemented","Diary queries cover at most eight days; due-now is ±30 minutes; overlaps are conflicts. Only Meetings/Viewings are calendar candidates, and provider status may remain not sent.","My Day/diary and external calendar preparation.","Users cannot treat the diary as a complete long-range calendar. Disabled provider integrations leave internal and external calendars unsynchronized.","Activities/tasks → diary range/priority/conflict → optional calendar connector → provider evidence.","Calendly and Microsoft 365 are disabled in dev.158.","diary-domain.js; manifest/.env example","Approve range, conflict tolerance, eligible activity types and connector reconciliation."),
R("H-07","WhatsApp dispatch is policy-gated and connector-disabled by default","Implemented boundary","The communication scaffold permits controlled purposes/channels only after actor, consent, restriction and subject checks. Disabled connector state blocks dispatch and stores references/digests rather than secret/private payloads in evidence.","Transactional share/service follow-up communication.","A prepared message is not proof of delivery; users must see disabled/failed/provider states clearly.","Communication intent → policy/consent/restriction → connector enabled check → dispatch/idempotency → provider/replay evidence.","Credentials, phone numbers and message content are prohibited from evidence envelopes.","communication-domain.js; deployment manifest","Approve supported channels/purposes, retention, templates and fallback procedure before enabling any provider."),
R("H-08","Commission calculation uses explicit slabs, splits and receipt events","Implemented","Slabs are contiguous from zero with an open final band; payout can be attained or progressive. Originating+servicing split must equal 100%. Receipt reversals reference receipts and cannot exceed them.","Commission expectation, realization and payout readiness.","Configuration determines agent earnings and liability. Reversal controls prevent negative/untraceable realization.","Deal value/terms → expected commission max(percent, minimum) → receipts/reversals → split/slab calculation → payout release.","Referral handling and minimums affect the result; tax/VAT treatment needs owner confirmation.","commission-payout-domain.js","Approve plans, thresholds, referral/VAT, rounding, effective dating and dispute adjustments."),
R("H-09","Payout release target is three working days after receipt","Implemented implicit SLA","The payout deadline is calculated three working days after receipt, using Saturday/Sunday as weekends and Asia/Dubai.","Commission payout queue.","This creates an obligation-like operational target and a calendar assumption that may conflict with company/bank holidays.","Receipt event → working-day calendar → release deadline → due/overdue queue.","Holiday maintenance is not proven in this rule.","commission-payout-domain.js","Approve SLA, workweek/holidays, partial receipts and approval dependencies."),
R("H-10","Leave approval and balance rules are fixed","Implemented","Leave needs active employment/reporting line/policy, at least 0.5 working day and a reason of at least 10 characters. Manager leave routes to Director; others to reporting Manager; self-approval is forbidden. Decision due is 1–10 working days; negative balance only when policy allows.","Agent leave request, task routing and capacity.","Missing reporting-manager data blocks submission; the encoded weekend pattern must match the corporate calendar.","Draft → working-unit/balance calculation → derived approver/task → decision → balance/history.","Half-days are supported; resubmission uses approval cycles.","agent-leave-domain.js","Approve workweek/holidays, leave types, balance rules, delegation and SLA."),
]),
("I", "Dashboards, reporting and integration boundaries", [
R("I-01","Dashboard role mapping has a fallback Agent view","Implemented","Admin/Director map to Executive, Manager to Manager, Listing Agent to Listing, Accountant to Accounting and all other recognized/internal users fall to Agent.","Home dashboards and KPI cards.","An unexpected role may receive the Agent view without an explicit error, hiding a configuration problem.","Authenticated role → dashboard family → scoped queries/proxies → cards/queues.","Read scope and dashboard scope can differ.","dashboard-domain.js","Approve explicit mapping for every role and reject unknown roles rather than silently fallback."),
R("I-02","Dashboard KPIs include unapproved proxy thresholds","Implemented and often labeled as assumptions","Examples include stale Lead after 7 days, stale Inventory after 30, availability current within 7, SLA risk within 60 minutes and team capacity pressure at 10+ open Leads.","Executive/Manager/Agent/Listing dashboards.","Proxy values can drive management decisions even when they are not contractual KPIs.","Operational timestamps/counts → fixed threshold → card label/risk state → manager action.","Some metrics are explicitly unavailable or labeled proxy/assumption.","dashboard-domain.js","Approve every KPI definition, denominator, scope, threshold and effective date before treating as performance measures."),
R("I-03","Queue age is a display calculation, not a business deadline","Implemented correction","dev.158 formats queue age rather than exposing raw minute values; age alone does not define breach unless paired with a configured SLA.","Review/assignment/verification queues.","Users may still interpret old age as non-compliance without a separate due-at rule.","Created/queued time → elapsed duration formatting → queue display; optional due time determines breach.","UAT-045 correction addressed formatting only.","UAT-045; dashboard/UI","Keep age and SLA status visually distinct and define queue-specific deadlines."),
R("I-04","Reports use operational source data and fixed result caps","Implemented implicit behavior","Several report/detail feeds cap recent movements/calls/closures/documents at 100 rows.","Reports, Lead/Customer history summaries and dashboards.","Large populations can appear complete when they are only the most recent 100 unless the UI labels the cap.","Scoped query → sort → LIMIT 100 → rendered report/summary.","Aggregate counts may be complete while detail lists are capped.","routes/crm.js","Approve pagination/export strategy and mandatory truncation disclosure."),
R("I-05","Property Finder is excluded and disabled","Deployment boundary","Sandbox and production read/create/publish flags are off. Property Finder was not targeted during dev.158 deployment.","Portal import/publication code paths only; no live operational flow.","Internal fields must not be treated as PF-approved or successfully mapped. Enabling later requires a separate governed readiness/UAT/deployment decision.","Current: Inventory remains internal → PF connector rejects/does nothing. Future: governed location/media/permit mapping → controlled preflight → approved external action.","No credentials, live listing mutations or credits were used in this review.","deployment manifest; .env.example; baseline evidence","Retain disabled until canonical locations, compliance mapping, ownership and explicit activation approval are complete."),
R("I-06","Microsoft 365 Email and Calendly are disabled","Deployment boundary","Both providers are disabled in dev.158. Internal activities/tasks may exist without external send/calendar evidence.","Email/calendar integration and diary.","Users must not assume a CORE record created an email or calendar event.","Internal intent/activity → connector enabled check → disabled/provider state → visible evidence.","No external-service change is authorized by this register.","deployment manifest; .env.example","Define enablement prerequisites, consent, reconciliation, failure handling and support ownership."),
R("I-07","Integration evidence must be idempotent and privacy-minimized","Implemented governance pattern","Provider callbacks use signature/replay/idempotency controls; evidence favors opaque references/digests over secrets or private payloads.","Communication and future external connectors.","Auditability is retained without spreading credentials or customer content through logs/evidence.","Outbound request/intent → idempotency key → provider → verified callback → deduplicated event/evidence.","Connector-specific schemas still require security/privacy review before activation.","communication-domain.js; integration modules","Adopt as a mandatory integration standard and approve retention/access controls."),
R("I-08","This register is evidence-based, not a claim of exhaustive business approval","Document control","Rules were derived from the exact deployed dev.158 runtime package, migrations, requirements/decision documents, automated evidence and observed UAT defects. Later local dev159 work is excluded.","Owner review, change control and UAT planning.","A rule's existence in code proves current behavior, not business approval. A suggestion proves neither implementation nor acceptance.","Evidence → classified rule → owner decision → approved specification/change → test → deployment → observed retest.","New paths/data may reveal additional implicit behavior; maintain this as a versioned register.","dev.158 manifest and SHA-256; UAT matrix; cited source files","Approve a recurring owner-review and release-gate process for additions/changes to business rules."),
]),
]

status_colors={"Approved design decision":PALE_GREEN,"Approved model":PALE_GREEN,"Implemented":PALE_BLUE,"Deployment boundary":LIGHT,"Document control":LIGHT}

doc=Document(); sec=doc.sections[0]
sec.top_margin=Inches(0.8); sec.bottom_margin=Inches(0.75); sec.left_margin=Inches(0.85); sec.right_margin=Inches(0.85); sec.header_distance=Inches(0.35); sec.footer_distance=Inches(0.35)
styles=doc.styles; normal=styles["Normal"]; normal.font.name="Calibri"; normal.font.size=Pt(10.5); normal.font.color.rgb=RGBColor.from_string(INK); normal.paragraph_format.space_after=Pt(5); normal.paragraph_format.line_spacing=1.12
normal._element.rPr.rFonts.set(qn("w:ascii"),"Calibri"); normal._element.rPr.rFonts.set(qn("w:hAnsi"),"Calibri")
for name,size,color,before,after in (("Heading 1",16,BLUE,16,8),("Heading 2",13,BLUE,12,6),("Heading 3",11.5,DARK,8,4)):
    s=styles[name]; s.font.name="Calibri"; s.font.size=Pt(size); s.font.bold=True; s.font.color.rgb=RGBColor.from_string(color); s.paragraph_format.space_before=Pt(before); s.paragraph_format.space_after=Pt(after); s.paragraph_format.keep_with_next=True
for style_name in ("List Bullet","List Number"):
    s=styles[style_name]; s.font.name="Calibri"; s.font.size=Pt(10.5); s.paragraph_format.space_after=Pt(2)
header=sec.header.paragraphs[0]; run(header,"NYSA CORE | Application-Wide Implicit Business Rules Register | dev.158",True,size=8.5,color=MUTED)
footer=sec.footer.paragraphs[0]; page_field(footer)

p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(22); p.paragraph_format.space_after=Pt(7); run(p,"NYSA CORE",True,size=12,color=BLUE)
p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(5); run(p,"Application-Wide Implicit\nBusiness Rules Register",True,size=24,color=NAVY)
p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(18); run(p,"Cumulative CRM Test deployment 2.1.0-dev.158",size=14,color=MUTED)
field(doc,"Document status","DRAFT FOR OWNER REVIEW — no new business decision inferred")
field(doc,"Evidence baseline","Exact deployed package: nysa-core-consolidated-crm-test-dev158.zip")
field(doc,"Verified package SHA-256","5b6a50ec7bbc13fb7583c9247187fd1fdd09c29870525e508fbeaf8bb98bb8ce")
field(doc,"Latest migration","100_dev158_uat040_048_operational_corrections.sql (100 migrations)")
field(doc,"Prepared","21 August 2026")
note(doc,"No-assumption control","This document separates implemented behavior, approved design decisions, observed defects, deployment boundaries and unresolved owner decisions. A current rule is not automatically a correct rule. A suggestion is not an approval. No code change, migration, data mutation, external-service action or deployment is authorized by this document.",PALE_GOLD)

doc.add_heading("How to use this register",level=1)
doc.add_paragraph("Review each rule's current behavior and business implication, then record a deliberate owner decision. Where the owner has already given explicit direction during UAT, that direction is described as such but remains pending implementation and CRM Test retest unless stated otherwise.")
for x in ["KEEP — current rule is approved as written.","CHANGE — replace with an approved rule/value set and effective date.","REMOVE — retire the rule and define migration/history treatment.","CLARIFY — retain temporarily but add wording, evidence or recovery guidance.","DEFER — name the owner, interim control and decision date."]:
    bullet(doc,x)

doc.add_heading("Evidence and scope",level=1)
doc.add_paragraph("The review covers the exact dev.158 package runtime, its 100 migrations, product/data/permission/decision documents, cumulative UAT matrix and the user-observed dev.158 issues through UAT-063. It does not treat later dirty-worktree or dev159 changes as deployed. It does not inspect or disclose live credentials or private owner/contact/authority data.")
note(doc,"Meaning of status labels","Approved design decision = explicitly documented prior decision. Implemented = code-enforced behavior, whether approved or not. Confirmed defect/regression = user-observed or evidenced divergence. Deployment boundary = intentionally disabled/excluded. Owner direction = explicitly stated desired behavior, still requiring implementation and retest.",PALE_BLUE)

doc.add_heading("Executive decision agenda",level=1)
agenda=[
("1","Lead classification","Split objective/transaction/market-stage/segment and redesign seller/landlord capture.","D-01, D-02, F-10, G-10"),
("2","Customer and organization identity","Remove Developer from Customer roles; define Investor/Other and preferred-channel effect.","B-07, C-02, C-03"),
("3","Inventory masters and accountability","Govern Community/Building; remove verification-stage custodian; define expiry maintenance.","B-08, E-04–E-07"),
("4","Eligibility versus fit","Retain approved/available/compliance gates; move customer affordability/preferences to explained ranking.","F-01–F-05"),
("5","Visibility and search","Approve role read scopes and correct Customer/Lead/Inventory pagination.","A-03, C-07, D-10, E-09"),
("6","Commercial recovery","Provide same-property revised Offer terms after rejection.","G-03–G-05"),
("7","Time and KPI defaults","Approve business calendars, 7/14-day periods, response targets and dashboard proxy thresholds.","D-06–D-07, E-08, G-07–G-09, H-05, H-09–H-10, I-02"),
("8","External boundaries","Keep PF/M365/Calendly/WhatsApp providers disabled until separate enablement controls are approved.","H-06–H-07, I-05–I-07"),
]
t=doc.add_table(rows=1,cols=4); t.alignment=WD_TABLE_ALIGNMENT.LEFT; table_widths(t,[600,1900,5100,1760]); headers=["#","Decision area","Business question","Rule refs"]
for i,h in enumerate(headers): shade(t.rows[0].cells[i],NAVY); run(t.rows[0].cells[i].paragraphs[0],h,True,size=9.5,color=WHITE)
for row in agenda:
    cells=t.add_row().cells
    for i,val in enumerate(row): run(cells[i].paragraphs[0],val,size=9.2); cells[i].vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.TOP
table_widths(t,[600,1900,5100,1760])

doc.add_heading("End-to-end information flow",level=1)
for text in [
"Demand path: Customer → Lead → routing/assignment/SLA → qualification + versioned requirements → Opportunity → matching/shortlist → Viewing → Offer revisions → Booking/reservation → Deal → documents/approval → close.",
"Supply path in dev.158: Customer/party → Lead fields designed mainly for demand → Inventory party/authority → Inventory draft → duplicate gate → verification → availability → matching/assignment/reservation → Deal. The seller/landlord Lead-to-Inventory design remains unresolved.",
"Governance path: versioned masters/rules → activation → frozen rule/version references on transactions → audit/history → later rule version without rewriting prior evidence.",
"Integration path: internal intent → policy/consent/readiness → connector enabled check → provider action/idempotency → callback/evidence. In dev.158, Property Finder, Microsoft 365 Email and Calendly remain disabled.",
]: bullet(doc,text)

doc.add_heading("Detailed rule register",level=1)
doc.add_paragraph("Each entry records the current dev.158 rule and the decision still required. Blank review lines are deliberate.")
rule_count=0
for code,title,rules in sections:
    doc.add_heading(f"{code}. {title}",level=1)
    for item in rules:
        rule_count+=1
        doc.add_heading(f"{item['id']}  {item['title']}",level=2)
        fill=PALE_RED if ("defect" in item['status'].lower() or "regression" in item['status'].lower() or "gap" in item['status'].lower() or "challenged" in item['status'].lower() or "rejected" in item['status'].lower()) else status_colors.get(item['status'],PALE_GOLD if ("review" in item['status'].lower() or "implicit" in item['status'].lower()) else PALE_BLUE)
        st=doc.add_table(rows=1,cols=2); st.alignment=WD_TABLE_ALIGNMENT.LEFT; table_widths(st,[1650,7710])
        shade(st.cell(0,0),NAVY); shade(st.cell(0,1),fill); run(st.cell(0,0).paragraphs[0],"STATUS",True,size=9,color=WHITE); run(st.cell(0,1).paragraphs[0],item['status'],True,size=9.2,color=NAVY)
        field(doc,"Current dev.158 behavior",item['current'])
        field(doc,"Where used",item['used'])
        field(doc,"Business implication",item['impact'])
        field(doc,"Data flow",item['flow'])
        field(doc,"Exceptions / failure behavior",item['exceptions'])
        field(doc,"Evidence",item['evidence'],color=MUTED)
        field(doc,"Owner decision required",item['decision'])
        p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(1); p.paragraph_format.space_after=Pt(4); run(p,"Owner record: ",True,color=NAVY); run(p,"Decision __________  Approved wording/value ______________________________  Owner/date __________________",italic=True,color=MUTED)

doc.add_heading("Controlled constants and thresholds requiring confirmation",level=1)
doc.add_paragraph("This appendix consolidates numeric/default assumptions already described in the register. It is a review checklist, not an approval.")
constants=[
("Session","7 calendar days","A-06"),("Password minimum","12 characters","A-07"),("Default working calendar","Mon–Fri, 09:00–18:00, Asia/Dubai","D-06"),("Response targets","Hot 15m; Warm 240m; Cold 1,440m; Unassessed 240m","D-07"),("Customer/Lead/Inventory main registers","10 rows, no complete navigation","C-07/D-10/E-09"),("Customer-fit score bands","Strong ≥80; Partial ≥60; otherwise Outside key requirements","F-05"),("Matching shortlist","1–6 properties","F-06"),("Viewing attendees","Maximum 20","G-01"),("Booking reservation","7 days","G-07"),("Booking/assignment maximum after extension","14 cumulative days","G-07/G-09"),("Availability freshness","7 days for publication readiness","E-08"),("Compliance reminders","0, 7, 14, 30 calendar days","H-02"),("Marketing material default validity","30 days; permitted 1–366","H-03"),("Shortlist response actions","2h/4h/8h/4h by response","H-05"),("Diary range / due now","8 days / ±30 minutes","H-06"),("Payout SLA","3 working days after receipt","H-09"),("Leave minimum / reason","0.5 day / 10 characters","H-10"),("Dashboard proxies","Lead 7d; Inventory 30d; SLA risk 60m; capacity ≥10","I-02"),("Recent-detail report caps","100 rows","I-04")]
t=doc.add_table(rows=1,cols=3); t.alignment=WD_TABLE_ALIGNMENT.LEFT; table_widths(t,[2800,5000,1560])
for i,h in enumerate(("Area","Current value","Rule")): shade(t.rows[0].cells[i],NAVY); run(t.rows[0].cells[i].paragraphs[0],h,True,size=9.5,color=WHITE)
for row in constants:
    c=t.add_row().cells
    for i,v in enumerate(row): run(c[i].paragraphs[0],v,size=9.2)
table_widths(t,[2800,5000,1560])

doc.add_heading("Recommended owner-review sequence",level=1)
for text in [
"First: decide the Lead/Opportunity transaction classification and seller/landlord flow, because they affect routing, requirements, matching, Deal types and reporting.",
"Second: decide Customer versus partner-organization roles, Community/Building masters and Inventory accountability/verification.",
"Third: approve operational hard gates separately from advisory customer-fit ranking, then retest Opportunity creation with above-budget and other near-fit properties.",
"Fourth: approve access/search completeness, time/SLA defaults, authority thresholds and dashboard KPIs.",
"Fifth: convert approved decisions into versioned specifications, migrations and automated/manual tests; deploy only through the normal approval process and mark passed only after CRM Test observation.",
]: bullet(doc,text)

doc.add_heading("Document control and evidence index",level=1)
doc.add_paragraph(f"Rule count: {rule_count}. Baseline: NYSA CORE 2.1.0-dev.158, deterministic package SHA-256 shown on the cover. Principal evidence includes PRODUCT_REQUIREMENTS.md, DATA_MODEL.md, PERMISSIONS_MATRIX.md, DECISIONS.md, CRM_TEST_DEV158_COMPLETE_MANUAL_UAT_ROUND.md, the cumulative dev.158 UAT matrix, migrations 001–100, and the cited dev.158 domain/route/UI files. No later local correction is represented as deployed or passed.")
note(doc,"UAT discipline","An implementation marked fixed locally remains unpassed until the user observes the corrected behavior in CRM Test. Issue, confirmed RCA, proposed solution, implementation status, deployment status and retest status must remain separate.",PALE_GOLD)

props=doc.core_properties; props.title="NYSA CORE Application-Wide Implicit Business Rules Register — dev.158"; props.subject="Owner review of implemented rules, implications, usage and data flows"; props.author=""; props.last_modified_by=""; props.keywords=""; props.comments=""
OUT.parent.mkdir(parents=True,exist_ok=True); doc.save(OUT); print(f"created {OUT} with {rule_count} rules")
