const view=document.querySelector('#view'),persona=document.querySelector('#persona');
const shell=(title,subtitle,body)=>`<section class="hero"><div><div class="eyebrow">NYSA CORE / MARKETING MATERIAL COMPLIANCE</div><h1>${title}</h1><p>${subtitle}</p></div><span class="badge">Synthetic review</span></section>${body}`;
const preflight=`<div class="grid"><div class="card"><small>Final Document</small><strong class="pass">Immutable v1</strong></div><div class="card"><small>Property Media</small><strong class="pass">3 approved</strong></div><div class="card"><small>Permit / disclosures</small><strong class="pass">Current</strong></div></div>`;
const author=()=>shell('Create marketing material','The Agent freezes the complete item and requests only its intended channels.',`<section class="panel"><h2>Property social creative</h2><div class="form"><div class="field"><label>Inventory</label><input value="INV-SYN-2408 · Marina Residence"></div><div class="field"><label>Campaign</label><input value="SUMMER-HOMES"></div><div class="field"><label>Region</label><input value="Dubai"></div><div class="field span3"><label>Headline</label><input value="Waterfront two-bedroom residence"></div><div class="field span2"><label>Final creative</label><input value="marina-social-v1.pdf · immutable Document v1"></div><div class="field"><label>Release window</label><input value="14 Aug – 30 Aug 2026"></div><div class="field span3"><label>Channels and approvers</label><input value="Instagram → Manager A · Print → Director B"></div></div>${preflight}<div class="actions"><button class="primary">Preflight passed · Submit</button></div><p class="note">Submission creates one governed Task for each selected approver. No external publication occurs.</p></section>`);
const queue=role=>shell(`${role} · My Task Queue`,`${role==='Manager'?'Team/listing-scoped':'Organization-wide'} approval authority.`, `<section class="panel"><h2>Review marketing material · MM-2026-SYN001</h2><table><tr><th>Channel</th><th>Inventory</th><th>Frozen content</th><th>Dependencies</th><th>Action</th></tr><tr><td>${role==='Manager'?'Instagram':'Print brochure'}</td><td>INV-SYN-2408</td><td>PDF v1 · SHA-256 frozen</td><td class="pass">All current</td><td><button class="primary">Review</button></td></tr></table><div class="timeline"><p><b>${role} approval</b></p><p>Approve, return or reject the assigned channel with a reason. Completing the generic Task cannot approve anything.</p><p>The author cannot approve their own submission.</p></div></section>`);
const register=()=>shell('Channel release register','Approval history is retained even when current eligibility later changes.',`<section class="panel"><table><tr><th>Material</th><th>Channel</th><th>Decision</th><th>Current eligibility</th><th>Effective until</th></tr><tr><td>MM-2026-SYN001<br><small>Marina social creative</small></td><td>Instagram</td><td>Manager approved</td><td class="pass">Released for use</td><td>25 Aug · media-rights expiry</td></tr><tr><td>MM-2026-SYN001</td><td>Print</td><td>Director approved</td><td class="block">Stale · permit changed</td><td>Approval retained</td></tr></table><p class="note">Released for use is an internal authorization only. No external publication occurs.</p></section>`);
const admin=()=>shell('Administration','Full Admin activates NYSA policy directly without maker-checker.',`<div class="grid"><div class="card"><small>Material type</small><strong>Property social post</strong><p>Property scope</p></div><div class="card"><small>Channel rule</small><strong>Instagram · Dubai</strong><p>Manager or Director</p></div><div class="card"><small>Permit rule</small><strong>Either authority</strong><p>Configured deliberately</p></div></div><section class="panel"><h2>No assumed legal rules</h2><p>The migration activates no RERA, permit or disclosure requirement. Full Admin configures only rules approved for NYSA operations.</p></section>`);
const renders={author,manager:()=>queue('Manager'),director:()=>queue('Director'),register,admin};
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));persona.textContent={author:'Marketing Agent · SALES AGENT',manager:'Team Manager · MANAGER',director:'Managing Director · DIRECTOR',register:'Director · ORGANIZATION VIEW',admin:'Full Administrator · ADMIN'}[button.dataset.view];view.innerHTML=renders[button.dataset.view]();});view.innerHTML=author();
