import { preparePartnerMasterDraft, decidePartnerDuplicateReview, verifyPartnerMaster, createPartnerRevision } from '/modules/partner-master-domain.js';

const now='2026-08-12T09:00:00.000Z',hash='a'.repeat(64),companyRef='NYSA-COMP-SYN-014';
const profiles={
  developer:{legalName:'Synthetic Developments LLC',tradeName:'Synthetic Developments',licenceRef:'DEV-LIC-SYN-001',licenceIssuer:'Synthetic Property Authority',role:'Developer'},
  external_agency:{legalName:'Synthetic Partner Brokerage LLC',tradeName:'Synthetic Brokerage',licenceRef:'',licenceIssuer:'',role:'Agency'},
  referral_partner:{legalName:'Synthetic Referral Network LLC',tradeName:'Synthetic Referral Network',licenceRef:'',licenceIssuer:'',role:'Referral partner'},
  service_provider:{legalName:'Synthetic Property Services LLC',tradeName:'Synthetic Services',licenceRef:'',licenceIssuer:'',role:'Service provider'}
};
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const human=value=>String(value||'').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
function inputFor(type,scenario){const p=profiles[type];return{partnerType:type,legalName:p.legalName,tradeName:p.tradeName,licenceRef:p.licenceRef,licenceIssuer:p.licenceIssuer,licenceExpiresAt:p.licenceRef?(scenario==='expired'?'2026-08-01T00:00:00.000Z':'2027-02-01T00:00:00.000Z'):null,serviceAreas:['Dubai'],projectReferences:type==='developer'?['PROJECT-SYN-001']:[],sourceEvidenceRef:'PARTNER-EVIDENCE-SYN-001',sourceEvidenceHash:hash,createdByRef:'ADMIN-SYN-1',now};}
function render(){
  const type=document.querySelector('#partner-type').value,scenario=document.querySelector('#scenario').value,p=profiles[type];
  const existing=scenario==='duplicate'?[{partnerRef:'NYSA-COMP-SYN-003',legalName:p.legalName,licenceRef:p.licenceRef,status:'active'}]:[];
  const prepared=preparePartnerMasterDraft(inputFor(type,scenario),existing);let current=prepared.draft,versions=current?[current]:[],reviewState='pending';
  if(scenario==='duplicate'&&current){current=decidePartnerDuplicateReview({draft:current,decision:'continue_new',existingPartnerRef:'NYSA-COMP-SYN-003',reason:'Evidence indicates a distinct legal organization',reviewerRef:'ADMIN-SYN-2',now});reviewState='duplicate_reviewed';}
  if(scenario==='verified'&&current){current=verifyPartnerMaster({draft:current,decision:'verified',reason:'Independent evidence review completed',verifierRef:'ADMIN-SYN-2',now});reviewState='active';}
  if(scenario==='revision'&&current){const active=verifyPartnerMaster({draft:current,decision:'verified',reason:'Independent evidence review completed',verifierRef:'ADMIN-SYN-2',now});const revision=createPartnerRevision(active,{tradeName:`${p.tradeName} Group`},'ADMIN-SYN-1','2026-08-12T10:00:00.000Z');versions=[active,revision];current=revision;reviewState='revision';}
  if(scenario==='expired')reviewState='expired';if(scenario==='own_draft')reviewState='own_draft';
  const active=current?.status==='active',usable=active;
  document.querySelector('#gate').innerHTML=`<article><div><span>Governed status</span><strong class="${active?'good':'bad'}">${esc(human(current?.status||'invalid'))}</strong></div><div><span>Eligible for new Inventory links</span><strong class="${usable?'good':'bad'}">${usable?'Yes · exact active version':'No · review incomplete'}</strong></div><small>Ordinary Company and Inventory maintenance remain available regardless of this status.</small></article>`;
  document.querySelector('#identity').innerHTML=current?`<article><div class="record-title"><div><span>Existing Company</span><strong>${companyRef}</strong></div><span class="pill">${esc(p.role)}</span></div><dl><div><dt>Legal name</dt><dd>${esc(current.legalName)}</dd></div><div><dt>Governed version</dt><dd>Version ${current.version}</dd></div><div><dt>Trade name</dt><dd>${esc(current.tradeName||'Not recorded')}</dd></div><div><dt>Source evidence</dt><dd>${esc(current.sourceEvidence.reference)}</dd></div><div><dt>Licence</dt><dd>${esc(current.licenceRef||'Not provided')}</dd></div><div><dt>Licence evidence</dt><dd>${esc(human(current.licenceEvidenceStatus))}</dd></div><div><dt>Licence issuer</dt><dd>${esc(current.licenceIssuer||'Not provided')}</dd></div><div><dt>Licence expiry</dt><dd>${esc(current.licenceExpiresAt?current.licenceExpiresAt.slice(0,10):'Not provided')}</dd></div></dl><div class="privacy-line"><span>Company contacts</span><strong>Hidden from governance review</strong></div></article>`:'<article class="empty">Invalid organization draft.</article>';
  const duplicate=prepared.duplicateCandidates[0];let review;
  if(reviewState==='active')review=`<article class="decision success"><strong>Verified by a second Administrator</strong><p>Admin Synthetic 2 reviewed the evidence. Version 1 is active and may be selected where compatible.</p><small>Creator: Admin Synthetic 1 · Verifier: Admin Synthetic 2</small></article>`;
  else if(reviewState==='expired')review=`<article class="decision danger"><strong>Activation blocked</strong><p>The supplied licence expired on 1 August 2026. The draft remains unavailable for Inventory linking.</p><small>Ordinary Company and Inventory maintenance are not blocked.</small></article>`;
  else if(reviewState==='own_draft')review=`<article class="decision danger"><strong>Separation of duties prevents approval</strong><p>Admin Synthetic 1 created this draft and cannot activate, reject, decide its duplicate review, or retire it.</p><small>A different Administrator must perform the decision.</small></article>`;
  else if(duplicate)review=`<article class="decision warning"><strong>Possible duplicate requires a decision</strong><p>${esc(duplicate.partnerRef)} · ${esc(human(duplicate.matchBasis))}</p><small>Admin Synthetic 2 recorded “continue as distinct” with an evidence-based reason. Activation is still a separate decision.</small></article>`;
  else if(reviewState==='revision')review=`<article class="decision"><strong>Correction awaits independent review</strong><p>Version 2 is pending. Version 1 remains active until the correction is accepted.</p><small>No active facts were overwritten.</small></article>`;
  else review=`<article class="decision"><strong>Independent verification required</strong><p>A different Administrator must review the legal identity and source evidence before activation.</p><small>Missing optional licence details do not block verification.</small></article>`;
  document.querySelector('#review').innerHTML=review;
  document.querySelector('#history').innerHTML=versions.map(item=>`<article><div class="history-head"><strong>Version ${item.version}</strong><span class="pill ${item.status==='active'?'active-pill':''}">${esc(human(item.status))}</span></div><span>Immutable evidence version</span><span>Supersedes: ${esc(item.supersedesPartnerVersionRef||'None')}</span></article>`).join('');
}
document.querySelector('#partner-type').addEventListener('change',render);document.querySelector('#scenario').addEventListener('change',render);render();
