const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const compatible={developer:{relationship:'Developer',company:'NYSA-COMP-SYN-014',name:'Synthetic Developments LLC',version:1},external_agency:{relationship:'Listing source agency',company:'NYSA-COMP-SYN-021',name:'Synthetic Partner Brokerage LLC',version:3},referral_partner:{relationship:'Referral source',company:'NYSA-COMP-SYN-032',name:'Synthetic Referral Network LLC',version:1}};
function render(){
  const origin=document.querySelector('#inventory-origin').value,scenario=document.querySelector('#organization-scenario').value,item=compatible[origin],box=document.querySelector('#inventory-link'),history=document.querySelector('#event-history');
  if(!item){box.innerHTML=`<article class="link-state neutral"><div><strong>No Partner Master relationship required</strong><p>${origin==='direct_owner'?'The secured Inventory Party remains the ownership authority.':'Portal/import provenance remains governed by its existing source evidence.'}</p></div><span class="pill">Inventory save allowed</span></article>`;history.innerHTML='<article><strong>No organization link event</strong><span>The existing Inventory record remains unchanged.</span></article>';return;}
  if(scenario==='active'){box.innerHTML=`<article class="link-state ready"><div><span>${esc(item.relationship)}</span><strong>${esc(item.name)}</strong><p>${esc(item.company)} · governed version ${item.version} · verified and active</p><small>This adds provenance only. Existing developer text and ownership remain unchanged.</small></div><span class="pill active-pill">Ready to link</span></article>`;history.innerHTML=`<article><strong>New linked event preview</strong><span>${esc(item.relationship)} · ${esc(item.company)} · version ${item.version}</span><span>Reason required when replacing or unlinking this relationship later.</span></article>`;return;}
  const pending=scenario==='pending';box.innerHTML=`<article class="link-state warning"><div><strong>${pending?'Organization review is incomplete':'No governed organization is maintained'}</strong><p>${pending?'The Company has a pending evidence version and cannot be linked yet.':'Continue without a link or ask an Administrator to govern the existing Company later.'}</p><small>Organization relationship may be completed later.</small></div><span class="pill">Inventory save allowed</span></article>`;history.innerHTML='<article><strong>No organization link event</strong><span>Saving Inventory does not create an inferred relationship.</span></article>';
}
document.querySelector('#inventory-origin').addEventListener('change',render);document.querySelector('#organization-scenario').addEventListener('change',render);render();
