import zlib from 'node:zlib';

const PAGE={width:595,height:842,margin:42};
const C={ink:[0.10,0.12,0.11],muted:[0.42,0.44,0.41],gold:[0.62,0.47,0.20],pale:[0.95,0.94,0.91],line:[0.84,0.83,0.79],white:[1,1,1]};
const clean=value=>String(value??'').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7e]/g,' ').replace(/\s+/g,' ').trim();
const pdfText=value=>clean(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const color=values=>values.join(' ');
const money=(value,currency='AED')=>value===null||value===undefined?'Not recorded':`${currency} ${Number(value).toLocaleString('en-US',{maximumFractionDigits:0})}`;
const date=value=>value?new Intl.DateTimeFormat('en-AE',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'Reconfirm before viewing';
const label=value=>clean(String(value||'').replaceAll('_',' ')).replace(/\b\w/g,x=>x.toUpperCase());

function wrap(value,maxWidth,size=10){
  const words=clean(value).split(' ').filter(Boolean),lines=[];let line='';
  const width=text=>text.length*size*0.51;
  for(const word of words){const next=line?`${line} ${word}`:word;if(width(next)<=maxWidth||!line)line=next;else{lines.push(line);line=word;}}
  if(line)lines.push(line);return lines.length?lines:[''];
}

function jpegSize(buffer){
  let offset=2;while(offset+8<buffer.length){if(buffer[offset]!==0xff){offset++;continue;}const marker=buffer[offset+1],length=buffer.readUInt16BE(offset+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{width:buffer.readUInt16BE(offset+7),height:buffer.readUInt16BE(offset+5)};if(length<2)break;offset+=2+length;}return null;
}
function unfilterPng(raw,width,height,channels){
  const stride=width*channels,out=Buffer.alloc(stride*height);let source=0;
  for(let row=0;row<height;row++){const filter=raw[source++];for(let x=0;x<stride;x++){const value=raw[source++],left=x>=channels?out[row*stride+x-channels]:0,up=row?out[(row-1)*stride+x]:0,upperLeft=row&&x>=channels?out[(row-1)*stride+x-channels]:0;let predictor=0;if(filter===1)predictor=left;else if(filter===2)predictor=up;else if(filter===3)predictor=Math.floor((left+up)/2);else if(filter===4){const p=left+up-upperLeft,pa=Math.abs(p-left),pb=Math.abs(p-up),pc=Math.abs(p-upperLeft);predictor=pa<=pb&&pa<=pc?left:pb<=pc?up:upperLeft;}out[row*stride+x]=(value+predictor)&255;}}
  return out;
}
function pngImage(buffer){
  if(buffer.readUInt32BE(0)!==0x89504e47)return null;const width=buffer.readUInt32BE(16),height=buffer.readUInt32BE(20),depth=buffer[24],type=buffer[25],interlace=buffer[28];if(depth!==8||interlace!==0||![0,2,4,6].includes(type))return null;const channels={0:1,2:3,4:2,6:4}[type],chunks=[];for(let p=8;p+12<=buffer.length;){const length=buffer.readUInt32BE(p),name=buffer.subarray(p+4,p+8).toString();if(name==='IDAT')chunks.push(buffer.subarray(p+8,p+8+length));p+=12+length;if(name==='IEND')break;}const pixels=unfilterPng(zlib.inflateSync(Buffer.concat(chunks)),width,height,channels),colors=type===0||type===4?1:3,rgb=Buffer.alloc(width*height*colors),alpha=(type===4||type===6)?Buffer.alloc(width*height):null;for(let i=0,j=0,a=0;i<pixels.length;i+=channels){if(colors===1)rgb[j++]=pixels[i];else{rgb[j++]=pixels[i];rgb[j++]=pixels[i+1];rgb[j++]=pixels[i+2];}if(alpha)alpha[a++]=pixels[i+channels-1];}return{width,height,colors,data:zlib.deflateSync(rgb),alpha:alpha?zlib.deflateSync(alpha):null};
}

class PdfDoc{
  constructor(){this.objects=[];this.pages=[];this.catalog=this.add('');this.pagesId=this.add('');this.regular=this.add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');this.bold=this.add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');this.images=[];}
  add(value){this.objects.push(value);return this.objects.length;}
  image(buffer,mediaType){try{if(mediaType==='image/jpeg'){const size=jpegSize(buffer);if(!size)return null;const id=this.add(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${size.width} /Height ${size.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${buffer.length} >>\nstream\n`),buffer,Buffer.from('\nendstream')]));return{id,width:size.width,height:size.height};}if(mediaType==='image/png'){const png=pngImage(buffer);if(!png)return null;const smask=png.alpha?this.add(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${png.width} /Height ${png.height} /ColorSpace /DeviceGray /BitsPerComponent 8 /Filter /FlateDecode /Length ${png.alpha.length} >>\nstream\n`),png.alpha,Buffer.from('\nendstream')])):null;const dict=`<< /Type /XObject /Subtype /Image /Width ${png.width} /Height ${png.height} /ColorSpace /Device${png.colors===1?'Gray':'RGB'} /BitsPerComponent 8 /Filter /FlateDecode${smask?` /SMask ${smask} 0 R`:''} /Length ${png.data.length} >>\nstream\n`;const id=this.add(Buffer.concat([Buffer.from(dict),png.data,Buffer.from('\nendstream')]));return{id,width:png.width,height:png.height};}}catch{}return null;}
  page(commands,images={}){const content=commands.join('\n'),stream=this.add(`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`),xobjects=Object.entries(images).map(([name,img])=>`/${name} ${img.id} 0 R`).join(' '),page=this.add(`<< /Type /Page /Parent ${this.pagesId} 0 R /MediaBox [0 0 ${PAGE.width} ${PAGE.height}] /Resources << /Font << /F1 ${this.regular} 0 R /F2 ${this.bold} 0 R >>${xobjects?` /XObject << ${xobjects} >>`:''} >> /Contents ${stream} 0 R >>`);this.pages.push(page);}
  finish(){this.objects[this.catalog-1]=`<< /Type /Catalog /Pages ${this.pagesId} 0 R >>`;this.objects[this.pagesId-1]=`<< /Type /Pages /Kids [${this.pages.map(x=>`${x} 0 R`).join(' ')}] /Count ${this.pages.length} >>`;let out=Buffer.from('%PDF-1.4\n'),offsets=[0];for(let i=0;i<this.objects.length;i++){offsets.push(out.length);const object=Buffer.isBuffer(this.objects[i])?this.objects[i]:Buffer.from(this.objects[i]);out=Buffer.concat([out,Buffer.from(`${i+1} 0 obj\n`),object,Buffer.from('\nendobj\n')]);}const xref=out.length;out=Buffer.concat([out,Buffer.from(`xref\n0 ${this.objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${this.objects.length+1} /Root ${this.catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`)]);return out;}
}

function canvas(){const c=[];return{c,rect(x,y,w,h,fill=C.pale,stroke=null){c.push(`${color(fill)} rg${stroke?` ${color(stroke)} RG`:''} ${x} ${PAGE.height-y-h} ${w} ${h} re ${stroke?'B':'f'}`);},line(x1,y1,x2,y2,stroke=C.line,width=1){c.push(`${color(stroke)} RG ${width} w ${x1} ${PAGE.height-y1} m ${x2} ${PAGE.height-y2} l S`);},text(value,x,y,{size=10,bold=false,fill=C.ink}={}){c.push(`${color(fill)} rg BT /F${bold?'2':'1'} ${size} Tf ${x} ${PAGE.height-y-size} Td (${pdfText(value)}) Tj ET`);},paragraph(value,x,y,width,{size=10,bold=false,fill=C.ink,leading=size*1.32,maxLines=99}={}){const lines=wrap(value,width,size).slice(0,maxLines);lines.forEach((line,i)=>this.text(line,x,y+i*leading,{size,bold,fill}));return lines.length*leading;},image(name,img,x,y,w,h){const scale=Math.min(w/img.width,h/img.height),dw=img.width*scale,dh=img.height*scale,dx=x+(w-dw)/2,dy=PAGE.height-y-(h+dh)/2;c.push(`q ${dw} 0 0 ${dh} ${dx} ${dy} cm /${name} Do Q`);}};}
function header(draw,organization,logo,pageNo,total){if(logo)draw.image('Logo',logo,PAGE.margin,28,70,46);draw.text(organization.displayName||'NYSA Realty',logo?122:PAGE.margin,36,{size:13,bold:true});draw.text('PRIVATE BUYER PROPOSAL',logo?122:PAGE.margin,56,{size:7,bold:true,fill:C.gold});draw.text(`Page ${pageNo} of ${total}`,500,47,{size:7,fill:C.muted});draw.line(PAGE.margin,86,PAGE.width-PAGE.margin,86,C.gold,1.5);}
function footer(draw,organization,disclaimer){draw.line(PAGE.margin,790,PAGE.width-PAGE.margin,790,C.line,.7);draw.paragraph(disclaimer,PAGE.margin,798,390,{size:6.5,fill:C.muted,maxLines:2,leading:8});draw.text(organization.proposalFooter||`${organization.displayName} | Private customer proposal`,405,809,{size:6.5,fill:C.muted});}
function chip(draw,value,x,y){const width=Math.min(112,Math.max(48,clean(value).length*5.5+18));draw.rect(x,y,width,22,C.pale,C.line);draw.text(value,x+9,y+6,{size:7.5});return width;}

export function makeProposalPdf(data){
  const {proposal,version,organization,recipient,requirement,properties,narrative,disclaimer,media=[],logo=null}=data,doc=new PdfDoc(),logoImage=logo?doc.image(logo.buffer,logo.mediaType):null,mediaImages=new Map();for(const item of media){const image=doc.image(item.buffer,item.mediaType);if(image)mediaImages.set(item.id,image);}const propertyPages=Math.max(1,properties.length),total=2+propertyPages;
  {
    const d=canvas(),images={};if(logoImage)images.Logo=logoImage;header(d,organization,logoImage,1,total);d.text('YOUR DUBAI PROPERTY SHORTLIST',PAGE.margin,112,{size:20,bold:true,fill:C.gold});d.text(`${clean(proposal.title)} - Version ${version}`,PAGE.margin,143,{size:9,fill:C.muted});d.rect(PAGE.margin,174,511,92,C.pale,C.line);const identity=recipient.idDocumentType&&recipient.idDocumentLast4?`${recipient.idDocumentType==='emirates_id'?'Emirates ID':'Passport'} ending ${recipient.idDocumentLast4}`:'Not recorded';[['PREPARED FOR',recipient.fullName],['CUSTOMER ADDRESS',recipient.postalAddress||'Not recorded'],['MOBILE',recipient.phone||'Not recorded'],['IDENTITY REFERENCE',identity]].forEach(([k,v],i)=>{const x=PAGE.margin+(i%2)*255,y=188+Math.floor(i/2)*40;d.text(k,x+12,y,{size:6.5,bold:true,fill:C.gold});d.text(v,x+12,y+13,{size:9,bold:true});});d.text('YOUR REQUIREMENTS',PAGE.margin,292,{size:10,bold:true,fill:C.gold});const chips=[label(requirement.businessLine),label(requirement.purpose),...(requirement.areas||[]).slice(0,2),...(requirement.propertyTypes||[]).slice(0,2),requirement.bedroomsMin?`${requirement.bedroomsMin}+ bedrooms`:null,requirement.budgetMin||requirement.budgetMax?`${money(requirement.budgetMin,organization.defaultCurrency)} - ${money(requirement.budgetMax,organization.defaultCurrency)}`:null,label(requirement.fundingMethod),requirement.timelineCode].filter(Boolean);let x=PAGE.margin,y=313;for(const value of chips){const width=Math.min(112,Math.max(48,clean(value).length*5.5+18));if(x+width>PAGE.width-PAGE.margin){x=PAGE.margin;y+=29;}x+=chip(d,value,x,y)+7;}y+=42;d.text('RECOMMENDED MATCHES',PAGE.margin,y,{size:10,bold:true,fill:C.gold});d.text(`${properties.length} shortlisted ${properties.length===1?'property':'properties'}`,430,y,{size:7.5,fill:C.muted});y+=24;properties.forEach((p,i)=>{d.rect(PAGE.margin,y,511,74,i%2?C.white:C.pale,C.line);d.text(`MATCH ${i+1}`,PAGE.margin+12,y+10,{size:7,bold:true,fill:C.gold});d.text(p.project,PAGE.margin+72,y+9,{size:11,bold:true});d.text(`Inventory ID: ${p.inventoryReference||'Not recorded'}`,PAGE.margin+72,y+27,{size:7,fill:C.muted});d.text(`${p.area} | ${p.propertyType} | ${p.bedrooms||'-'} bed | ${p.sizeSqft?Number(p.sizeSqft).toLocaleString('en-US')+' sq ft':'Size not recorded'}`,PAGE.margin+72,y+43,{size:8});d.text(money(p.price,p.currency||organization.defaultCurrency),435,y+11,{size:10,bold:true,fill:C.gold});d.text(`Availability: ${date(p.availabilityConfirmedAt)}`,370,y+43,{size:7,fill:C.muted});y+=74;});d.text('Prepared by',PAGE.margin,744,{size:7,bold:true,fill:C.gold});d.text(`${data.agent.name} | ${data.preparedAt}`,PAGE.margin,757,{size:8});footer(d,organization,disclaimer);doc.page(d.c,images);
  }
  properties.forEach((p,index)=>{
    const d=canvas(),images={};if(logoImage)images.Logo=logoImage;header(d,organization,logoImage,index+2,total);d.text(`MATCH ${index+1} OF ${properties.length}`,PAGE.margin,109,{size:7,bold:true,fill:C.gold});d.text(p.project,PAGE.margin,126,{size:18,bold:true});d.text(`${p.area} | ${p.propertyType} | ${p.handoverDate||'Handover not recorded'}`,PAGE.margin,151,{size:8,fill:C.muted});d.text(money(p.price,p.currency||organization.defaultCurrency),420,126,{size:14,bold:true,fill:C.gold});const chosen=media.filter(x=>x.listingId===p.id).slice(0,2);for(let slot=0;slot<2;slot++){const item=chosen[slot],img=item&&mediaImages.get(item.id),name=`M${index}_${slot}`;d.rect(PAGE.margin+slot*258,181,247,150,C.pale,C.line);if(img){images[name]=img;d.image(name,img,PAGE.margin+slot*258+3,184,241,128);d.text(item.caption||item.title||`Approved image ${slot+1}`,PAGE.margin+slot*258+8,315,{size:6.5,fill:C.muted});}else d.text('No approved image selected',PAGE.margin+slot*258+65,250,{size:8,fill:C.muted});}const facts=[['INVENTORY ID',p.inventoryReference||'Not recorded'],['BUILT-UP AREA',p.sizeSqft?`${Number(p.sizeSqft).toLocaleString('en-US')} sq ft`:'Not recorded'],['DEVELOPER',p.developer||'Not recorded'],['BEDROOMS',p.bedrooms||'Not recorded'],['PARKING',p.parkingSpaces||'Not recorded'],['AVAILABILITY',date(p.availabilityConfirmedAt)]];facts.forEach(([k,v],i)=>{const col=i%3,row=Math.floor(i/3),x=PAGE.margin+col*170,y=354+row*58;d.rect(x,y,162,50,C.pale,C.line);d.text(k,x+9,y+8,{size:6.2,bold:true,fill:C.gold});d.paragraph(v,x+9,y+22,144,{size:8.5,bold:true,maxLines:2});});let y=480;[['WHY IT MATCHES',narrative.suitability||'Selected against the recorded customer requirements and current inventory facts.'],['HIGHLIGHTS',narrative.highlights||'Review the verified property facts, availability and approved media above.'],['IMPORTANT TRADE-OFFS',narrative.assumptions||'Availability, price and property particulars remain subject to reconfirmation.']].forEach(([k,v])=>{d.text(k,PAGE.margin,y,{size:7,bold:true,fill:C.gold});y+=14;y+=d.paragraph(v,PAGE.margin,y,500,{size:9,leading:12,maxLines:4})+12;});footer(d,organization,disclaimer);doc.page(d.c,images);
  });
  {
    const d=canvas(),images={};if(logoImage)images.Logo=logoImage;header(d,organization,logoImage,total,total);d.text('INDICATIVE PURCHASE JOURNEY',PAGE.margin,112,{size:15,bold:true,fill:C.gold});d.text(`Customer timing: ${requirement.timelineCode||'To be confirmed'}`,PAGE.margin,138,{size:8,fill:C.muted});const stages=narrative.indicativeTimeline?.stages||[];let y=178;stages.slice(0,7).forEach((stage,i)=>{d.rect(PAGE.margin,y,28,28,C.gold);d.text(String(i+1),PAGE.margin+10,y+7,{size:10,bold:true,fill:C.white});d.line(PAGE.margin+14,y+28,PAGE.margin+14,y+48,C.gold,1.2);d.text(stage.label,PAGE.margin+45,y+1,{size:10,bold:true});d.paragraph(stage.guidance,PAGE.margin+45,y+18,450,{size:8,fill:C.muted,maxLines:2,leading:10});y+=63;});d.text('NEXT STEPS',PAGE.margin,655,{size:10,bold:true,fill:C.gold});['Confirm the shortlist','Arrange property viewing','Reconfirm finance and transaction readiness'].forEach((value,i)=>{const x=PAGE.margin+i*170;d.rect(x,677,160,50,C.pale,C.line);d.rect(x+10,689,24,24,C.gold);d.text(String(i+1),x+19,695,{size:8,bold:true,fill:C.white});d.paragraph(value,x+43,688,105,{size:8,bold:true,maxLines:2,leading:10});});footer(d,organization,disclaimer);doc.page(d.c,images);
  }
  return doc.finish();
}
